In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import nltk

from functions import *

In [2]:
# #show full text of columns
# pd.set_option('display.max_colwidth', -1)
# #show all columns
# pd.set_option('display.max_columns', None)
# #show 3 rows only
# # pd.set_option('display.max_rows', 5)
# # show 10 rows only
# pd.set_option('display.max_rows', 10)

ValueError: Value must be a nonnegative integer or None

In [3]:
#import man_full_dayun.csv
man_df = pd.read_csv(r"man_df_18_5_2023.csv")

In [4]:
man_df

,uniqueid,Divorce_date,Date_of_marriage,Age_partner_man,Marriage_duration,Type_of_divorce,Num_Children,DOB_partner_man,Level_of_education_partner_man,year_of_marriage,...,marri_age_group,man大運財透干2,man大運財得地2,man大運日支六沖,man大運日支六合,man大運日干五合,man大運日柱天地合,man財透干2,man財得地2,man流年大運地支伏吟
0,0,2006-06-09,2000-06-26,30.0,5.0,Necesario,1.0,1975-12-18,SECUNDARIA,2000,...,21-30,False,False,False,False,False,False,False,False,False
1,1,2005-02-01,1975-12-18,49.0,NaN,Necesario,NaN,1955-02-22,PREPARATORIA,1975,...,0-20,False,False,False,False,False,False,False,False,False
2,2,2006-02-01,1987-12-03,42.0,18.0,Necesario,2.0,1964-01-20,PROFESIONAL,1987,...,21-30,True,True,False,False,True,False,False,False,False
3,3,2006-02-01,1998-11-14,30.0,7.0,Necesario,2.0,1975-10-30,PROFESIONAL,1998,...,21-30,False,False,False,False,True,False,False,False,False
4,4,2006-02-01,1995-01-20,32.0,11.0,Necesario,2.0,1973-03-28,SECUNDARIA,1995,...,21-30,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4530,4537,2012-10-31,2008-10-25,35.0,3.0,Voluntario,NaN,1977-10-29,PROFESIONAL,2008,...,21-30,False,False,False,False,False,False,False,True,False
4531,4538,2013-10-31,2012-05-26,30.0,1.0,Voluntario,NaN,1982-11-10,PROFESIONAL,2012,...,21-30,False,False,False,False,False,False,False,False,False
4532,4539,2013-10-31,1978-06-02,59.0,35.0,Voluntario,2.0,1954-10-28,PROFESIONAL,1978,...,21-30,False,False,False,False,False,False,False,False,False
4533,4540,2012-12-31,1979-11-05,54.0,33.0,Voluntario,2.0,1958-02-07,PREPARATORIA,1979,...,0-20,False,True,False,False,False,False,True,True,False
4534,4541,2013-12-31,2009-08-22,53.0,4.0,Voluntario,NaN,1960-06-22,PROFESIONAL,2009,...,41-50,False,False,True,False,False,False,False,False,False

In [5]:
#get all the col names of the dataframe
man_df.columns

Index(['uniqueid', 'Divorce_date', 'Date_of_marriage', 'Age_partner_man',
       'Marriage_duration', 'Type_of_divorce', 'Num_Children',
       'DOB_partner_man', 'Level_of_education_partner_man', 'year_of_marriage',
       'year_of_DOB', 'year_of_Divorse', 'month_of_DOB', 'day_of_DOB', 'DONE',
       'dayun', 'man時干', 'man時支', 'man日干', 'man日支', 'man月干', 'man月支', 'man年干',
       'man年支', 'Year_marriage_ganzhi', 'man日支同年支', 'man日支六沖', 'man日支六合',
       'man流年天干十神', 'man流年地支十神', 'man財透干', 'man財得地', 'man日干五合', 'man日柱天地合',
       'man流年雙體財', 'man日干支關係', 'man日支半三合', 'man日支半三會局', 'man日支暗合',
       'man流年大運天地合', 'man流年大運伏吟', '當令', 'man大運天干十神', 'man大運地支十神', 'man大運財透干',
       'man大運財得地', 'man年干十神', 'man年支十神', 'man月干十神', 'man月支十神', '年月有多少財',
       '年月有多少官', '本命日支六合', '本命日支三合', '本命日支被三合或六合', '日支大運六合', '日支大運三合',
       '日支被大運三合或六合', '流年之前日支被合', 'marriage_age', 'marri_age_group',
       'man大運財透干2', 'man大運財得地2', 'man大運日支六沖', 'man大運日支六合', 'man大運日干五合',
       'man大運日柱天地合', 'man財透干2', 'man財得地2', 'man流年大運地支伏吟'],
      dtype='object')

In [ ]:
man_df['man日干大運地支伏吟'] = man_df.apply(lambda row: True if row['man日干'] == row['dayun'][1] else False, axis=1)
#drop the col man流年大運地支伏吟

man_df=man_df.drop('man流年大運地支伏吟', axis=1)

In [ ]:
#定身強弱
sanhui = {
    '木': ['寅', '卯', '辰'],
    '火': ['巳', '午', '未'],
    '金': ['申', '酉', '戌'],
    '水': ['亥', '子', '丑'],
    '土': [ '辰','戌','丑','未' ]
}

sanhe = {
    '火': ['寅', '午', '戌'],
    '水': ['申', '子', '辰'],
    '金': ['巳', '酉', '丑'],
    '木': ['亥', '卯', '未'],
    '土': [ '辰','戌','丑','未' ]
}

def 強弱得令(man日干,man月支):
    if man月支 in sanhui[wu_xing_dict[man日干]]:
        return True
    else:
        return False
    
def 強弱得地(man日干,man日支,man年支):
    wx=wu_xing_dict[man日干]
    if wx==wu_xing_dict[man日支] and wx==wu_xing_dict[man年支]:
        return True
    else:
        return False

def 強弱得勢(man日干,man月干,man年干):
    wx=wu_xing_dict[man日干]
    if wx==wu_xing_dict[man月干] or wx==wu_xing_dict[man年干]:
        return True
    else:
        return False

# def 地支半三合(man日干,man日支,man月支,man年支):
    # wx=wu_xing_dict[man日干]
    # if any of two from (man日支,man月支,man年支) are distinct and in sanhui[wx], then true


# def 地支三合(man日干,man日支,man月支,man年支):
#     wx=wu_xing_dict[man日干]
    # if all man日支,man月支,man年支 are distinct and in sanhui[wx], then true


def 強弱地支半三合(man日干, man日支, man月支, man年支):
    wx = wu_xing_dict[man日干]
    zodiacs = sanhe[wx]
    distinct_zodiacs = {man日支, man月支, man年支}
    common_zodiacs = set(zodiacs).intersection(distinct_zodiacs)
    return len(common_zodiacs) >= 2


def 強弱地支三合(man日干, man日支, man月支, man年支):
    wx = wu_xing_dict[man日干]
    zodiacs = sanhe[wx]
    distinct_zodiacs = {man日支, man月支, man年支}
    return distinct_zodiacs.issubset(zodiacs) and len(distinct_zodiacs) == 3

def 強弱地支半三會(man日干, man日支, man月支, man年支):
    wx = wu_xing_dict[man日干]
    zodiacs = sanhui[wx]
    distinct_zodiacs = {man日支, man月支, man年支}
    common_zodiacs = set(zodiacs).intersection(distinct_zodiacs)
    return len(common_zodiacs) >= 2


def 強弱地支三會(man日干, man日支, man月支, man年支):
    wx = wu_xing_dict[man日干]
    zodiacs = sanhui[wx]
    distinct_zodiacs = {man日支, man月支, man年支}
    return distinct_zodiacs.issubset(zodiacs) and len(distinct_zodiacs) == 3

sheng_dict = {
    '金': ['水'],
    '木': ['火'],
    '水': ['木'],
    '火': ['土'],
    '土': ['金']
}
# def 印的數量(man日干, man日支, man月干,man月支, man年干,man年支):
    # if man日支, man月干,man月支, man年干,man年支 are 印 of man日干, then return 5
    # if sheng_dict[man日支] == wu_xing_dict[man日干], then it is 印

def 強弱印的數量(man日干, man日支, man月干, man月支, man年干, man年支):

    count = 0
    if sheng_dict[wu_xing_dict[man日支]] == wu_xing_dict[man日干]:
        count += 1
    if sheng_dict[wu_xing_dict[man月干]] == wu_xing_dict[man日干]:
        count += 1
    if sheng_dict[wu_xing_dict[man月支]] == wu_xing_dict[man日干]:
        count += 1
    if sheng_dict[wu_xing_dict[man年干]] == wu_xing_dict[man日干]:
        count += 1
    if sheng_dict[wu_xing_dict[man年支]] == wu_xing_dict[man日干]:
        count += 1
    return count


import pandas as pd

# Assuming you have a DataFrame called man_df with the relevant columns

man_df['強弱得令'] = man_df.apply(lambda row: 強弱得令(row['man日干'], row['man月支']), axis=1)
man_df['強弱地支三會'] = man_df.apply(lambda row: 強弱地支三會(row['man日干'], row['man日支'], row['man月支'], row['man年支']), axis=1)
man_df['強弱地支三合'] = man_df.apply(lambda row: 強弱地支三合(row['man日干'], row['man日支'], row['man月支'], row['man年支']), axis=1)
man_df['強弱得地'] = man_df.apply(lambda row: 強弱得地(row['man日干'], row['man日支'], row['man年支']), axis=1)
man_df['強弱得勢'] = man_df.apply(lambda row: 強弱得勢(row['man日干'], row['man月干'], row['man年干']), axis=1)
man_df['強弱地支半三合'] = man_df.apply(lambda row: 強弱地支半三合(row['man日干'], row['man日支'], row['man月支'], row['man年支']), axis=1)
man_df['強弱地支半三會'] = man_df.apply(lambda row: 強弱地支半三會(row['man日干'], row['man日支'], row['man月支'], row['man年支']), axis=1)

man_df['強弱印的數量'] = man_df.apply(lambda row: 強弱印的數量(row['man日干'], row['man日支'], row['man月干'], row['man月支'], row['man年干'], row['man年支']), axis=1)

# Assuming 'man日干', 'man日支', 'man月支', 'man年支', 'man月干', 'man年干' are column names in the DataFrame

In [ ]:
#create new col named 身強身弱
# if 強弱得令 is true,  then 身強身弱 is 強 
# elif 強弱地支三會 is true,  then 身強身弱 is 強
# elif 強弱地支三合 is true,  then 身強身弱 is 強
# elif 強弱印的數量 is 4,  then 身強身弱 is 強
# elif 強弱地支半三會 is true,  then 身強身弱 is 可能強
# elif 強弱地支半三合 is true,  then 身強身弱 is 可能強
# elif 強弱印的數量 is 3,  then 身強身弱 is 可能強
# elif 強弱得地 is true,  then 身強身弱 is 可能強 
# elif 強弱得勢 is true,  then 身強身弱 is 可能強
# else 身強身弱 is 弱

man_df['身強身弱'] = ''

for index, row in man_df.iterrows():
    if row['強弱得令']:
        man_df.at[index, '身強身弱'] = '強'
    elif row['強弱地支三會']:
        man_df.at[index, '身強身弱'] = '強'
    elif row['強弱地支三合']:
        man_df.at[index, '身強身弱'] = '強'
    elif 強弱印的數量(row['man日干'], row['man日支'], row['man月干'], row['man月支'], row['man年干'], row['man年支']) == 4:
        man_df.at[index, '身強身弱'] = '強'
    elif row['強弱地支半三會']:
        man_df.at[index, '身強身弱'] = '可能強'
    elif row['強弱地支半三合']:
        man_df.at[index, '身強身弱'] = '可能強'
    elif 強弱印的數量(row['man日干'], row['man日支'], row['man月干'], row['man月支'], row['man年干'], row['man年支']) == 3:
        man_df.at[index, '身強身弱'] = '可能強'
    elif row['強弱得地']:
        man_df.at[index, '身強身弱'] = '可能強'
    elif row['強弱得勢']:
        man_df.at[index, '身強身弱'] = '可能強'
    else:
        man_df.at[index, '身強身弱'] = '弱'

In [ ]:
man_df

,uniqueid,Divorce_date,Date_of_marriage,Age_partner_man,Marriage_duration,Type_of_divorce,Num_Children,DOB_partner_man,Level_of_education_partner_man,year_of_marriage,year_of_DOB,year_of_Divorse,month_of_DOB,day_of_DOB,DONE,dayun,man時干,man時支,man日干,man日支,man月干,man月支,man年干,man年支,Year_marriage_ganzhi,man日支同年支,man日支六沖,man日支六合,man流年天干十神,man流年地支十神,man財透干,man財得地,man日干五合,man日柱天地合,man流年雙體財,man日干支關係,man日支半三合,man日支半三會局,man日支暗合,man流年大運天地合,man流年大運伏吟,當令,man大運天干十神,man大運地支十神,man大運財透干,man大運財得地,man年干十神,man年支十神,man月干十神,man月支十神,年月有多少財,年月有多少官,本命日支六合,本命日支三合,本命日支被三合或六合,日支大運六合,日支大運三合,日支被大運三合或六合,流年之前日支被合,marriage_age,marri_age_group,man大運財透干2,man大運財得地2,man大運日支六沖,man大運日支六合,man大運日干五合,man大運日柱天地合,man財透干2,man財得地2,man日干大運地支伏吟,強弱得令,強弱得地,強弱得勢,強弱地支半三合,強弱地支三合,強弱地支半三會,強弱地支三會,強弱印的數量,身強身弱
0,0,2006-06-09,2000-06-26,30.0,5.0,Necesario,1.0,1975-12-18,SECUNDARIA,2000,1975,2006,12,18,1,乙酉,壬,子,戊,戌,戊,子,乙,卯,庚辰,False,True,False,食神,比肩,False,False,False,False,False,比和,False,False,False,True,False,0,正官,傷官,False,False,正官,正官,比肩,正財,1,2,yes,no,yes,no,no,no,yes,25,21-30,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,0,可能強
1,1,2005-02-01,1975-12-18,49.0,NaN,Necesario,NaN,1955-02-22,PREPARATORIA,1975,1955,2005,2,22,1,丙子,甲,子,甲,寅,戊,寅,乙,未,乙卯,False,False,False,劫財,劫財,False,False,False,False,False,比和,False,True,False,False,False,1,食神,正印,False,False,劫財,正財,偏財,比肩,2,0,no,no,no,no,no,no,no,20,0-20,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,0,強
2,2,2006-02-01,1987-12-03,42.0,18.0,Necesario,2.0,1964-01-20,PROFESIONAL,1987,1964,2006,1,20,1,癸亥,壬,子,戊,辰,乙,丑,癸,卯,丁卯,False,False,False,正印,正官,False,False,False,False,False,比和,False,True,False,False,False,1,正財,偏財,True,True,正財,正官,正官,劫財,1,2,no,no,no,no,no,no,no,23,21-30,True,True,False,False,True,False,False,False,False,True,False,False,True,False,True,False,0,強
3,3,2006-02-01,1998-11-14,30.0,7.0,Necesario,2.0,1975-10-30,PROFESIONAL,1998,1975,2006,10,30,1,甲申,甲,子,己,酉,丙,戌,乙,卯,戊寅,False,False,False,劫財,正官,False,False,False,False,False,日干生日支,False,False,False,False,False,1,正官,傷官,False,False,七殺,七殺,正印,劫財,0,2,no,no,no,no,no,no,no,23,21-30,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,0,強
4,4,2006-02-01,1995-01-20,32.0,11.0,Necesario,2.0,1973-03-28,SECUNDARIA,1995,1973,2006,3,28,1,癸丑,壬,子,癸,亥,乙,卯,癸,丑,乙亥,True,False,False,食神,劫財,False,False,False,False,False,比和,False,False,False,False,False,0,比肩,七殺,False,False,比肩,七殺,食神,食神,0,1,no,no,no,no,no,no,no,22,21-30,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,0,可能強
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4530,4537,2012-10-31,2008-10-25,35.0,3.0,Voluntario,NaN,1977-10-29,PROFESIONAL,2008,1977,2012,10,29,1,丁未,甲,子,己,未,庚,戌,丁,巳,戊子,False,False,False,劫財,偏財,False,True,False,False,False,比和,False,False,False,False,False,1,偏印,比肩,False,False,偏印,偏印,傷官,劫財,0,0,no,no,no,no,no,no,no,31,21-30,False,False,False,False,False,False,False,True,False,True,False,False,True,False,True,False,0,強
4531,4538,2013-10-31,2012-05-26,30.0,1.0,Voluntario,NaN,1982-11-10,PROFESIONAL,2012,1982,2013,11,10,1,甲寅,庚,子,丁,酉,辛,亥,壬,戌,壬辰,False,False,True,正官,傷官,False,False,True,True,False,日干剋日支,False,False,False,False,False,0,正印,正印,False,False,正官,傷官,偏財,正官,1,2,no,no,no,no,no,no,no,30,21-30,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0,弱
4532,4539,2013-10-31,1978-06-02,59.0,35.0,Voluntario,2.0,1954-10-28,PROFESIONAL,1978,1954,2013,10,28,1,丁丑,庚,子,丁,巳,甲,戌,甲,午,戊午,False,False,False,傷官,劫財,False,False,False,False,False,比和,False,True,False,False,False,0,比肩,食神,False,False,正印,劫財,正印,傷官,0,0,no,no,no,no,no,no,no,24,21-30,False,False,False,False,False,False,False,False,False,False,True,False,True,False,True,False,0,可能強
4533,4540,2012-12-31,1979-11-05,54.0,33.0,Voluntario,2.0,1958-02-07,PREPARATORIA,1979,1958,2012,2,7,1,丙辰,丙,子,乙,卯,甲,寅,戊,戌,己未,False,False,False,偏財,偏財,True,True,False,False,True,比和,True,False,False,False,False,1,傷官,正財,False,True,正財,正財,劫財,劫財,2,0,yes,no,yes,no,no,no,yes,21,0-20,False,True,False,False,False,False,True,True,False,True,False,True,False,False,True,False,0,強
4534,4541,2013-12-31,2009-08-22,53.0,4.0,Voluntario,NaN,1960-06-22,PROFESIONAL,2009,1960,2013,6,22,1,丁亥,戊,子,辛,巳,壬,午,庚,子,己丑,False,False,False,偏印,偏印,False,False,False,False,False,日支剋日干,True,False,False,False,False,0,七殺,傷官,False,False,劫財,食神,傷官,正官,0,1,no,no,no,no,no,no,no,49,41-50,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,0,可能強

In [ ]:
# drop man大運財透干2	man大運財得地2 man財透干2 man財得地2
man_df.drop(['man大運財透干2', 'man大運財得地2', 'man財透干2', 'man財得地2'], axis=1, inplace=True)

In [ ]:
man_df

,uniqueid,Divorce_date,Date_of_marriage,Age_partner_man,Marriage_duration,Type_of_divorce,Num_Children,DOB_partner_man,Level_of_education_partner_man,year_of_marriage,year_of_DOB,year_of_Divorse,month_of_DOB,day_of_DOB,DONE,dayun,man時干,man時支,man日干,man日支,man月干,man月支,man年干,man年支,Year_marriage_ganzhi,man日支同年支,man日支六沖,man日支六合,man流年天干十神,man流年地支十神,man財透干,man財得地,man日干五合,man日柱天地合,man流年雙體財,man日干支關係,man日支半三合,man日支半三會局,man日支暗合,man流年大運天地合,man流年大運伏吟,當令,man大運天干十神,man大運地支十神,man大運財透干,man大運財得地,man年干十神,man年支十神,man月干十神,man月支十神,年月有多少財,年月有多少官,本命日支六合,本命日支三合,本命日支被三合或六合,日支大運六合,日支大運三合,日支被大運三合或六合,流年之前日支被合,marriage_age,marri_age_group,man大運日支六沖,man大運日支六合,man大運日干五合,man大運日柱天地合,man日干大運地支伏吟,強弱得令,強弱得地,強弱得勢,強弱地支半三合,強弱地支三合,強弱地支半三會,強弱地支三會,強弱印的數量,身強身弱
0,0,2006-06-09,2000-06-26,30.0,5.0,Necesario,1.0,1975-12-18,SECUNDARIA,2000,1975,2006,12,18,1,乙酉,壬,子,戊,戌,戊,子,乙,卯,庚辰,False,True,False,食神,比肩,False,False,False,False,False,比和,False,False,False,True,False,0,正官,傷官,False,False,正官,正官,比肩,正財,1,2,yes,no,yes,no,no,no,yes,25,21-30,False,False,False,False,False,False,False,True,False,False,False,False,0,可能強
1,1,2005-02-01,1975-12-18,49.0,NaN,Necesario,NaN,1955-02-22,PREPARATORIA,1975,1955,2005,2,22,1,丙子,甲,子,甲,寅,戊,寅,乙,未,乙卯,False,False,False,劫財,劫財,False,False,False,False,False,比和,False,True,False,False,False,1,食神,正印,False,False,劫財,正財,偏財,比肩,2,0,no,no,no,no,no,no,no,20,0-20,False,False,False,False,False,True,False,True,False,False,False,False,0,強
2,2,2006-02-01,1987-12-03,42.0,18.0,Necesario,2.0,1964-01-20,PROFESIONAL,1987,1964,2006,1,20,1,癸亥,壬,子,戊,辰,乙,丑,癸,卯,丁卯,False,False,False,正印,正官,False,False,False,False,False,比和,False,True,False,False,False,1,正財,偏財,True,True,正財,正官,正官,劫財,1,2,no,no,no,no,no,no,no,23,21-30,False,False,True,False,False,True,False,False,True,False,True,False,0,強
3,3,2006-02-01,1998-11-14,30.0,7.0,Necesario,2.0,1975-10-30,PROFESIONAL,1998,1975,2006,10,30,1,甲申,甲,子,己,酉,丙,戌,乙,卯,戊寅,False,False,False,劫財,正官,False,False,False,False,False,日干生日支,False,False,False,False,False,1,正官,傷官,False,False,七殺,七殺,正印,劫財,0,2,no,no,no,no,no,no,no,23,21-30,False,False,True,False,False,True,False,False,False,False,False,False,0,強
4,4,2006-02-01,1995-01-20,32.0,11.0,Necesario,2.0,1973-03-28,SECUNDARIA,1995,1973,2006,3,28,1,癸丑,壬,子,癸,亥,乙,卯,癸,丑,乙亥,True,False,False,食神,劫財,False,False,False,False,False,比和,False,False,False,False,False,0,比肩,七殺,False,False,比肩,七殺,食神,食神,0,1,no,no,no,no,no,no,no,22,21-30,False,False,False,False,False,False,False,True,False,False,True,False,0,可能強
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4530,4537,2012-10-31,2008-10-25,35.0,3.0,Voluntario,NaN,1977-10-29,PROFESIONAL,2008,1977,2012,10,29,1,丁未,甲,子,己,未,庚,戌,丁,巳,戊子,False,False,False,劫財,偏財,False,True,False,False,False,比和,False,False,False,False,False,1,偏印,比肩,False,False,偏印,偏印,傷官,劫財,0,0,no,no,no,no,no,no,no,31,21-30,False,False,False,False,False,True,False,False,True,False,True,False,0,強
4531,4538,2013-10-31,2012-05-26,30.0,1.0,Voluntario,NaN,1982-11-10,PROFESIONAL,2012,1982,2013,11,10,1,甲寅,庚,子,丁,酉,辛,亥,壬,戌,壬辰,False,False,True,正官,傷官,False,False,True,True,False,日干剋日支,False,False,False,False,False,0,正印,正印,False,False,正官,傷官,偏財,正官,1,2,no,no,no,no,no,no,no,30,21-30,False,False,False,False,False,False,False,False,False,False,False,False,0,弱
4532,4539,2013-10-31,1978-06-02,59.0,35.0,Voluntario,2.0,1954-10-28,PROFESIONAL,1978,1954,2013,10,28,1,丁丑,庚,子,丁,巳,甲,戌,甲,午,戊午,False,False,False,傷官,劫財,False,False,False,False,False,比和,False,True,False,False,False,0,比肩,食神,False,False,正印,劫財,正印,傷官,0,0,no,no,no,no,no,no,no,24,21-30,False,False,False,False,False,False,True,False,True,False,True,False,0,可能強
4533,4540,2012-12-31,1979-11-05,54.0,33.0,Voluntario,2.0,1958-02-07,PREPARATORIA,1979,1958,2012,2,7,1,丙辰,丙,子,乙,卯,甲,寅,戊,戌,己未,False,False,False,偏財,偏財,True,True,False,False,True,比和,True,False,False,False,False,1,傷官,正財,False,True,正財,正財,劫財,劫財,2,0,yes,no,yes,no,no,no,yes,21,0-20,False,False,False,False,False,True,False,True,False,False,True,False,0,強
4534,4541,2013-12-31,2009-08-22,53.0,4.0,Voluntario,NaN,1960-06-22,PROFESIONAL,2009,1960,2013,6,22,1,丁亥,戊,子,辛,巳,壬,午,庚,子,己丑,False,False,False,偏印,偏印,False,False,False,False,False,日支剋日干,True,False,False,False,False,0,七殺,傷官,False,False,劫財,食神,傷官,正官,0,1,no,no,no,no,no,no,no,49,41-50,True,False,False,False,False,False,False,True,False,False,False,False,0,可能強

In [ ]:
# for Marriage_duration > 10
#count the length of the df
len(man_df[man_df['Marriage_duration'] > 10])

1907

In [ ]:
# get all rows where man日支六沖=True

# Filter the rows where 'man日支六沖' is True
filtered_df = man_df[man_df['man日支六沖'] == True]

In [ ]:
#value counts of 身強身弱
filtered_df['身強身弱'].value_counts()

弱      134
可能強    124
強      100
Name: 身強身弱, dtype: int64

In [ ]:
df_filtered= man_df[man_df['身強身弱']=='弱']




#for the columns that are boolean, count the number of True, and plot a bar chart to see the distribution
# create a list of columns that are boolean
boolean_cols = [col for col in df_filtered.columns if df_filtered[col].dtype == 'bool']
boolean_cols

# create a new df with only the boolean columns
df_bool = df_filtered[boolean_cols]
df_bool

# count the number of True and False in each column and show all the result
for col in df_bool.columns:
    print(col,df_bool[col].value_counts()[0])
    # print('-------------------')

# df_bool.sum()

# # plot a bar chart to see the distribution using plotly
import plotly.express as px
px.bar(df_bool.sum(), x=df_bool.sum().index, y=df_bool.sum().values)

man日支同年支 1646
man日支六沖 1662
man日支六合 1645
man財透干 1462
man財得地 1432
man日干五合 1613
man日柱天地合 1763
man流年雙體財 1758
man日支半三合 1468
man日支半三會局 1469
man日支暗合 1699
man流年大運天地合 1763
man流年大運伏吟 1766
man大運財透干 1408
man大運財得地 1437
man大運財透干2 1408
man大運財得地2 1437
man大運日支六沖 1666
man大運日支六合 1648
man大運日干五合 1580
man大運日柱天地合 1757
man財透干2 1462
man財得地2 1432
man日干大運地支伏吟 1796
強弱得令 1796
強弱得地 1796
強弱得勢 1796
強弱地支半三合 1796
強弱地支三合 1796
強弱地支半三會 1796
強弱地支三會 1796

In [ ]:
#value counts of man流年天干十神
df_filtered['man大運天干十神'].value_counts()

正印    143
偏財    135
劫財    133
正官    131
傷官    126
比肩    125
食神    118
正財    117
偏印    115
七殺    98
Name: man大運天干十神, dtype: int64

In [ ]:
#value counts of man流年天干十神
df_filtered['man大運地支十神'].value_counts()

傷官    165
正印    162
食神    161
偏印    147
正財    117
偏財    106
劫財    99
比肩    98
正官    95
七殺    91
Name: man大運地支十神, dtype: int64

In [ ]:
#value counts of man流年天干十神
df_filtered['man流年天干十神'].value_counts()

偏印    222
食神    190
比肩    190
劫財    184
正官    181
傷官    176
偏財    168
正財    166
七殺    165
正印    154
Name: man流年天干十神, dtype: int64

In [ ]:

#value counts of man流年地支十神
df_filtered['man流年地支十神'].value_counts()

七殺    197
正印    195
偏財    193
偏印    187
食神    179
劫財    174
正財    171
正官    170
比肩    168
傷官    162
Name: man流年地支十神, dtype: int64

In [ ]:
df_filtered= man_df[man_df['身強身弱']=='強']
#for the columns that are boolean, count the number of True, and plot a bar chart to see the distribution
# create a list of columns that are boolean
boolean_cols = [col for col in df_filtered.columns if df_filtered[col].dtype == 'bool']
boolean_cols

# create a new df with only the boolean columns
df_bool = df_filtered[boolean_cols]
df_bool

# count the number of True and False in each column and show all the result
for col in df_bool.columns:
    print(col,df_bool[col].value_counts()[0])
    # print('-------------------')

# df_bool.sum()

# # plot a bar chart to see the distribution using plotly
import plotly.express as px
px.bar(df_bool.sum(), x=df_bool.sum().index, y=df_bool.sum().values)

man日支同年支 1127
man日支六沖 1141
man日支六合 1145
man財透干 977
man財得地 1001
man日干五合 1114
man日柱天地合 1219
man流年雙體財 1214
man日支半三合 1043
man日支半三會局 1049
man日支暗合 1176
man流年大運天地合 1218
man流年大運伏吟 1225
man大運財透干 989
man大運財得地 1018
man大運財透干2 989
man大運財得地2 1018
man大運日支六沖 1137
man大運日支六合 1143
man大運日干五合 1111
man大運日柱天地合 1225
man財透干2 977
man財得地2 1001
man日干大運地支伏吟 1241
強弱得令 12
強弱得地 1165
強弱得勢 825
強弱地支半三合 993
強弱地支三合 1219
強弱地支半三會 827
強弱地支三會 1224

In [ ]:
#value counts of man流年天干十神
df_filtered['man大運天干十神'].value_counts()

正印    143
偏財    135
劫財    133
正官    131
傷官    126
比肩    125
食神    118
正財    117
偏印    115
七殺    98
Name: man大運天干十神, dtype: int64

In [ ]:
#value counts of man流年天干十神
df_filtered['man大運地支十神'].value_counts()

傷官    165
正印    162
食神    161
偏印    147
正財    117
偏財    106
劫財    99
比肩    98
正官    95
七殺    91
Name: man大運地支十神, dtype: int64

In [ ]:
#value counts of man流年天干十神
df_filtered['man流年天干十神'].value_counts()

正財    138
正印    132
七殺    131
比肩    129
偏財    126
食神    126
劫財    120
傷官    114
正官    113
偏印    112
Name: man流年天干十神, dtype: int64

In [ ]:

#value counts of man流年地支十神
df_filtered['man流年地支十神'].value_counts()

比肩    140
傷官    136
劫財    133
偏財    132
七殺    127
正官    122
正印    117
偏印    116
食神    110
正財    108
Name: man流年地支十神, dtype: int64

In [ ]:
len(filtered_df)

358

In [ ]:
def printBazi(df):
    for index, row in df.iterrows():
        print(f"{row['man日干']}{row['man月干']}{row['man年干']}|{row['dayun'][0]}{row['Year_marriage_ganzhi'][0]}")
        print(f"{row['man日支']}{row['man月支']}{row['man年支']}|{row['dayun'][1]}{row['Year_marriage_ganzhi'][1]}")
        collist = [col for col in row.index if row[col] and df[col].dtype == 'bool']
        print(collist)
        print()

In [ ]:
printBazi(filtered_df)

戊戊乙|乙庚
戌子卯|酉辰
['man日支六沖', 'man流年大運天地合']

庚己己|丙庚
戌巳酉|寅辰
['man日支六沖', 'man大運財得地', 'man大運財得地2']

己丙甲|戊癸
卯寅寅|辰酉
['man日支六沖', 'man財透干', 'man流年大運天地合', 'man財透干2']

甲庚戊|癸丙
戌申子|亥辰
['man日支六沖', 'man財得地', 'man財得地2']

丙丁辛|甲戊
午酉酉|午子
['man日支六沖']

辛丙癸|壬乙
巳辰卯|子亥
['man日支六沖', 'man財透干', 'man財透干2']

己壬己|己丁
丑申卯|巳未
['man日支六沖']

乙壬己|己丁
亥申丑|巳巳
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日支六沖', 'man流年大運地支伏吟']

壬乙己|癸甲
寅亥未|酉申
['man日支六沖']

戊甲戊|丁丙
午子申|卯子
['man日支六沖', 'man財得地', 'man財得地2']

辛己乙|丁己
未丑丑|亥丑
['man日支六沖']

辛己戊|庚丁
未未午|申丑
['man日支六沖']

癸壬己|戊己
亥申亥|辰巳
['man日支六沖', 'man財得地', 'man大運日干五合', 'man財得地2']

戊丙己|甲甲
辰寅酉|子戌
['man日支六沖', 'man大運財得地', 'man大運財得地2']

丙壬丙|丙甲
辰辰申|申戌
['man日支六沖', 'man大運財得地', 'man大運財得地2']

庚壬丁|己庚
子寅未|亥午
['man日支六沖']

丙壬甲|乙戊
申申辰|亥寅
['man日支六沖']

丙己己|丁丙
午巳酉|卯子
['man日支六沖']

癸癸壬|乙癸
卯丑子|卯酉
['man日支六沖']

甲乙甲|戊丙
申亥午|寅寅
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日支六沖', 'man流年大運地支伏吟']

癸丙庚|辛乙
巳戌寅|卯亥
['man日支六沖']

丁乙辛|壬己
酉未亥|辰卯
['man日支六沖', 'man大運日支六合', 'man大運日干五合', 'man大運日柱天地合']

辛庚庚|癸辛
卯辰子|未酉
['man日支六沖']

戊甲庚|丙庚
子申戌|戌午
['man日支六沖']

乙戊甲|庚己
酉辰寅|午卯
['man日支六沖', 'man財透干', 'man大運日干五合', 'man財透干2']

己丁丁|乙癸
丑未巳|巳未
['man日支六沖', 'man財透干', 'man財透干2']

戊壬甲|甲戊
戌申辰|戌辰
['man日支六沖']

癸丁癸|甲辛
亥巳丑|寅巳
['man日支六沖', 'man財得地', 'man大運日支六合', 'man財得地2']

癸丙壬|辛丁
巳午寅|亥亥
['man日支六沖', 'man財透干', 'man大運日支六沖', 'man財透干2', 'man流年大運地支伏吟']

癸壬庚|乙丁
未午戌|酉丑
['man日支六沖', 'man財透干', 'man財透干2']

丁乙庚|戊丁
未酉戌|子丑
['man日支六沖']

庚癸甲|戊壬
寅酉申|寅申
['man日支六沖', 'man大運財得地', 'man大運財得地2']

己己乙|丙乙
卯卯卯|子酉
['man日支六沖', 'man大運財得地', 'man大運財得地2']

甲壬辛|庚庚
戌辰酉|寅辰
['man日支六沖', 'man財得地', 'man財得地2']

辛戊辛|甲丁
巳戌亥|午亥
['man日支六沖', 'man大運財透干', 'man大運財透干2']

庚丁丙|壬甲
寅酉申|寅申
['man日支六沖', 'man財透干', 'man大運財得地', 'man大運財得地2', 'man財透干2']

己丁甲|庚辛
卯卯午|午酉
['man日支六沖']

壬丙丙|己甲
寅申辰|亥申
['man日支六沖', 'man大運日支六合']

戊癸庚|丙庚
戌未戌|戌辰
['man日支六沖']

庚丙庚|己丙
辰戌申|丑戌
['man日支六沖']

戊丁辛|癸戊
午酉亥|巳子
['man日支六沖', 'man財得地', 'man大運財透干', 'man大運財透干2', 'man大運日干五合', 'man財得地2']

壬戊甲|辛戊
子辰午|未午
['man日支六沖', 'man財得地', 'man財得地2']

己庚癸|丁丁
巳申亥|巳亥
['man日支六沖', 'man財得地', 'man財得地2']

乙戊戊|辛己
亥午戌|酉巳
['man日支六沖', 'man財透干', 'man財透干2']

辛辛丙|甲癸
酉丑子|辰卯
['man日支六沖', 'man財得地', 'man大運財透干', 'man大運財透干2', 'man大運日支六合', 'man財得地2']

乙戊甲|庚己
酉辰寅|午卯
['man日支六沖', 'man財透干', 'man大運日干五合', 'man財透干2']

丁癸庚|丙癸
巳未子|戌亥
['man日支六沖']

戊乙丙|戊甲
寅未辰|戌申
['man日支六沖']

丁丁己|乙辛
巳丑丑|亥亥
['man日支六沖', 'man財透干', 'man大運日支六沖', 'man財透干2', 'man流年大運地支伏吟']

庚辛己|己壬
子未未|巳午
['man日支六沖']

辛癸壬|丙辛
亥丑子|辰巳
['man日支六沖', 'man大運日干五合']

甲庚丁|丙戊
申戌酉|午寅
['man日支六沖', 'man財透干', 'man財透干2']

甲庚辛|丙戊
申寅丑|戌寅
['man日支六沖', 'man財透干', 'man大運財得地', 'man大運財得地2', 'man財透干2']

丁壬己|己乙
巳申酉|巳亥
['man日支六沖']

丙壬丙|乙丙
午辰午|未子
['man日支六沖', 'man大運日支六合']

丁丁辛|甲丁
丑酉巳|午未
['man日支六沖']

庚乙癸|癸丙
午丑丑|亥子
['man日支六沖']

乙己癸|丁己
亥未卯|巳巳
['man日支六沖', 'man財透干', 'man大運日支六沖', 'man財透干2', 'man流年大運地支伏吟']

乙乙己|辛乙
巳亥亥|未亥
['man日支六沖', 'man大運財得地', 'man大運財得地2']

丙庚乙|丁丙
午辰巳|丑子
['man日支六沖']

癸己戊|壬乙
巳未申|戌亥
['man日支六沖']

戊己乙|丁丙
午卯卯|丑子
['man日支六沖', 'man財得地', 'man財得地2']

庚戊丙|庚壬
子戌辰|子午
['man日支六沖']

庚壬丁|庚壬
戌寅卯|子辰
['man日支六沖']

庚己癸|丁戊
寅未未|巳申
['man日支六沖']

乙丙甲|戊丁
未子寅|寅丑
['man日支六沖', 'man財得地', 'man大運財透干', 'man大運財透干2', 'man財得地2']

丙癸壬|乙戊
申卯子|巳寅
['man日支六沖', 'man大運日支六合']

戊己壬|辛壬
辰酉寅|亥戌
['man日支六沖', 'man財透干', 'man大運財得地', 'man大運財得地2', 'man財透干2']

庚庚己|戊壬
辰午亥|辰戌
['man日支六沖']

戊庚庚|癸丙
辰辰申|未戌
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日干五合']

丙丁辛|乙壬
寅酉亥|未申
['man日支六沖', 'man財得地', 'man財得地2']

甲癸戊|乙庚
辰亥子|丑戌
['man日支六沖', 'man財得地', 'man大運財得地', 'man大運財得地2', 'man財得地2']

乙己乙|丙己
酉丑巳|戌卯
['man日支六沖', 'man財透干', 'man大運財得地', 'man大運財得地2', 'man財透干2']

癸丁乙|甲乙
未亥未|申丑
['man日支六沖']

癸甲甲|丁丁
亥戌午|丑巳
['man日支六沖', 'man財透干', 'man財得地', 'man流年雙體財', 'man大運財透干', 'man大運財透干2', 'man財透干2', 'man財得地2']

庚丙己|癸甲
午寅亥|亥子
['man日支六沖', 'man財透干', 'man財透干2']

壬丁丁|甲庚
寅未亥|辰申
['man日支六沖']

丁辛癸|戊己
未酉亥|午丑
['man日支六沖', 'man大運日支六合']

庚丙甲|己庚
子寅辰|巳午
['man日支六沖']

壬癸丙|乙丙
午巳辰|未子
['man日支六沖', 'man財透干', 'man大運日支六合', 'man財透干2']

丁乙癸|癸丁
巳丑亥|亥亥
['man日支六沖', 'man大運日支六沖', 'man流年大運地支伏吟']

辛庚壬|癸辛
丑戌寅|丑未
['man日支六沖']

己丁戊|庚己
亥巳戌|申巳
['man日支六沖']

辛戊癸|甲乙
巳午卯|寅亥
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財得地', 'man大運財透干2', 'man大運財得地2', 'man財透干2']

丙甲丙|丙戊
申午辰|申寅
['man日支六沖', 'man大運財得地', 'man大運財得地2']

己壬甲|丙己
酉申辰|子卯
['man日支六沖', 'man大運財得地', 'man大運財得地2']

辛辛己|己丁
酉未亥|巳卯
['man日支六沖', 'man財得地', 'man財得地2']

癸己癸|丙辛
亥未丑|辰巳
['man日支六沖', 'man財得地', 'man大運財透干', 'man大運財透干2', 'man財得地2']

辛戊庚|辛乙
巳子戌|卯亥
['man日支六沖', 'man財透干', 'man大運財得地', 'man大運財得地2', 'man財透干2']

壬丁乙|甲庚
戌亥卯|申辰
['man日支六沖']

丁乙戊|己辛
酉卯午|未卯
['man日支六沖', 'man財透干', 'man財透干2']

戊甲庚|丙壬
寅申戌|戌申
['man日支六沖', 'man財透干', 'man財透干2']

戊乙己|癸庚
辰亥丑|酉戌
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日支六合', 'man大運日干五合', 'man大運日柱天地合']

庚戊己|乙甲
午辰亥|丑子
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man大運日干五合', 'man財透干2']

壬辛己|己甲
寅未未|巳申
['man日支六沖', 'man流年大運天地合', 'man大運財得地', 'man大運財得地2']

壬辛庚|甲甲
申巳寅|申寅
['man日支六沖']

戊辛辛|己壬
辰丑丑|亥戌
['man日支六沖', 'man財透干', 'man大運財得地', 'man大運財得地2', 'man財透干2']

甲壬辛|己甲
午辰卯|丑子
['man日支六沖', 'man流年大運天地合', 'man大運財透干', 'man大運財得地', 'man大運財透干2', 'man大運財得地2', 'man大運日干五合']

癸丙庚|戊辛
亥戌申|子巳
['man日支六沖', 'man財得地', 'man大運日干五合', 'man財得地2']

己甲戊|己己
未寅戌|未丑
['man日支六沖']

癸乙癸|壬癸
丑丑丑|戌未
['man日支六沖']

甲丙己|甲戊
申子酉|戌寅
['man日支六沖', 'man財透干', 'man大運財得地', 'man大運財得地2', 'man財透干2']

丁己庚|甲丁
巳卯子|申亥
['man日支六沖', 'man大運財得地', 'man大運財得地2', 'man大運日支六合']

戊甲辛|庚庚
戌午丑|寅辰
['man日支六沖']

甲丁己|乙丙
辰丑未|亥戌
['man日支六沖', 'man財得地', 'man財得地2']

己戊癸|乙癸
丑午丑|卯未
['man日支六沖', 'man財透干', 'man財透干2']

辛丙己|甲辛
亥寅未|子巳
['man日支六沖', 'man大運財透干', 'man大運財透干2']

乙癸戊|乙辛
亥亥午|丑巳
['man日支六沖', 'man大運財得地', 'man大運財得地2']

丙甲甲|丙庚
戌戌寅|子辰
['man日支六沖', 'man財透干', 'man財透干2']

壬丙甲|己甲
寅子寅|卯申
['man日支六沖']

庚丁己|甲丙
辰卯未|子戌
['man日支六沖', 'man大運財透干', 'man大運財透干2']

癸癸戊|丙乙
巳亥申|寅亥
['man日支六沖', 'man大運財透干', 'man大運財透干2']

丙庚丙|癸丙
午寅午|巳子
['man日支六沖']

壬壬壬|丙丙
辰子子|辰戌
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man財透干2']

壬乙丙|戊庚
申未寅|戌寅
['man日支六沖']

己丙戊|戊癸
亥辰辰|午巳
['man日支六沖', 'man財透干', 'man財透干2']

丁癸甲|乙乙
卯酉子|亥酉
['man日支六沖', 'man財得地', 'man財得地2']

己乙丙|戊辛
丑未午|戌未
['man日支六沖']

甲戊甲|庚丙
午辰寅|午子
['man日支六沖']

戊戊庚|庚甲
辰子戌|寅戌
['man日支六沖']

壬乙辛|癸甲
寅未酉|巳申
['man日支六沖', 'man大運財得地', 'man大運財得地2']

癸丁壬|辛丁
酉未辰|亥卯
['man日支六沖', 'man財透干', 'man財透干2']

辛丁乙|乙己
丑亥未|酉未
['man日支六沖', 'man大運財透干', 'man大運財透干2']

丁丁甲|辛己
亥卯午|未巳
['man日支六沖', 'man大運財透干', 'man大運財透干2']

壬庚丁|戊甲
午戌酉|申子
['man日支六沖']

丙庚癸|戊戊
申申丑|午寅
['man日支六沖']

庚己乙|丁庚
寅丑未|亥申
['man日支六沖', 'man大運日支六合']

癸乙壬|丁癸
卯巳子|未酉
['man日支六沖', 'man大運財透干', 'man大運財透干2']

丁戊乙|乙乙
未子未|酉丑
['man日支六沖', 'man大運財得地', 'man大運財得地2']

戊甲癸|壬壬
子子亥|戌午
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man財透干2']

庚己辛|丙甲
午亥卯|申子
['man日支六沖', 'man財透干', 'man財透干2']

戊壬丁|庚戊
申寅巳|子寅
['man日支六沖', 'man大運財得地', 'man大運財得地2']

戊庚庚|壬壬
寅辰戌|午申
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man財透干2']

庚壬丁|庚壬
辰子酉|戌戌
['man日支六沖', 'man大運日支六沖', 'man流年大運地支伏吟']

壬辛辛|己甲
申丑卯|亥寅
['man日支六沖', 'man流年大運天地合']

己甲戊|丁乙
巳寅申|巳亥
['man日支六沖', 'man財得地', 'man財得地2']

辛甲丁|辛癸
丑辰巳|丑未
['man日支六沖']

丙戊甲|辛戊
申辰辰|未寅
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日干五合']

丁丁丁|乙辛
亥未巳|巳巳
['man日支六沖', 'man財透干', 'man大運日支六沖', 'man財透干2', 'man流年大運地支伏吟']

庚丁戊|己丙
子巳子|未午
['man日支六沖']

丁戊辛|甲丁
未戌卯|午丑
['man日支六沖', 'man大運日支六合']

戊丙癸|甲甲
寅辰亥|寅申
['man日支六沖']

庚庚壬|癸壬
子戌子|丑午
['man日支六沖', 'man大運日支六合']

己乙壬|戊丁
未巳子|申丑
['man日支六沖']

丙己甲|辛戊
子巳午|未午
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日干五合']

己己丙|壬癸
卯亥午|寅酉
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man財透干2']

庚己丙|壬甲
寅亥辰|寅申
['man日支六沖', 'man財透干', 'man大運財得地', 'man大運財得地2', 'man財透干2']

丁辛壬|乙己
亥亥辰|卯巳
['man日支六沖']

壬丁癸|壬戊
申巳巳|子寅
['man日支六沖']

壬丁戊|己壬
辰巳戌|未戌
['man日支六沖']

庚辛己|戊壬
寅未酉|辰申
['man日支六沖']

己丁辛|乙辛
亥酉酉|未巳
['man日支六沖']

癸丙癸|甲丁
巳辰亥|寅亥
['man日支六沖', 'man財透干', 'man財透干2']

辛辛癸|戊辛
亥酉丑|午巳
['man日支六沖']

庚甲甲|己戊
申戌申|卯寅
['man日支六沖', 'man財得地', 'man大運財得地', 'man大運財得地2', 'man財得地2']

辛丁癸|壬乙
未巳未|子丑
['man日支六沖', 'man財透干', 'man財透干2']

己甲庚|丁丁
巳申申|亥亥
['man日支六沖', 'man財得地', 'man流年大運伏吟', 'man大運財得地', 'man大運財得地2', 'man大運日支六沖', 'man財得地2', 'man流年大運地支伏吟']

庚乙丁|癸丙
午巳巳|卯子
['man日支六沖', 'man大運財得地', 'man大運財得地2']

丁癸丙|丙己
亥巳午|申巳
['man日支六沖', 'man大運財得地', 'man大運財得地2']

戊甲戊|丁丙
午子申|卯子
['man日支六沖', 'man財得地', 'man財得地2']

辛戊庚|辛丁
未子戌|卯丑
['man日支六沖', 'man大運財得地', 'man大運財得地2']

癸甲癸|庚癸
卯子巳|申酉
['man日支六沖']

己丁辛|乙丁
未酉亥|未丑
['man日支六沖']

己壬己|己丁
未申酉|巳丑
['man日支六沖']

乙庚辛|丁乙
酉子卯|酉卯
['man日支六沖']

癸乙丙|丁辛
亥未辰|酉巳
['man日支六沖', 'man財得地', 'man大運財透干', 'man大運財透干2', 'man財得地2']

戊甲戊|丙戊
申寅午|辰寅
['man日支六沖']

乙丙戊|戊辛
丑辰申|午未
['man日支六沖', 'man財得地', 'man大運財透干', 'man大運財透干2', 'man財得地2']

壬癸丙|丙甲
辰巳午|申戌
['man日支六沖', 'man大運財透干', 'man大運財透干2']

丁乙辛|辛乙
卯未丑|卯酉
['man日支六沖', 'man財得地', 'man大運財透干', 'man大運財透干2', 'man財得地2']

乙丙丁|庚丁
未午丑|子丑
['man日支六沖', 'man財得地', 'man大運日干五合', 'man財得地2']

辛癸壬|丁辛
卯丑午|巳酉
['man日支六沖']

戊甲丙|丁壬
戌午辰|酉辰
['man日支六沖', 'man財透干', 'man流年大運天地合', 'man財透干2']

乙乙壬|戊辛
丑巳寅|申未
['man日支六沖', 'man財得地', 'man大運財透干', 'man大運財透干2', 'man財得地2']

癸辛壬|甲丁
酉亥寅|寅卯
['man日支六沖', 'man財透干', 'man財透干2']

丙丁戊|己庚
戌巳午|未辰
['man日支六沖', 'man財透干', 'man財透干2']

乙戊丁|乙乙
酉申亥|巳卯
['man日支六沖']

己丁壬|庚乙
巳未子|戌亥
['man日支六沖', 'man財得地', 'man財得地2']

丙壬庚|乙壬
寅午子|酉申
['man日支六沖', 'man財得地', 'man大運財得地', 'man大運財得地2', 'man財得地2']

丁辛乙|己乙
巳巳卯|卯亥
['man日支六沖']

癸丙甲|己癸
卯寅辰|巳酉
['man日支六沖', 'man大運財得地', 'man大運財得地2']

甲戊丁|乙戊
午申卯|巳子
['man日支六沖', 'man財透干', 'man財透干2']

戊甲丁|壬戊
申辰巳|寅寅
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日支六沖', 'man流年大運地支伏吟']

庚壬乙|庚丙
申午巳|辰寅
['man日支六沖', 'man財得地', 'man財得地2']

丁乙乙|壬癸
卯酉巳|午酉
['man日支六沖', 'man財得地', 'man大運日干五合', 'man財得地2']

乙丁癸|甲乙
卯巳丑|寅酉
['man日支六沖']

壬丁壬|庚庚
戌未子|戌辰
['man日支六沖']

辛庚癸|丁己
未申亥|巳丑
['man日支六沖']

癸己丙|壬乙
巳亥午|寅亥
['man日支六沖']

己己甲|癸辛
丑巳午|酉未
['man日支六沖', 'man大運財透干', 'man大運財透干2']

乙己庚|壬癸
卯丑戌|辰酉
['man日支六沖', 'man大運財得地', 'man大運財得地2']

壬癸庚|乙戊
午未申|酉子
['man日支六沖']

辛丁甲|己己
酉丑寅|卯卯
['man日支六沖', 'man財得地', 'man流年大運伏吟', 'man大運財得地', 'man大運財得地2', 'man大運日支六沖', 'man財得地2', 'man流年大運地支伏吟']

辛甲癸|壬乙
卯寅亥|子酉
['man日支六沖', 'man財透干', 'man財透干2']

癸丙己|甲辛
亥寅未|子巳
['man日支六沖', 'man財得地', 'man財得地2']

乙壬辛|己乙
卯辰酉|丑酉
['man日支六沖', 'man大運財透干', 'man大運財得地', 'man大運財透干2', 'man大運財得地2']

丙丁己|癸戊
申丑亥|酉寅
['man日支六沖', 'man大運財得地', 'man大運財得地2']

壬庚丁|丁庚
戌戌未|未辰
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日干五合']

壬辛壬|甲庚
戌亥子|寅辰
['man日支六沖']

癸乙壬|戊乙
卯巳子|申酉
['man日支六沖', 'man大運日干五合']

甲甲甲|丁丙
辰戌寅|丑戌
['man日支六沖', 'man財得地', 'man大運財得地', 'man大運財得地2', 'man財得地2']

癸乙辛|癸乙
卯未酉|巳酉
['man日支六沖', 'man大運財得地', 'man大運財得地2']

乙甲癸|庚辛
酉子丑|申卯
['man日支六沖', 'man大運日干五合']

辛癸癸|庚癸
丑亥亥|申未
['man日支六沖']

己辛丙|癸癸
卯丑午|卯酉
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man財透干2']

丙癸戊|乙戊
申亥午|丑寅
['man日支六沖']

戊己庚|庚戊
戌丑戌|寅辰
['man日支六沖']

己乙戊|丙癸
酉丑子|寅卯
['man日支六沖', 'man財透干', 'man財透干2']

乙辛乙|己己
亥巳巳|卯巳
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man財透干2']

庚癸戊|丙甲
寅亥午|寅申
['man日支六沖', 'man財透干', 'man大運財得地', 'man大運財得地2', 'man財透干2']

壬丁甲|庚庚
戌卯寅|午辰
['man日支六沖', 'man大運財得地', 'man大運財得地2']

丙己癸|丁庚
子未卯|巳午
['man日支六沖', 'man財透干', 'man財透干2']

丙辛丙|甲庚
戌卯辰|午辰
['man日支六沖', 'man財透干', 'man財透干2']

丙癸庚|丙甲
辰未戌|戌戌
['man日支六沖', 'man大運日支六沖', 'man流年大運地支伏吟']

丁癸己|庚己
亥酉酉|午巳
['man日支六沖', 'man大運財透干', 'man大運財透干2']

庚庚己|丁丙
午午酉|卯子
['man日支六沖', 'man大運財得地', 'man大運財得地2']

丁乙辛|癸辛
卯未丑|巳酉
['man日支六沖', 'man財透干', 'man財得地', 'man流年雙體財', 'man財透干2', 'man財得地2']

壬癸癸|辛庚
子亥丑|酉午
['man日支六沖', 'man財得地', 'man財得地2']

庚甲辛|庚甲
辰午丑|寅戌
['man日支六沖', 'man財透干', 'man大運財得地', 'man大運財得地2', 'man財透干2']

庚癸丁|辛壬
申卯丑|丑寅
['man日支六沖', 'man財得地', 'man財得地2']

戊己甲|癸甲
寅巳寅|酉申
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日干五合']

丙丁壬|庚戊
子未辰|戌午
['man日支六沖', 'man大運財透干', 'man大運財透干2']

癸辛丙|癸己
酉丑辰|卯卯
['man日支六沖', 'man大運日支六沖', 'man流年大運地支伏吟']

己乙乙|癸辛
丑酉巳|未未
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日支六沖', 'man流年大運地支伏吟']

己乙甲|丁癸
卯亥寅|丑酉
['man日支六沖', 'man財透干', 'man財透干2']

庚己丁|丙戊
戌酉酉|午辰
['man日支六沖']

丙甲丁|庚庚
申辰巳|子寅
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man財透干2']

甲丁己|癸壬
戌卯未|亥辰
['man日支六沖', 'man財得地', 'man財得地2']

丙庚辛|丁庚
戌寅亥|亥辰
['man日支六沖', 'man財透干', 'man財透干2']

丁丁己|甲辛
酉卯未|子卯
['man日支六沖', 'man財透干', 'man財透干2']

丙丁壬|庚戊
午未戌|戌子
['man日支六沖', 'man大運財透干', 'man大運財透干2']

癸戊丙|庚己
丑戌申|子未
['man日支六沖', 'man大運日支六合']

辛癸丙|丁丁
亥巳戌|酉巳
['man日支六沖']

丙庚壬|壬丙
申戌寅|子寅
['man日支六沖']

戊辛丁|戊壬
寅亥未|申申
['man日支六沖', 'man財透干', 'man大運日支六沖', 'man財透干2', 'man流年大運地支伏吟']

丁癸戊|乙辛
亥亥午|丑巳
['man日支六沖', 'man財透干', 'man財透干2']

癸癸壬|乙癸
卯丑子|卯酉
['man日支六沖']

癸丁丁|癸辛
酉未巳|卯卯
['man日支六沖', 'man大運日支六沖', 'man流年大運地支伏吟']

壬甲癸|辛丙
午子丑|酉子
['man日支六沖', 'man財透干', 'man財透干2']

丙戊丁|乙丙
辰申巳|巳戌
['man日支六沖']

甲壬戊|甲戊
戌戌申|子辰
['man日支六沖', 'man財透干', 'man財得地', 'man流年雙體財', 'man財透干2', 'man財得地2']

甲辛辛|己壬
寅卯亥|丑申
['man日支六沖', 'man大運財透干', 'man大運財得地', 'man大運財透干2', 'man大運財得地2', 'man大運日干五合']

己丁己|癸癸
丑丑酉|酉未
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man財透干2']

丁丙壬|庚己
酉午寅|戌卯
['man日支六沖', 'man大運財透干', 'man大運財透干2']

壬丁戊|己庚
辰巳子|未戌
['man日支六沖']

戊己己|丙庚
戌巳酉|寅辰
['man日支六沖']

丙丙甲|戊壬
子寅子|辰午
['man日支六沖']

庚乙戊|己庚
戌丑戌|巳辰
['man日支六沖']

丁丁乙|甲癸
丑亥卯|申未
['man日支六沖', 'man大運財得地', 'man大運財得地2']

庚乙癸|辛甲
辰丑巳|酉戌
['man日支六沖', 'man財透干', 'man大運日支六合', 'man財透干2']

癸丙丁|甲己
亥午未|辰巳
['man日支六沖', 'man財得地', 'man財得地2']

癸己戊|壬癸
卯未申|戌酉
['man日支六沖', 'man大運日支六合']

己丙癸|甲癸
丑辰亥|寅未
['man日支六沖', 'man財透干', 'man大運日干五合', 'man財透干2']

丁丙甲|己辛
卯子午|卯酉
['man日支六沖', 'man財透干', 'man財得地', 'man流年雙體財', 'man財透干2', 'man財得地2']

戊乙丁|癸庚
子巳未|卯午
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日干五合']

癸丁壬|己癸
丑未戌|酉未
['man日支六沖']

甲壬壬|甲壬
子寅戌|辰午
['man日支六沖', 'man大運財得地', 'man大運財得地2']

壬庚辛|丁丙
申寅丑|亥寅
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man大運日干五合', 'man財透干2']

乙丙乙|癸癸
卯戌巳|未酉
['man日支六沖', 'man大運財得地', 'man大運財得地2']

己壬壬|甲辛
卯寅寅|辰酉
['man日支六沖', 'man大運日干五合']

甲丙壬|己壬
辰午辰|酉戌
['man日支六沖', 'man財得地', 'man大運財透干', 'man大運財透干2', 'man大運日支六合', 'man大運日干五合', 'man大運日柱天地合', 'man財得地2']

丙戊戊|庚丙
辰午辰|申戌
['man日支六沖', 'man大運財透干', 'man大運財得地', 'man大運財透干2', 'man大運財得地2']

癸丁壬|己丁
巳未戌|酉亥
['man日支六沖', 'man財透干', 'man財透干2']

癸癸甲|乙癸
丑酉子|亥未
['man日支六沖']

丁癸癸|辛癸
卯亥丑|酉酉
['man日支六沖', 'man財得地', 'man大運財透干', 'man大運財得地', 'man大運財透干2', 'man大運財得地2', 'man大運日支六沖', 'man財得地2', 'man流年大運地支伏吟']

己甲壬|戊辛
丑辰辰|申未
['man日支六沖']

己庚丙|壬丁
酉子午|寅卯
['man日支六沖', 'man大運財透干', 'man大運財透干2']

癸丙乙|癸辛
丑戌巳|未未
['man日支六沖', 'man大運日支六沖', 'man流年大運地支伏吟']

壬己癸|丙庚
申未丑|辰寅
['man日支六沖', 'man大運財透干', 'man大運財透干2']

辛甲辛|庚丁
未午丑|寅丑
['man日支六沖', 'man大運財得地', 'man大運財得地2']

甲丁己|癸戊
子丑卯|酉午
['man日支六沖', 'man財透干', 'man財透干2']

壬甲癸|庚戊
午寅丑|戌子
['man日支六沖']

乙己丁|丙辛
亥酉巳|午巳
['man日支六沖']

丙丁庚|己庚
戌亥申|丑辰
['man日支六沖', 'man財透干', 'man財透干2']

庚壬壬|甲丙
午寅子|辰子
['man日支六沖', 'man大運財透干', 'man大運財透干2']

癸壬丁|己己
酉子未|酉卯
['man日支六沖']

甲丙庚|戊壬
子戌申|子午
['man日支六沖', 'man大運財透干', 'man大運財透干2']

乙戊丙|辛乙
卯戌辰|丑酉
['man日支六沖', 'man大運財得地', 'man大運財得地2']

癸甲庚|丁丁
未申戌|亥丑
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man財透干2']

壬庚戊|甲庚
申申午|子寅
['man日支六沖']

丁丁己|甲己
未丑未|戌丑
['man日支六沖']

壬壬丁|己戊
申子未|酉寅
['man日支六沖']

戊甲戊|丙庚
戌寅午|辰辰
['man日支六沖', 'man大運日支六沖', 'man流年大運地支伏吟']

壬庚庚|癸戊
申辰戌|未寅
['man日支六沖']

癸丁辛|癸丁
亥酉巳|巳巳
['man日支六沖', 'man財透干', 'man財得地', 'man流年雙體財', 'man大運財得地', 'man大運財得地2', 'man大運日支六沖', 'man財透干2', 'man財得地2', 'man流年大運地支伏吟']

丁甲辛|壬癸
丑午酉|辰未
['man日支六沖', 'man大運日干五合']

戊癸丁|辛戊
戌丑未|亥辰
['man日支六沖', 'man大運財得地', 'man大運財得地2']

乙癸丁|辛癸
巳卯酉|丑亥
['man日支六沖', 'man大運財得地', 'man大運財得地2']

丁丙壬|庚乙
未午辰|戌丑
['man日支六沖', 'man大運財透干', 'man大運財透干2']

癸辛丁|戊丁
未亥未|申丑
['man日支六沖', 'man財透干', 'man大運日干五合', 'man財透干2']

癸丙乙|甲癸
卯戌卯|申酉
['man日支六沖']

丙甲丁|壬壬
寅辰未|寅申
['man日支六沖', 'man財得地', 'man財得地2']

庚辛丙|甲甲
寅丑辰|辰申
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man財透干2']

己丙己|甲丁
巳寅未|子亥
['man日支六沖', 'man財得地', 'man大運財得地', 'man大運財得地2', 'man大運日干五合', 'man財得地2']

甲壬甲|乙丙
辰申子|亥戌
['man日支六沖', 'man財得地', 'man財得地2']

丁丁丙|癸乙
巳酉子|卯亥
['man日支六沖']

丁甲癸|辛辛
亥寅丑|亥巳
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man財透干2']

乙丁辛|乙乙
卯酉酉|未酉
['man日支六沖', 'man大運財得地', 'man大運財得地2']

乙己庚|壬丁
未卯戌|午丑
['man日支六沖', 'man財得地', 'man大運日支六合', 'man財得地2']

乙乙己|壬丁
未亥酉|申丑
['man日支六沖', 'man財得地', 'man財得地2']

己壬壬|甲丁
巳寅戌|辰亥
['man日支六沖', 'man財得地', 'man大運日干五合', 'man財得地2']

癸癸辛|庚辛
丑巳丑|寅未
['man日支六沖']

壬甲辛|辛壬
戌午酉|卯辰
['man日支六沖', 'man大運日支六合']

戊壬丁|己丙
午寅未|亥子
['man日支六沖', 'man財得地', 'man大運財得地', 'man大運財得地2', 'man財得地2']

癸庚丙|甲辛
亥寅午|午巳
['man日支六沖', 'man財得地', 'man大運財得地', 'man大運財得地2', 'man財得地2']

癸壬壬|乙丁
未子寅|卯丑
['man日支六沖', 'man財透干', 'man財透干2']

己戊癸|乙辛
亥午丑|卯巳
['man日支六沖']

癸庚丁|戊辛
亥戌巳|申巳
['man日支六沖', 'man財得地', 'man大運日干五合', 'man財得地2']

戊丁丁|甲甲
寅未巳|辰申
['man日支六沖']

甲辛乙|丙丙
午巳酉|子子
['man日支六沖', 'man流年大運伏吟', 'man大運日支六沖', 'man流年大運地支伏吟']

戊癸丙|戊庚
戌巳申|戌辰
['man日支六沖']

甲癸丁|庚庚
戌丑巳|戌辰
['man日支六沖', 'man財得地', 'man大運財得地', 'man大運財得地2', 'man財得地2']

乙己乙|丙丁
酉卯未|子卯
['man日支六沖']

癸壬癸|己乙
巳戌卯|未亥
['man日支六沖']

癸己乙|丁丁
酉卯巳|丑卯
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man財透干2']

癸壬丁|庚乙
未子酉|戌丑
['man日支六沖']

戊甲戊|丙丙
午子午|寅子
['man日支六沖', 'man財得地', 'man財得地2']

庚辛乙|戊戊
申巳卯|寅寅
['man日支六沖', 'man財得地', 'man流年大運伏吟', 'man大運財得地', 'man大運財得地2', 'man大運日支六沖', 'man財得地2', 'man流年大運地支伏吟']

壬戊壬|庚丙
午申子|戌子
['man日支六沖', 'man財透干', 'man財透干2']

戊丙癸|癸甲
寅辰丑|丑申
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日干五合']

戊辛乙|己丙
戌巳未|卯辰
['man日支六沖', 'man大運日支六合']

戊甲己|辛庚
子戌亥|未午
['man日支六沖']

癸辛丁|己辛
卯亥酉|酉酉
['man日支六沖', 'man大運日支六沖', 'man流年大運地支伏吟']

己己辛|丙丁
酉亥丑|申卯
['man日支六沖']

庚辛壬|甲戊
申亥子|寅寅
['man日支六沖', 'man財得地', 'man大運財透干', 'man大運財得地', 'man大運財透干2', 'man大運財得地2', 'man大運日支六沖', 'man財得地2', 'man流年大運地支伏吟']

乙甲甲|丙乙
巳戌寅|子亥
['man日支六沖']

癸庚丙|甲辛
亥子午|辰巳
['man日支六沖', 'man財得地', 'man財得地2']

辛戊辛|丙癸
卯戌亥|申酉
['man日支六沖', 'man大運日干五合']

戊己壬|壬甲
辰酉子|子戌
['man日支六沖', 'man大運財透干', 'man大運財得地', 'man大運財透干2', 'man大運財得地2']

壬丁壬|庚庚
子未寅|戌午
['man日支六沖', 'man財得地', 'man財得地2']

丙丁己|乙戊
申丑未|亥寅
['man日支六沖']

戊己庚|辛壬
午卯寅|巳子
['man日支六沖', 'man財透干', 'man財得地', 'man流年雙體財', 'man財透干2', 'man財得地2']

辛己丁|丙癸
卯酉未|午酉
['man日支六沖', 'man大運日干五合']

乙乙戊|己乙
巳卯戌|未亥
['man日支六沖', 'man大運財透干', 'man大運財得地', 'man大運財透干2', 'man大運財得地2']

壬己辛|丙壬
子亥亥|申午
['man日支六沖', 'man財得地', 'man大運財透干', 'man大運財透干2', 'man財得地2']

癸丙乙|癸癸
丑戌卯|未未
['man日支六沖', 'man流年大運伏吟', 'man大運日支六沖', 'man流年大運地支伏吟']

癸辛庚|甲己
丑巳寅|申未
['man日支六沖']

癸乙丙|丁己
酉未辰|酉卯
['man日支六沖', 'man大運財透干', 'man大運財透干2']

癸乙壬|戊己
亥巳寅|申巳
['man日支六沖', 'man財得地', 'man大運日干五合', 'man財得地2']

庚乙癸|壬甲
午卯巳|子子
['man日支六沖', 'man財透干', 'man大運日支六沖', 'man財透干2', 'man流年大運地支伏吟']

丁戊癸|丙乙
酉午巳|辰卯
['man日支六沖', 'man大運日支六合']

丙甲癸|壬丙
午子丑|戌子
['man日支六沖']

乙己己|丙辛
卯巳丑|寅酉
['man日支六沖']

癸甲己|壬辛
亥戌未|申巳
['man日支六沖', 'man財得地', 'man財得地2']

庚戊庚|庚丙
午子戌|寅子
['man日支六沖', 'man大運財得地', 'man大運財得地2']

甲乙乙|辛壬
戌酉卯|巳辰
['man日支六沖', 'man財得地', 'man財得地2']

乙丁丁|甲己
亥未未|辰巳
['man日支六沖', 'man財透干', 'man大運財得地', 'man大運財得地2', 'man財透干2']

甲戊戊|癸戊
申午戌|亥寅
['man日支六沖', 'man財透干', 'man流年大運天地合', 'man財透干2']

癸壬癸|庚癸
巳戌卯|申亥
['man日支六沖', 'man大運日支六合']

乙庚辛|丁己
酉子亥|酉卯
['man日支六沖', 'man財透干', 'man財透干2']

壬壬己|庚庚
戌申未|午辰
['man日支六沖', 'man大運財得地', 'man大運財得地2']

丙甲癸|辛甲
午子巳|酉子
['man日支六沖', 'man大運財透干', 'man大運財得地', 'man大運財透干2', 'man大運財得地2', 'man大運日干五合']

庚壬辛|庚甲
辰辰亥|寅戌
['man日支六沖', 'man財透干', 'man大運財得地', 'man大運財得地2', 'man財透干2']

戊辛丙|癸壬
寅丑午|卯申
['man日支六沖', 'man財透干', 'man大運財透干', 'man大運財透干2', 'man大運日干五合', 'man財透干2']

壬辛壬|甲戊
戌亥寅|寅辰
['man日支六沖']

戊庚丙|癸戊
申子午|卯寅
['man日支六沖', 'man大運財透干', 'man大運財透干2', 'man大運日干五合']

庚乙庚|戊壬
子酉戌|子午
['man日支六沖']

己戊丙|壬己
未戌辰|寅丑
['man日支六沖', 'man大運財透干', 'man大運財透干2']

In [ ]:
# 日支大運地支伏吟
# man流年大運地支伏吟 del
#大運雙體食傷