In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import nltk

from functions import *

In [2]:
#show full text of columns
pd.set_option('display.max_colwidth', -1)
#show all columns
pd.set_option('display.max_columns', None)
#show 3 rows only
# pd.set_option('display.max_rows', 5)
# show 10 rows only
pd.set_option('display.max_rows', 10)

C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_24436\3836281045.py:2: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)

In [3]:
man_df = pd.read_csv(r"C:\Users\TOSHIBA\Documents\Github\FateAi\Bazi Data Scraping and Analysis\maxicoDivorceData.csv", encoding='latin1', header=0)

In [5]:
translation = {
    'Fecha de Registro': 'Registration_Date',
    'Tipo': 'Type',
    'Nacionalidad': 'Nationality',
    'F_Naci_Do': 'Groom_Birth_Date',
    'LocNaci_Do': 'Groom_Birth_City',
    'MpioNaci_Do': 'Groom_Birth_Municipality',
    'EFedNaci_Do': 'Groom_Birth_State',
    'PaisNaci_Do': 'Groom_Birth_Country',
    'Edad': 'Age',
    'MpioHab_Do': 'Residence_Municipality',
    'EFedHab_Do': 'Residence_State',
    'PaisHab_Do': 'Residence_Country',
    'ElIngreso': 'Groom_Income',
    'OcupaciÃ³n_Do': 'Groom_Occupation',
    'LocHabi_Do': 'Residence_City',
    'Nacionalidad2': 'Bride_Nationality',
    'F_Naci_Da': 'Bride_Birth_Date',
    'Fecha de Registro 2': 'Registration_Date_2',
    'LocNaci_Da': 'Bride_Birth_City',
    'MpioNaci_Da': 'Bride_Birth_Municipality',
    'EFedNaci_Da': 'Bride_Birth_State',
    'PaisNaci_Da': 'Bride_Birth_Country',
    'Edad2': 'Bride_Age',
    'LocHabi_Da': 'Bride_Residence_City',
    'MpioHab_Da': 'Bride_Residence_Municipality',
    'EFedHab_Da': 'Bride_Residence_State',
    'PaisHab_Da': 'Bride_Residence_Country',
    'OcupaciÃ³n_Da': 'Bride_Occupation',
    'EllaIngreso': 'Bride_Income',
    'Fecha': 'Marriage_Date',
    'Localidad': 'Location',
    'Municipio': 'Municipality',
    'Entidad Federativa': 'State',
    'ElEscolaridad': 'Groom_Education',
    'ElTrabajo': 'Groom_Employment',
    'EllaEscolaridad': 'Bride_Education',
    'EllaTrabajo': 'Bride_Employment',
    'Matri_AÃ±os': 'Marriage_Years',
    'Matri_Meses': 'Marriage_Months',
    'Num_Hijos': 'Number_of_Children',
    'Custodia': 'Custody'
}

man_df.rename(columns=translation, inplace=True)
man_df.columns = man_df.columns.str.replace(' ', '_')

In [6]:
man_df

,Registration_Date,Type,Nationality,Groom_Birth_Date,Groom_Birth_City,Groom_Birth_Municipality,Groom_Birth_State,Groom_Birth_Country,Age,Residence_Municipality,Residence_State,Residence_Country,Groom_Income,Groom_Occupation,Residence_City,Bride_Nationality,Bride_Birth_Date,Registration_Date_2,Bride_Birth_City,Bride_Birth_Municipality,Bride_Birth_State,Bride_Birth_Country,Bride_Age,Bride_Residence_City,Bride_Residence_Municipality,Bride_Residence_State,Bride_Residence_Country,Bride_Occupation,Bride_Income,Marriage_Date,Location,Municipality,State,Groom_Education,Groom_Employment,Bride_Education,Bride_Employment,Marriage_Years,Marriage_Months,Number_of_Children,Custody
0,09/06/2006,Necesario,MEXICANA,18/12/1975,XALAPA - ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,30.0,XALAPA,VERACRUZ,MEXICO,2000.0,PINTOR,XALAPA-ENRIQUEZ,MEXICANA,08/01/1983,NaN,PUEBLA,PUEBLA,PUEBLA,MEXICO,22.0,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,EMPLEADA,1800.0,26/06/2000,XALAPA,XALAPA,VERACRUZ,SECUNDARIA,OBRERO,SECUNDARIA,EMPLEADO,5.0,NaN,1.0,NaN
1,01/02/2000,Voluntario,MEXICANA,NaN,NaN,NaN,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,MEXICANA,NaN,NaN,NaN,NaN,NaN,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN,17/02/1977,XALAPA,XALAPA,VERACRUZ,PREPARATORIA,ESTABLECIMIENTO,PREPARATORIA,EMPLEADO,NaN,NaN,NaN,NaN
2,01/02/2005,Necesario,MEXICANA,22/02/1955,XALAPA - ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,49.0,NaN,NaN,NaN,NaN,MEDICO,NaN,MEXICANA,21/03/1947,NaN,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,57.0,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,JUBILADA,NaN,18/12/1975,XALAPA,XALAPA,VERACRUZ,PREPARATORIA,OBRERO,NaN,TRABAJADOR POR CUENTA PROPIA EN VIA PUBLICA,NaN,NaN,NaN,NaN
3,01/02/2006,Necesario,MEXICANA,20/01/1964,XALAPA - ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,42.0,XALAPA,VERACRUZ,MEXICO,6000.0,EMPLEADO,XALAPA-ENRIQUEZ,MEXICANA,NaN,NaN,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,NaN,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,COMERCIANTE,5000.0,03/12/1987,XALAPA,XALAPA,VERACRUZ,PROFESIONAL,EMPLEADO,PREPARATORIA,EMPLEADO,18.0,NaN,2.0,MADRE
4,01/02/2006,Necesario,MEXICANA,30/10/1975,XALAPA - ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,30.0,COATEPEC,VERACRUZ,MEXICO,18000.0,MEDICO,COATEPEC,MEXICANA,13/10/1978,NaN,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,27.0,COATEPEC,COATEPEC,VERACRUZ,MEXICO,AMA DE CASA,NaN,14/11/1998,XALAPA,XALAPA,VERACRUZ,PROFESIONAL,EMPLEADO,PREPARATORIA,NO TRABAJA,7.0,NaN,2.0,MADRE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4918,31/10/2012,Voluntario,MEXICANA,29/10/1977,MORELIA,MORELIA,MICHOACAN,MEXICO,35.0,MORELIA,MICHOACAN,MEXICO,12500.0,AUDITOR,MORELIA,MEXICANA,12/01/1978,16/02/1978,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,34.0,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,EMPLEADA,6000.0,25/10/2008,XALAPA,XALAPA,VERACRUZ,PROFESIONAL,EMPLEADO,PROFESIONAL,EMPLEADO,3.0,11.0,NaN,NaN
4919,31/10/2013,Voluntario,MEXICANA,10/11/1982,VERACRUZ,VERACRUZ,VERACRUZ,MEXICO,30.0,XALAPA,VERACRUZ,MEXICO,NaN,EMPLEADO,XALAPA-ENRIQUEZ,MEXICANA,09/02/1981,05/09/1989,TLAPACOYAN,TLAPACOYAN,VERACRUZ,MEXICO,32.0,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,EMPLEADA,NaN,26/05/2012,XALAPA,XALAPA,VERACRUZ,PROFESIONAL,EMPLEADO,PROFESIONAL,EMPLEADO,1.0,NaN,NaN,NaN
4920,31/10/2013,Voluntario,MEXICANA,28/10/1954,XALAPA - ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,59.0,EMILIANO ZAPATA,VERACRUZ,MEXICO,20000.0,MEDICO,EMILIANO ZAPATA,MEXICANA,17/02/1957,03/04/1957,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,56.0,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,JUBILADA,29000.0,02/06/1978,XALAPA,XALAPA,VERACRUZ,PROFESIONAL,EMPLEADO,PROFESIONAL,EMPLEADO,35.0,NaN,2.0,NaN
4921,31/12/2012,Voluntario,MEXICANA,07/02/1958,TLAPACOYAN,TLAPACOYAN,VERACRUZ,MEXICO,54.0,XALAPA,VERACRUZ,MEXICO,NaN,EMPLEADO,XALAPA-ENRIQUEZ,MEXICANA,27/01/1964,11/03/1964,TLAPACOYAN,TLAPACOYAN,VERACRUZ,MEXICO,48.0,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,AMA DE CASA,NaN,05/11/1979,TLAPACOYAN,TLAPACOYAN,VERACRUZ,PREPARATORIA,NaN,PRIMARIA,NO TRABAJA,33.0,NaN,2.0,NaN
4922,31/12/2013,Voluntario,MEXICANA,22/06/1960,TLACOTALPAN,TLACOTALPAN,VERACRUZ,MEXICO,53.0,XALAPA,VERACRUZ,MEXICO,20000.0,CONTADOR,XALAPA-ENRIQUEZ,MEXICANA,22/01/1972,07/09/1972,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,41.0,XALAPA-ENRIQUEZ,XALAPA,VERACRUZ,MEXICO,ARQUITECTA,20000.0,22/08/2009,COATEPEC,COATEPEC,VERACRUZ,PROFESIONAL,EMPLEADO,PROFESIONAL,EMPLEADO,4.0,NaN,NaN,NaN

In [9]:
#get only  Registration_Date Groom_Birth_Date Age Groom_Income Groom_Occupation Marriage_Date Marriage_Years Number_of_Children
selected_columns = ['Registration_Date', 'Groom_Birth_Date', 'Age', 'Groom_Income', 'Groom_Occupation',
                    'Marriage_Date', 'Marriage_Years', 'Number_of_Children']

man_df_selected = man_df[selected_columns]

In [10]:
man_df_selected

,Registration_Date,Groom_Birth_Date,Age,Groom_Income,Groom_Occupation,Marriage_Date,Marriage_Years,Number_of_Children
0,09/06/2006,18/12/1975,30.0,2000.0,PINTOR,26/06/2000,5.0,1.0
1,01/02/2000,NaN,47.0,NaN,NaN,17/02/1977,NaN,NaN
2,01/02/2005,22/02/1955,49.0,NaN,MEDICO,18/12/1975,NaN,NaN
3,01/02/2006,20/01/1964,42.0,6000.0,EMPLEADO,03/12/1987,18.0,2.0
4,01/02/2006,30/10/1975,30.0,18000.0,MEDICO,14/11/1998,7.0,2.0
...,...,...,...,...,...,...,...,...
4918,31/10/2012,29/10/1977,35.0,12500.0,AUDITOR,25/10/2008,3.0,NaN
4919,31/10/2013,10/11/1982,30.0,NaN,EMPLEADO,26/05/2012,1.0,NaN
4920,31/10/2013,28/10/1954,59.0,20000.0,MEDICO,02/06/1978,35.0,2.0
4921,31/12/2012,07/02/1958,54.0,NaN,EMPLEADO,05/11/1979,33.0,2.0
4922,31/12/2013,22/06/1960,53.0,20000.0,CONTADOR,22/08/2009,4.0,NaN

In [11]:
#drop if Groom_Birth_Date is NaN
man_df_selected = man_df_selected.dropna(subset=['Groom_Birth_Date'])

#convert Registration_Date Groom_Birth_Date Marriage_Date to datetime

man_df_selected['Registration_Date'] = pd.to_datetime(man_df_selected['Registration_Date'])
man_df_selected['Groom_Birth_Date'] = pd.to_datetime(man_df_selected['Groom_Birth_Date'])
man_df_selected['Marriage_Date'] = pd.to_datetime(man_df_selected['Marriage_Date'])

c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/01/2004' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/01/2009' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/01/2010' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/01/2011' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/01/2012' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/02/2001' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/02/2002' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/02/2003' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/02/2004' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/02/2007' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/02/2008' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/02/2009' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/02/2012' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/02/2013' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/02/2014' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/03/2006' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/03/2008' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/03/2012' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/03/2013' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/03/2014' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/04/2004' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/04/2005' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/04/2007' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/04/2009' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/04/2011' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/04/2012' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/05/2003' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/05/2005' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/05/2008' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/05/2009' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/05/2011' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/05/2013' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/06/2003' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/06/2005' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/06/2006' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/06/2007' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/06/2008' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/06/2012' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/07/2000' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/07/2001' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/07/2004' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/07/2005' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/07/2006' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/07/2007' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/07/2009' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/07/2010' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/07/2011' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/07/2012' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/08/2001' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/08/2003' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/08/2004' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/08/2007' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/08/2008' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/08/2009' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/08/2010' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/08/2012' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/09/2000' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/09/2001' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/09/2002' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/09/2005' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/09/2006' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/09/2010' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/09/2013' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/10/2000' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/10/2003' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/10/2004' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/10/2011' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/10/2014' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/11/2000' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/11/2001' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  cache_array = _maybe_cache(arg, format, cache, convert_listlike)
c:\Users\TOSHIBA\anaconda3\lib\site-packages\pandas\core\tools\datetimes.py:1047: UserWarning: Parsing '13/11/2002' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.

In [12]:
man_df_selected

,Registration_Date,Groom_Birth_Date,Age,Groom_Income,Groom_Occupation,Marriage_Date,Marriage_Years,Number_of_Children
0,2006-09-06,1975-12-18,30.0,2000.0,PINTOR,2000-06-26,5.0,1.0
2,2005-01-02,1955-02-22,49.0,NaN,MEDICO,1975-12-18,NaN,NaN
3,2006-01-02,1964-01-20,42.0,6000.0,EMPLEADO,1987-03-12,18.0,2.0
4,2006-01-02,1975-10-30,30.0,18000.0,MEDICO,1998-11-14,7.0,2.0
5,2006-01-02,1973-03-28,32.0,NaN,EMPLEADO,1995-01-20,11.0,2.0
...,...,...,...,...,...,...,...,...
4918,2012-10-31,1977-10-29,35.0,12500.0,AUDITOR,2008-10-25,3.0,NaN
4919,2013-10-31,1982-10-11,30.0,NaN,EMPLEADO,2012-05-26,1.0,NaN
4920,2013-10-31,1954-10-28,59.0,20000.0,MEDICO,1978-02-06,35.0,2.0
4921,2012-12-31,1958-07-02,54.0,NaN,EMPLEADO,1979-05-11,33.0,2.0
4922,2013-12-31,1960-06-22,53.0,20000.0,CONTADOR,2009-08-22,4.0,NaN

In [14]:
#sort by Registration_Date
man_df_selected.sort_values('Age')

,Registration_Date,Groom_Birth_Date,Age,Groom_Income,Groom_Occupation,Marriage_Date,Marriage_Years,Number_of_Children
1124,2006-07-11,1987-04-02,19.0,13000.0,EMPLEADO,2005-08-06,1.0,NaN
312,2005-03-03,1985-07-26,19.0,NaN,EMPLEADO,2003-07-24,NaN,NaN
3532,2011-06-22,1991-06-15,19.0,NaN,ESTUDIANTE,2010-05-25,1.0,NaN
516,2011-04-05,1990-02-10,20.0,2000.0,EMPLEADO,2008-12-02,NaN,NaN
57,2010-01-06,1989-10-19,20.0,4000.0,EMPLEADO,2009-02-16,1.0,NaN
...,...,...,...,...,...,...,...,...
1720,2010-11-08,1933-10-06,77.0,3800.0,PENSIONADO,1993-04-23,17.0,NaN
237,2009-02-07,1931-05-25,78.0,15000.0,PENSIONADO,1977-10-09,38.0,1.0
4894,2001-08-31,1922-11-30,78.0,3000.0,MAESTRO,1955-12-14,45.0,4.0
3234,2006-09-20,1923-07-04,83.0,NaN,JUBILADO,1957-11-02,49.0,1.0
915,2011-06-09,1920-08-07,91.0,NaN,NaN,1950-06-02,61.0,NaN

In [15]:
# create col Age_at_Marriage 
man_df_selected['Age_at_Marriage'] = (man_df_selected['Marriage_Date'] - man_df_selected['Groom_Birth_Date']).dt.days // 365

C:\Users\TOSHIBA\AppData\Local\Temp\ipykernel_24436\3622279673.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  man_df_selected['Age_at_Marriage'] = (man_df_selected['Marriage_Date'] - man_df_selected['Groom_Birth_Date']).dt.days // 365

In [19]:
count = (man_df_selected['Marriage_Date'] < man_df_selected['Groom_Birth_Date']).sum()
print("Number of Marriage_Date > Groom_Birth_Date:", count)

Number of Marriage_Date > Groom_Birth_Date: 1

In [16]:
man_df_selected

,Registration_Date,Groom_Birth_Date,Age,Groom_Income,Groom_Occupation,Marriage_Date,Marriage_Years,Number_of_Children,Age_at_Marriage
0,2006-09-06,1975-12-18,30.0,2000.0,PINTOR,2000-06-26,5.0,1.0,24
2,2005-01-02,1955-02-22,49.0,NaN,MEDICO,1975-12-18,NaN,NaN,20
3,2006-01-02,1964-01-20,42.0,6000.0,EMPLEADO,1987-03-12,18.0,2.0,23
4,2006-01-02,1975-10-30,30.0,18000.0,MEDICO,1998-11-14,7.0,2.0,23
5,2006-01-02,1973-03-28,32.0,NaN,EMPLEADO,1995-01-20,11.0,2.0,21
...,...,...,...,...,...,...,...,...,...
4918,2012-10-31,1977-10-29,35.0,12500.0,AUDITOR,2008-10-25,3.0,NaN,31
4919,2013-10-31,1982-10-11,30.0,NaN,EMPLEADO,2012-05-26,1.0,NaN,29
4920,2013-10-31,1954-10-28,59.0,20000.0,MEDICO,1978-02-06,35.0,2.0,23
4921,2012-12-31,1958-07-02,54.0,NaN,EMPLEADO,1979-05-11,33.0,2.0,20
4922,2013-12-31,1960-06-22,53.0,20000.0,CONTADOR,2009-08-22,4.0,NaN,49

In [17]:
#sort by Registration_Date
man_df_selected.sort_values('Age_at_Marriage')

,Registration_Date,Groom_Birth_Date,Age,Groom_Income,Groom_Occupation,Marriage_Date,Marriage_Years,Number_of_Children,Age_at_Marriage
462,2001-04-01,1943-03-06,57.0,10000.0,COMERCIANTE,1931-08-31,30.0,4.0,-12
4504,2001-01-29,1974-05-23,26.0,2000.0,EMPLEADO,1984-01-21,1.0,NaN,9
1687,2004-11-06,1976-10-03,28.0,NaN,EMPLEADO,1986-10-17,13.0,2.0,10
216,2014-02-05,1975-08-11,38.0,10000.0,EMPLEADO,1987-03-13,23.0,NaN,11
3232,2005-09-20,1976-03-29,29.0,2000.0,EMPLEADO,1990-01-18,NaN,NaN,13
...,...,...,...,...,...,...,...,...,...
2769,2009-02-18,1934-06-24,74.0,9700.0,EMPLEADO,2002-07-13,6.0,NaN,68
1018,2013-07-03,1942-09-19,70.0,4000.0,PENSIONADO,2012-06-01,1.0,NaN,69
2886,2013-10-18,1940-06-22,73.0,NaN,EMPLEADO,2011-04-07,2.0,NaN,70
3980,2011-05-25,1936-10-17,74.0,NaN,PENSIONADO,2009-07-10,1.0,NaN,72
3493,2011-03-22,1935-03-09,75.0,2200.0,PENSIONADO,2007-11-15,3.0,NaN,72

In [20]:
#only get these 4 cols Registration_Date	Groom_Birth_Date  Age Groom_Occupation
selected_cols = ['Registration_Date', 'Groom_Birth_Date', 'Age', 'Groom_Occupation']
man_df_selected_subset = man_df_selected[selected_cols]

man_df_selected_subset

     Registration_Date Groom_Birth_Date   Age Groom_Occupation
0    2006-09-06        1975-12-18        30.0  PINTOR
2    2005-01-02        1955-02-22        49.0  MEDICO
3    2006-01-02        1964-01-20        42.0  EMPLEADO
4    2006-01-02        1975-10-30        30.0  MEDICO
5    2006-01-02        1973-03-28        32.0  EMPLEADO
...         ...               ...         ...       ...
4918 2012-10-31        1977-10-29        35.0  AUDITOR
4919 2013-10-31        1982-10-11        30.0  EMPLEADO
4920 2013-10-31        1954-10-28        59.0  MEDICO
4921 2012-12-31        1958-07-02        54.0  EMPLEADO
4922 2013-12-31        1960-06-22        53.0  CONTADOR

[4542 rows x 4 columns]

In [21]:
#export to csv
man_df_selected_subset.to_csv('man_divorce_only.csv', index=False)