In [10]:
import pandas as pd

In [11]:
# import birthdayDF.txt as a dataframe 
df = pd.read_csv("birthdayDF.txt", sep = ",")

In [12]:
df

,Name,Gender,BirthyYear,Bmonth,Bday,FatherDeadY,時干,時支,日干,日支,月干,月支,年干,年支
0,Kanye West,Male,1977,Jun,8,1977,己,丑,丙,申,丙,午,丁,巳
1,Miley Cyrus,Female,1992,Nov,23,1996,癸,丑,癸,卯,辛,亥,壬,申
2,Justin Timberlake,Male,1981,Jan,31,1984,乙,丑,己,酉,己,丑,庚,申
3,Angelina Jolie,Female,1975,Jun,4,1978,己,丑,辛,巳,辛,巳,乙,卯
4,Jennifer Aniston,Female,1969,Feb,11,1996,辛,丑,丁,巳,丙,寅,己,酉
5,Britney Spears,Female,1981,Dec,2,1988,乙,丑,甲,寅,己,亥,辛,酉
6,Taylor Swift,Female,1989,Dec,13,1992,辛,丑,丁,未,丙,子,己,巳
7,Rihanna,Female,1988,Feb,20,2003,丁,丑,乙,巳,甲,寅,戊,辰
8,Beyonce,Female,1981,Sep,4,2002,丁,丑,乙,酉,丙,申,辛,酉
9,Emma Watson,Female,1990,Apr,15,2004,丁,丑,庚,戌,庚,辰,庚,午
10,Leonardo DiCaprio,Male,1974,Nov,11,1993,己,丑,丙,辰,乙,亥,甲,寅
11,Will Smith,Male,1968,Sep,25,1996,癸,丑,戊,戌,辛,酉,戊,申
12,Alicia Keys,Female,1981,Jan,25,2002,癸,丑,癸,卯,己,丑,庚,申
13,Brad Pitt,Male,1963,Dec,18,1967,丁,丑,乙,未,甲,子,癸,卯
14,Mark Wahlberg,Male,1971,Jun,5,1982,己,丑,辛,酉,癸,巳,辛,亥
15,Selena Gomez,Female,1992,Jul,22,1998,乙,丑,己,亥,丁,未,壬,申
16,John Legend,Male,1978,Dec,28,1998,乙,丑,甲,子,甲,子,戊,午
17,Jim Carrey,Male,1962,Jan,17,1994,丁,丑,乙,卯,辛,丑,辛,丑
18,Jennifer Lopez,Female,1969,Jul,24,1986,丁,丑,庚,子,辛,未,己,酉
19,Denzel Washington,Male,1954,Dec,28,1991,癸,丑,戊,午,丙,子,甲,午

In [13]:
# print the df as json file
df.to_json("birthdayDF.json", orient = "records")

In [14]:
陽干=['甲','丙','戊','庚','壬']
陰干=['乙','丁','己','辛','癸']

陽地支=['子','午','申','戌','酉']
陰地支=['寅','卯','辰','巳','未']

In [15]:
# # write a python function to calculate the 十神 of a person's 日干
# def shishen(ri,other):
# for example:
#     shishen('丁','丙') --> '劫財' as 丁 is 陰火 and 丙 is 陽火, 丙是丁的劫財
#     shishen('丁','壬') --> '食神' as 丁 is 陰火 and 壬 is 陽水, 壬是丁的正官
#     shishen('丁','丁') --> '比肩' as 丁 is 陰火 and 丁 is 陰火, 丁是丁的比肩

In [17]:
gan_dict = {
    '甲': '比肩',
    '乙': '劫財',
    '丙': '食神',
    '丁': '傷官',
    '戊': '偏財',
    '己': '正財',
    '庚': '偏印',
    '辛': '正印',
    '壬': '七殺',
    '癸': '正官'
}
    
yin_yang_dict = {
    '甲': '陽木',
    '乙': '陰木',
    '丙': '陽火',
    '丁': '陰火',
    '戊': '陽土',
    '己': '陰土',
    '庚': '陽金',
    '辛': '陰金',
    '壬': '陽水',
    '癸': '陰水',
    '子': '陰水',
    '丑': '陰土',
    '寅': '陽木',
    '卯': '陰木',
    '辰': '陽土',
    '巳': '陰火',
    '午': '陽火',
    '未': '陰土',
    '申': '陽金',
    '酉': '陰金',
    '戌': '陽土',
    '亥': '陽水'
}

# val=yin_yang_dict[other]
# yy=val[0]
# wx=val[1]
# if(y==yy):

In [18]:
shishen_dict = {
    '甲': {'甲': '比肩', '乙': '劫財', '丙': '食神', '丁': '傷官', '戊': '偏財', '己': '正財', '庚': '七殺', '辛': '正官', '壬': '偏印', '癸': '正印'},
    '乙': {'甲': '劫財', '乙': '比肩', '丙': '傷官', '丁': '食神', '戊': '正財', '己': '偏財', '庚': '正官', '辛': '七殺', '壬': '正印', '癸': '偏印'},
    '丙': {'甲': '偏印', '乙': '正印', '丙': '比肩', '丁': '劫財', '戊': '食神', '己': '傷官', '庚': '偏財', '辛': '正財', '壬': '七殺', '癸': '正官'},
    '丁': {'甲': '正印', '乙': '偏印', '丙': '劫財', '丁': '比肩', '戊': '傷官', '己': '食神', '庚': '正財', '辛': '偏財', '壬': '正官', '癸': '七殺'},
    
    '戊': {'甲': '偏財', '乙': '正財', '丙': '偏印', '丁': '正印', '戊': '比肩', '己': '劫財', '庚': '食神', '辛': '傷官', '壬': '騙財', '癸': '正財'},
    
    '己': {'甲': '正官', '乙': '偏官', '丙': '正印', '丁': '偏印', '戊': '劫財', '己': '比肩', '庚': '傷官', '辛': '食神', '壬': '正財', '癸': '偏財'},
    
    '庚': {'甲': '偏財', '乙': '正財', '丙': '偏官', '丁': '正官', '戊': '偏印', '己': '正印', '庚': '比肩', '辛': '劫財', '壬': '食神', '癸': '傷官'},
    
    '辛': {'甲': '正財','乙': '偏財','丙': '正官','丁': '偏官','戊': '正印','己': '偏印','庚': '劫財','辛': '比肩','壬': '傷官','癸': '食神'},
    
    '壬': {'甲': '食神','乙': '傷官','丙': '偏財','丁': '正財','戊': '偏官','己': '正官','庚': '偏印','辛': '正印','壬': '比肩','癸': '劫財'},
    
    '癸': {'甲': '傷官','乙': '食神','丙': '正財','丁': '偏財','戊': '正官','己': '偏官','庚': '正印','辛': '偏印','壬': '劫財','癸': '比肩'}
    }

In [ ]:
The above is some rows of a df,
each row represent a person
first add shishen as 10 columns to the df, shishen=['比肩','劫財','食神','傷官','正財','偏財','正官','七殺','正印','偏印']

then create a function apply to each row 
first get the 日干 of each row 
then check the dictionary shishen_dict = {
    '甲': {'甲': '比肩', '乙': '劫財', '丙': '食神', '丁': '傷官', '戊': '偏財', '己': '正財', '庚': '七殺', '辛': '正官', '壬': '偏印', '癸': '正印'},
    '乙': {'甲': '劫財', '乙': '比肩', '丙': '傷官', '丁': '食神', '戊': '正財', '己': '偏財', '庚': '正官', '辛': '七殺', '壬': '正印', '癸': '偏印'},
    '丙': {'甲': '偏印', '乙': '正印', '丙': '比肩', '丁': '劫財', '戊': '食神', '己': '傷官', '庚': '偏財', '辛': '正財', '壬': '七殺', '癸': '正官'},
    '丁': {'甲': '正印', '乙': '偏印', '丙': '劫財', '丁': '比肩', '戊': '傷官', '己': '食神', '庚': '正財', '辛': '偏財', '壬': '正官', '癸': '七殺'},
    
    '戊': {'甲': '偏財', '乙': '正財', '丙': '偏印', '丁': '正印', '戊': '比肩', '己': '劫財', '庚': '食神', '辛': '傷官', '壬': '騙財', '癸': '正財'},
    
    '己': {'甲': '正官', '乙': '偏官', '丙': '正印', '丁': '偏印', '戊': '劫財', '己': '比肩', '庚': '傷官', '辛': '食神', '壬': '正財', '癸': '偏財'},
    
    '庚': {'甲': '偏財', '乙': '正財', '丙': '偏官', '丁': '正官', '戊': '偏印', '己': '正印', '庚': '比肩', '辛': '劫財', '壬': '食神', '癸': '傷官'},
    
    '辛': {'甲': '正財','乙': '偏財','丙': '正官','丁': '偏官','戊': '正印','己': '偏印','庚': '劫財','辛': '比肩','壬': '傷官','癸': '食神'},
    
    '壬': {'甲': '食神','乙': '傷官','丙': '偏財','丁': '正財','戊': '偏官','己': '正官','庚': '偏印','辛': '正印','壬': '比肩','癸': '劫財'},
    
    '癸': {'甲': '傷官','乙': '食神','丙': '正財','丁': '偏財','戊': '正官','己': '偏官','庚': '正印','辛': '偏印','壬': '劫財','癸': '比肩'}
    }

for example:
日主="甲"
get shishen_dict[日主] which is another dict, we call it dict2 here
then loop through the same row to see if other row has the key in this dict2
if yes(there must be, if not then something is wrong) then get the value then put into a list called shishen_of_each_person
each row should have a shishen_of_each_person with 10 values in this list, if not then sth is wrong
after that, count the number of each 十神 in the list shishen, then put the number into the df under corresponding shishen column

{'甲': '比肩',
 '乙': '劫財',
 '丙': '食神',
 '丁': '傷官',
 '戊': '偏財',
 '己': '正財',
 '庚': '七殺',
 '辛': '正官',
 '壬': '偏印',
 '癸': '正印'}

In [49]:
shishen=['比肩','劫財','食神','傷官','正財','偏財','正官','七殺','正印','偏印']

In [20]:
shishen=['比肩','劫財','食神','傷官','正財','偏財','正官','七殺','正印','偏印']
df = df.reindex(columns=[*df.columns.tolist(), *shishen])

In [22]:
# show all rows of the df
pd.set_option('display.max_rows', None)

In [24]:
df

,Name,Gender,BirthyYear,Bmonth,Bday,FatherDeadY,時干,時支,日干,日支,...,比肩,劫財,食神,傷官,正財,偏財,正官,七殺,正印,偏印
0,Kanye West,Male,1977,Jun,8,1977,己,丑,丙,申,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Miley Cyrus,Female,1992,Nov,23,1996,癸,丑,癸,卯,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Justin Timberlake,Male,1981,Jan,31,1984,乙,丑,己,酉,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Angelina Jolie,Female,1975,Jun,4,1978,己,丑,辛,巳,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jennifer Aniston,Female,1969,Feb,11,1996,辛,丑,丁,巳,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Britney Spears,Female,1981,Dec,2,1988,乙,丑,甲,寅,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Taylor Swift,Female,1989,Dec,13,1992,辛,丑,丁,未,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Rihanna,Female,1988,Feb,20,2003,丁,丑,乙,巳,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Beyonce,Female,1981,Sep,4,2002,丁,丑,乙,酉,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Emma Watson,Female,1990,Apr,15,2004,丁,丑,庚,戌,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Leonardo DiCaprio,Male,1974,Nov,11,1993,己,丑,丙,辰,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Will Smith,Male,1968,Sep,25,1996,癸,丑,戊,戌,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Alicia Keys,Female,1981,Jan,25,2002,癸,丑,癸,卯,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Brad Pitt,Male,1963,Dec,18,1967,丁,丑,乙,未,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Mark Wahlberg,Male,1971,Jun,5,1982,己,丑,辛,酉,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Selena Gomez,Female,1992,Jul,22,1998,乙,丑,己,亥,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,John Legend,Male,1978,Dec,28,1998,乙,丑,甲,子,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Jim Carrey,Male,1962,Jan,17,1994,丁,丑,乙,卯,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Jennifer Lopez,Female,1969,Jul,24,1986,丁,丑,庚,子,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Denzel Washington,Male,1954,Dec,28,1991,癸,丑,戊,午,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
# move the  col '日干' to the 6th col
cols = df.columns.tolist()
cols = cols[:5] + cols[6:] + cols[5:6]
df = df[cols]

In [29]:
df.iloc[0]['日干']

'丙'

In [26]:
len(df)

20

In [32]:
cols=['時干','時支','日支','月干','月支','年干','年支']

In [41]:
pd.options.mode.chained_assignment = 'warn'

In [57]:
for r in range(len(df)):
    shishen_list=[]
    日主=df.iloc[r]['日干']
    dict2=shishen_dict[日主]
    print(dict2)
    for c in cols:
        gz=df.iloc[r][c]
        ss=dict2[gz]
        shishen_list.append(ss)
    print(shishen_list)
    for s in shishen:
        df.at[r,s]=shishen_list.count(s)

{'甲': '偏印', '乙': '正印', '丙': '比肩', '丁': '劫財', '戊': '食神', '己': '傷官', '庚': '偏財', '辛': '正財', '壬': '七殺', '癸': '正官'}

KeyError: '丑'

In [52]:
df

,Name,Gender,BirthyYear,Bmonth,Bday,時干,時支,日干,日支,月干,...,劫財,食神,傷官,正財,偏財,正官,七殺,正印,偏印,FatherDeadY
0,Kanye West,Male,1977,Jun,8,己,丑,丙,申,丙,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1977
1,Miley Cyrus,Female,1992,Nov,23,癸,丑,癸,卯,辛,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1996
2,Justin Timberlake,Male,1981,Jan,31,乙,丑,己,酉,己,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1984
3,Angelina Jolie,Female,1975,Jun,4,己,丑,辛,巳,辛,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1978
4,Jennifer Aniston,Female,1969,Feb,11,辛,丑,丁,巳,丙,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1996
5,Britney Spears,Female,1981,Dec,2,乙,丑,甲,寅,己,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1988
6,Taylor Swift,Female,1989,Dec,13,辛,丑,丁,未,丙,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1992
7,Rihanna,Female,1988,Feb,20,丁,丑,乙,巳,甲,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2003
8,Beyonce,Female,1981,Sep,4,丁,丑,乙,酉,丙,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2002
9,Emma Watson,Female,1990,Apr,15,丁,丑,庚,戌,庚,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2004
10,Leonardo DiCaprio,Male,1974,Nov,11,己,丑,丙,辰,乙,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1993
11,Will Smith,Male,1968,Sep,25,癸,丑,戊,戌,辛,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1996
12,Alicia Keys,Female,1981,Jan,25,癸,丑,癸,卯,己,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2002
13,Brad Pitt,Male,1963,Dec,18,丁,丑,乙,未,甲,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1967
14,Mark Wahlberg,Male,1971,Jun,5,己,丑,辛,酉,癸,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1982
15,Selena Gomez,Female,1992,Jul,22,乙,丑,己,亥,丁,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1998
16,John Legend,Male,1978,Dec,28,乙,丑,甲,子,甲,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1998
17,Jim Carrey,Male,1962,Jan,17,丁,丑,乙,卯,辛,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1994
18,Jennifer Lopez,Female,1969,Jul,24,丁,丑,庚,子,辛,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1986
19,Denzel Washington,Male,1954,Dec,28,癸,丑,戊,午,丙,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1991