In [5]:
from selenium import webdriver
import time
from selenium.webdriver.support.ui import Select
driver = webdriver.Chrome()

from selenium.webdriver.common.by import By

In [ ]:
tenGod=[][10]
#  正官
# ▪ 偏官
# ▪ 正印
# ▪ 
# ▪ 正財偏印
# ▪ 偏財
# ▪ 比肩
# ▪ 劫財
# ▪ 食神
# ▪ 傷官

In [35]:
def Count10God(gods):
    countGod=[0]*10
    for god in gods:
#         print(god)
        if god == "正官":
            countGod[0]+=1
        if god == "偏官" or god =="七殺":
            countGod[1]=countGod[1]+1
#             print(countGod[1])
        if god == "正印":
            countGod[2]+=1
        if god == "偏印":
            countGod[3]+=1
        if god == "正財":
            countGod[4]+=1
        if god == "偏財":
            countGod[5]+=1
        if god == "比肩":
            countGod[6]+=1
        if god == "劫財":
            countGod[7]+=1
        if god == "食神":
            countGod[8]+=1
        if god == "傷官": 
            countGod[9]+=1
    return countGod

In [6]:
year="1996"
month="9"
day="17"
hr="3"
gender="Female"
# ['Justin Timberlake' 'Male' '1981' 'Jan' '31' '1984']

In [37]:
from textwrap import wrap
def get10god():
#     <font color="#336699">比肩</font>
    return10god=driver.find_elements_by_xpath("//font[@color='#336699']")
    gods=""
    for i in return10god:
        gods=gods+i.text
        
    gods=gods.replace("\n", "")
    g=gods[:16]
    
    g=wrap(g, 2)
# ['12', '34', '56', '78', '90']
#     gods=list(gods.strip())
    return Count10God(g)

In [3]:
print(get10god())

NameError: name 'get10god' is not defined

In [36]:
print(Count10God(get10god()))

七殺
比肩
日主
食神
比肩
比肩
傷官
傷官
[0, 1, 0, 0, 0, 0, 3, 0, 1, 2]

<ipython-input-7-d6adb59ea894>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  return10god=driver.find_elements_by_xpath("//font[@color='#336699']")

In [4]:
def getBAZI(year,month,day,hr,gender):
    driver.get("https://fatew.com/")
    select = Select(driver.find_element(By.NAME, "hityear"))
    select.select_by_value(year)

    select = Select(driver.find_element(By.NAME, "hitmonth"))
    select.select_by_visible_text(month)

    select = Select(driver.find_element(By.NAME, "hitday"))
    select.select_by_visible_text(day)

    select = Select(driver.find_element(By.NAME, "hittime"))
    # select.select_by_value(hr)
    select.select_by_visible_text(hr)

    if gender == "Male":
        driver.find_elements(By.ID,'male')[0].click()
        #click on the radio button by class="myradio"
        # driver.find_element_by_css_selector("input[type='radio'][value='1']").click()
        # modify he above line to make it work, there s AttributeError: 'WebDriver' object has no attribute 'find_element_by_css_selector'
        

    if gender =="Female":
        driver.find_elements(By.ID,'female')[0].click()

    driver.find_elements(By.CSS_SELECTOR,"input[type='submit'][id='submitb']")[0].click()

    returnv=driver.find_elements(By.XPATH,"//font[@size = '6' and @face='標楷體']")

    baz=""
    for i in returnv:
        baz=baz+i.text

    baz=baz.replace("\n", "")
    b=baz[0:4]+baz[5:]
    bazi=list(b.strip())
    return bazi

In [7]:
driver.get("https://fatew.com/")
select = Select(driver.find_element(By.NAME, "hityear"))
select.select_by_value(year)

select = Select(driver.find_element(By.NAME, "hitmonth"))
select.select_by_visible_text(month)

select = Select(driver.find_element(By.NAME, "hitday"))
select.select_by_visible_text(day)

select = Select(driver.find_element(By.NAME, "hittime"))
# select.select_by_value(hr)
select.select_by_visible_text(hr)

if gender == "Male":
    driver.find_elements(By.ID,'male')[0].click()
    #click on the radio button by class="myradio"
    # driver.find_element_by_css_selector("input[type='radio'][value='1']").click()
    # modify he above line to make it work, there s AttributeError: 'WebDriver' object has no attribute 'find_element_by_css_selector'
    

if gender =="Female":
    driver.find_elements(By.ID,'female')[0].click()

driver.find_elements(By.CSS_SELECTOR,"input[type='submit'][id='submitb']")[0].click()

returnv=driver.find_elements(By.XPATH,"//font[@size = '6' and @face='標楷體']")

baz=""
for i in returnv:
    baz=baz+i.text

baz=baz.replace("\n", "")
b=baz[0:4]+baz[5:]
bazi=list(b.strip())
print(bazi)

['壬', '寅', '丁', '巳', '丁', '酉', '丙', '子']

In [ ]:
# get the table with border=1 cellspacing=0 cellpadding=0 bordercolor="#F2F2F2" by selenium and then convert it to pandas dataframe
# https://stackoverflow.com/questions/50884670/how-to-convert-html-table-to-pandas-dataframe
# https://stackoverflow.com/questions/50884670/how-to-convert-html-table-to-pandas-dataframe

In [13]:
import pandas as pd
table_element = driver.find_elements(By.XPATH,'//table[@border="1" and @cellspacing="0" and @cellpadding="0" and @bordercolor="#F2F2F2"]')

# Convert the table element into a string of HTML
table_html = table_element[0].get_attribute('outerHTML')

# Use Pandas to parse the HTML string into a DataFrame
df = pd.read_html(table_html)[0]

# Close the WebDriver instance
# driver.quit()

# Display the resulting DataFrame
print(df)

       0   1   2   3       4                    5
0     西元  實歲  大運  流年  大運流年合化  運勢 ( 紅線越長代表該年運勢越佳 )
1   1957   3  辛未  丁酉     NaN                  NaN
2   1958   4  辛未  戊戌    地支土局                  NaN
3   1959   5  辛未  己亥    地支木局                  NaN
4   1960   6  辛未  庚子     NaN                  NaN
..   ...  ..  ..  ..     ...                  ...
77  2032  78  戊寅  壬子     NaN                  NaN
78  2033  79  戊寅  癸丑    天干化火                  NaN
79  2034  80  戊寅  甲寅     NaN                  NaN
80  2035  81  戊寅  乙卯     NaN                  NaN
81  2036  82  戊寅  丙辰     NaN                  NaN

[82 rows x 6 columns]

In [10]:
#make first row as header
new_header = df.iloc[0] #grab the first row for the header
df = df[1:] #take the data less the header row
df.columns = new_header #set the header row as the df header
#rename df to dayunliunian
dayunliunian=df
#save to csv
dayunliunian.to_csv("dayunliunian.csv",index=False)

In [12]:
dayunliunian

0     西元  實歲  大運  流年    大運流年合化 運勢 ( 紅線越長代表該年運勢越佳 )
1   1999   3  丙申  己卯       NaN                 NaN
2   2000   4  丙申  庚辰      地支水局                 NaN
3   2001   5  丙申  辛巳  天干化水地支合水                 NaN
4   2002   6  丙申  壬午       NaN                 NaN
5   2003   7  丙申  癸未       NaN                 NaN
..   ...  ..  ..  ..       ...                 ...
77  2074  78  己丑  甲午      天干化土                 NaN
78  2075  79  己丑  乙未      地支土局                 NaN
79  2076  80  己丑  丙申       NaN                 NaN
80  2077  81  己丑  丁酉      地支金局                 NaN
81  2078  82  己丑  戊戌      地支土局                 NaN

[81 rows x 6 columns]

In [20]:
#make the first row as the header
new_header = df.iloc[0] #grab the first row for the header
df = df[1:] #take the data less the header row
df.columns = new_header #set the header row as the df header
df

0     西元  實歲  大運  流年 大運流年合化 運勢 ( 紅線越長代表該年運勢越佳 )
1   1983   2  庚寅  癸亥   地支合木                 NaN
2   1984   3  庚寅  甲子    NaN                 NaN
3   1985   4  庚寅  乙丑   天干化金                 NaN
4   1986   5  庚寅  丙寅    NaN                 NaN
5   1987   6  庚寅  丁卯    NaN                 NaN
..   ...  ..  ..  ..    ...                 ...
77  2058  77  丁酉  戊寅    NaN                 NaN
78  2059  78  丁酉  己卯    NaN                 NaN
79  2060  79  丁酉  庚辰   地支合金                 NaN
80  2061  80  丁酉  辛巳   地支金局                 NaN
81  2062  81  丁酉  壬午   天干化木                 NaN

[81 rows x 6 columns]

In [29]:
a=[]
with open("bazidata.txt","r") as r:
    a=r.readlines()
print(a[0])

1. Kanye West (Male, b. June 8, 1977, Father died in 1977)

In [ ]:
import calendar
abbr_to_num = {name: num for num, name in enumerate(calendar.month_abbr) if num}
abbr_to_num[month]

In [ ]:
month=bd[0:3]
month

start = bd.find(' ')
end =bd.find(',')
day=bd[start+1:end]

start = bd.find(', ')
yr=bd[start+2:]
yr

In [128]:
data=[]

In [129]:
for i,line in enumerate(a):
    sdf=[]
    start = line.find('. ')
    end = line.find(' (')
    n=line[start+2:end]
    sdf.append(n)
    
    start = line.find('(')
    end =line.find(',')
    gender=line[start+1:end]
    sdf.append(gender)
    
    start =line.find(', b. ')
    end =line.find(', Father')
    bd=line[start+5:end]

    start = bd.find(', ')
    yr=bd[start+2:]
    sdf.append(yr)
        
    month=bd[0:3]
    sdf.append(month)
    
    start = bd.find(' ')
    end =bd.find(',')
    day=bd[start+1:end]
    sdf.append(day)
    
    start = line.find('Father died in ')
    end =line.find(')')
    fdy=line[start+15:end]
    sdf.append(fdy)
    
    data.append(sdf)

In [185]:
data

array([['Kanye West', 'Male', '1977', 'Jun', '8', '1977'],
       ['Miley Cyrus', 'Female', '1992', 'Nov', '23', '1996'],
       ['Justin Timberlake', 'Male', '1981', 'Jan', '31', '1984'],
       ['Angelina Jolie', 'Female', '1975', 'Jun', '4', '1978'],
       ['Jennifer Aniston', 'Female', '1969', 'Feb', '11', '1996'],
       ['Britney Spears', 'Female', '1981', 'Dec', '2', '1988'],
       ['Taylor Swift', 'Female', '1989', 'Dec', '13', '1992'],
       ['Rihanna', 'Female', '1988', 'Feb', '20', '2003'],
       ['Beyonce', 'Female', '1981', 'Sep', '4', '2002'],
       ['Emma Watson', 'Female', '1990', 'Apr', '15', '2004'],
       ['Leonardo DiCaprio', 'Male', '1974', 'Nov', '11', '1993'],
       ['Will Smith', 'Male', '1968', 'Sep', '25', '1996'],
       ['Alicia Keys', 'Female', '1981', 'Jan', '25', '2002'],
       ['Brad Pitt', 'Male', '1963', 'Dec', '18', '1967'],
       ['Mark Wahlberg', 'Male', '1971', 'Jun', '5', '1982'],
       ['Selena Gomez', 'Female', '1992', 'Jul', '22', '1998'],
       ['John Legend', 'Male', '1978', 'Dec', '28', '1998'],
       ['Jim Carrey', 'Male', '1962', 'Jan', '17', '1994'],
       ['Jennifer Lopez', 'Female', '1969', 'Jul', '24', '1986'],
       ['Denzel Washington', 'Male', '1954', 'Dec', '28', '1991']],
      dtype='<U17')

In [131]:
import numpy as np
data=np.array(data)

In [201]:
Allbazi=[]

In [213]:
for row in data:
    gender=row[1]
    month=row[3]
    abbr_to_num = {name: num for num, name in enumerate(calendar.month_abbr) if num}
    month=str(abbr_to_num[month])
    print(str(month))
    day=str(row[4])
    print(day)
    hr="1"
    year=str(row[2])
    bazi=getBAZI(year,month,day,hr,gender)
    print(row)
    print(bazi)
#     row=row+bazi
    Allbazi.append(bazi)
#     np.concatenate((row, bazi))
    
    
    
# year="1996"
# month="9"
# day="17"
# hr="3"
# gender="F"

6
8

<ipython-input-212-e5426efb9743>:17: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("input[type='radio'][value='1']").click()
<ipython-input-212-e5426efb9743>:21: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("input[type='submit'][id='submitb']").click()
<ipython-input-212-e5426efb9743>:23: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  returnv=driver.find_elements_by_xpath("//font[@size = '6' and @face='標楷體']")

['Kanye West' 'Male' '1977' 'Jun' '8' '1977']
['己', '丑', '丙', '申', '丙', '午', '丁', '巳']
11
23

<ipython-input-212-e5426efb9743>:19: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_css_selector("input[type='radio'][value='0']").click()

['Miley Cyrus' 'Female' '1992' 'Nov' '23' '1996']
['癸', '丑', '癸', '卯', '辛', '亥', '壬', '申']
1
31
['Justin Timberlake' 'Male' '1981' 'Jan' '31' '1984']
[]
6
4
['Angelina Jolie' 'Female' '1975' 'Jun' '4' '1978']
['己', '丑', '辛', '巳', '辛', '巳', '乙', '卯']
2
11
['Jennifer Aniston' 'Female' '1969' 'Feb' '11' '1996']
['辛', '丑', '丁', '巳', '丙', '寅', '己', '酉']
12
2
['Britney Spears' 'Female' '1981' 'Dec' '2' '1988']
['乙', '丑', '甲', '寅', '己', '亥', '辛', '酉']
12
13
['Taylor Swift' 'Female' '1989' 'Dec' '13' '1992']
['辛', '丑', '丁', '未', '丙', '子', '己', '巳']
2
20
['Rihanna' 'Female' '1988' 'Feb' '20' '2003']
['丁', '丑', '乙', '巳', '甲', '寅', '戊', '辰']
9
4
['Beyonce' 'Female' '1981' 'Sep' '4' '2002']
['丁', '丑', '乙', '酉', '丙', '申', '辛', '酉']
4
15
['Emma Watson' 'Female' '1990' 'Apr' '15' '2004']
['丁', '丑', '庚', '戌', '庚', '辰', '庚', '午']
11
11
['Leonardo DiCaprio' 'Male' '1974' 'Nov' '11' '1993']
['己', '丑', '丙', '辰', '乙', '亥', '甲', '寅']
9
25
['Will Smith' 'Male' '1968' 'Sep' '25' '1996']
['癸', '丑', '戊', '戌', '辛', '酉', '戊', '申']
1
25
['Alicia Keys' 'Female' '1981' 'Jan' '25' '2002']
['癸', '丑', '癸', '卯', '己', '丑', '庚', '申']
12
18
['Brad Pitt' 'Male' '1963' 'Dec' '18' '1967']
['丁', '丑', '乙', '未', '甲', '子', '癸', '卯']
6
5
['Mark Wahlberg' 'Male' '1971' 'Jun' '5' '1982']
['己', '丑', '辛', '酉', '癸', '巳', '辛', '亥']
7
22
['Selena Gomez' 'Female' '1992' 'Jul' '22' '1998']
['乙', '丑', '己', '亥', '丁', '未', '壬', '申']
12
28
['John Legend' 'Male' '1978' 'Dec' '28' '1998']
['乙', '丑', '甲', '子', '甲', '子', '戊', '午']
1
17
['Jim Carrey' 'Male' '1962' 'Jan' '17' '1994']
['丁', '丑', '乙', '卯', '辛', '丑', '辛', '丑']
7
24
['Jennifer Lopez' 'Female' '1969' 'Jul' '24' '1986']
['丁', '丑', '庚', '子', '辛', '未', '己', '酉']
12
28
['Denzel Washington' 'Male' '1954' 'Dec' '28' '1991']
['癸', '丑', '戊', '午', '丙', '子', '甲', '午']

In [223]:
len(Allbazi)
Allbazi[2]=bazi

In [224]:
Allbazi

[['己', '丑', '丙', '申', '丙', '午', '丁', '巳'],
 ['癸', '丑', '癸', '卯', '辛', '亥', '壬', '申'],
 ['乙', '丑', '己', '酉', '己', '丑', '庚', '申'],
 ['己', '丑', '辛', '巳', '辛', '巳', '乙', '卯'],
 ['辛', '丑', '丁', '巳', '丙', '寅', '己', '酉'],
 ['乙', '丑', '甲', '寅', '己', '亥', '辛', '酉'],
 ['辛', '丑', '丁', '未', '丙', '子', '己', '巳'],
 ['丁', '丑', '乙', '巳', '甲', '寅', '戊', '辰'],
 ['丁', '丑', '乙', '酉', '丙', '申', '辛', '酉'],
 ['丁', '丑', '庚', '戌', '庚', '辰', '庚', '午'],
 ['己', '丑', '丙', '辰', '乙', '亥', '甲', '寅'],
 ['癸', '丑', '戊', '戌', '辛', '酉', '戊', '申'],
 ['癸', '丑', '癸', '卯', '己', '丑', '庚', '申'],
 ['丁', '丑', '乙', '未', '甲', '子', '癸', '卯'],
 ['己', '丑', '辛', '酉', '癸', '巳', '辛', '亥'],
 ['乙', '丑', '己', '亥', '丁', '未', '壬', '申'],
 ['乙', '丑', '甲', '子', '甲', '子', '戊', '午'],
 ['丁', '丑', '乙', '卯', '辛', '丑', '辛', '丑'],
 ['丁', '丑', '庚', '子', '辛', '未', '己', '酉'],
 ['癸', '丑', '戊', '午', '丙', '子', '甲', '午']]

In [226]:
data=[['Kanye West', 'Male', '1977', 'Jun', '8', '1977'],
       ['Miley Cyrus', 'Female', '1992', 'Nov', '23', '1996'],
       ['Justin Timberlake', 'Male', '1981', 'Jan', '31', '1984'],
       ['Angelina Jolie', 'Female', '1975', 'Jun', '4', '1978'],
       ['Jennifer Aniston', 'Female', '1969', 'Feb', '11', '1996'],
       ['Britney Spears', 'Female', '1981', 'Dec', '2', '1988'],
       ['Taylor Swift', 'Female', '1989', 'Dec', '13', '1992'],
       ['Rihanna', 'Female', '1988', 'Feb', '20', '2003'],
       ['Beyonce', 'Female', '1981', 'Sep', '4', '2002'],
       ['Emma Watson', 'Female', '1990', 'Apr', '15', '2004'],
       ['Leonardo DiCaprio', 'Male', '1974', 'Nov', '11', '1993'],
       ['Will Smith', 'Male', '1968', 'Sep', '25', '1996'],
       ['Alicia Keys', 'Female', '1981', 'Jan', '25', '2002'],
       ['Brad Pitt', 'Male', '1963', 'Dec', '18', '1967'],
       ['Mark Wahlberg', 'Male', '1971', 'Jun', '5', '1982'],
       ['Selena Gomez', 'Female', '1992', 'Jul', '22', '1998'],
       ['John Legend', 'Male', '1978', 'Dec', '28', '1998'],
       ['Jim Carrey', 'Male', '1962', 'Jan', '17', '1994'],
       ['Jennifer Lopez', 'Female', '1969', 'Jul', '24', '1986'],
       ['Denzel Washington', 'Male', '1954', 'Dec', '28', '1991']]

In [228]:
import pandas as pd
# ['壬', '寅', '丁', '巳', '丁', '酉', '丙', '子']
# ["時干","時支","日干","日支","月干","月支","年干","年支"]
df = pd.DataFrame(data,columns=['Name','Gender',"BirthyYear","Bmonth","Bday","FatherDeadY"])
dfbazi=pd.DataFrame(Allbazi,columns=["時干","時支","日干","日支","月干","月支","年干","年支"])
result = pd.concat([df, dfbazi], axis=1, join='inner')
display(result)

,Name,Gender,BirthyYear,Bmonth,Bday,FatherDeadY,時干,時支,日干,日支,月干,月支,年干,年支
0,Kanye West,Male,1977,Jun,8,1977,己,丑,丙,申,丙,午,丁,巳
1,Miley Cyrus,Female,1992,Nov,23,1996,癸,丑,癸,卯,辛,亥,壬,申
2,Justin Timberlake,Male,1981,Jan,31,1984,乙,丑,己,酉,己,丑,庚,申
3,Angelina Jolie,Female,1975,Jun,4,1978,己,丑,辛,巳,辛,巳,乙,卯
4,Jennifer Aniston,Female,1969,Feb,11,1996,辛,丑,丁,巳,丙,寅,己,酉
5,Britney Spears,Female,1981,Dec,2,1988,乙,丑,甲,寅,己,亥,辛,酉
6,Taylor Swift,Female,1989,Dec,13,1992,辛,丑,丁,未,丙,子,己,巳
7,Rihanna,Female,1988,Feb,20,2003,丁,丑,乙,巳,甲,寅,戊,辰
8,Beyonce,Female,1981,Sep,4,2002,丁,丑,乙,酉,丙,申,辛,酉
9,Emma Watson,Female,1990,Apr,15,2004,丁,丑,庚,戌,庚,辰,庚,午
10,Leonardo DiCaprio,Male,1974,Nov,11,1993,己,丑,丙,辰,乙,亥,甲,寅
11,Will Smith,Male,1968,Sep,25,1996,癸,丑,戊,戌,辛,酉,戊,申
12,Alicia Keys,Female,1981,Jan,25,2002,癸,丑,癸,卯,己,丑,庚,申
13,Brad Pitt,Male,1963,Dec,18,1967,丁,丑,乙,未,甲,子,癸,卯
14,Mark Wahlberg,Male,1971,Jun,5,1982,己,丑,辛,酉,癸,巳,辛,亥
15,Selena Gomez,Female,1992,Jul,22,1998,乙,丑,己,亥,丁,未,壬,申
16,John Legend,Male,1978,Dec,28,1998,乙,丑,甲,子,甲,子,戊,午
17,Jim Carrey,Male,1962,Jan,17,1994,丁,丑,乙,卯,辛,丑,辛,丑
18,Jennifer Lopez,Female,1969,Jul,24,1986,丁,丑,庚,子,辛,未,己,酉
19,Denzel Washington,Male,1954,Dec,28,1991,癸,丑,戊,午,丙,子,甲,午

In [236]:
result.to_csv(r'birthdayDF.txt', header=True, index=None)

In [108]:
df.iloc[0:3,2]

0    1977
1    1992
2    1981
Name: BirthyYear, dtype: object

In [ ]:
bd="December 28, 1954"

In [90]:
month=bd[0:3]
month

start = bd.find(' ')
end =bd.find(',')
day=bd[start+1:end]

start = bd.find(', ')
yr=bd[start+2:]
yr

'1954'

In [89]:
day

'28'

In [85]:
import calendar
abbr_to_num = {name: num for num, name in enumerate(calendar.month_abbr) if num}
abbr_to_num[month]

12

In [78]:
calendar.month_abbr[2]

'Feb'

In [ ]:
/ask seperate the following data into different colume:
    1. Kanye West (Male, b. June 8, 1977, Father died in 1977)

In [21]:
bazi=[]

In [23]:
for i in returnv:
    bazi.append(i.text)
    print(i.text)

丙
丁
丁
壬
子
酉
巳
寅

In [25]:
for i in bazi:
    print(i)

丙
丁
丁
壬
子
酉
巳
寅

In [ ]:
"年干","月干","日干","時干","年支","月支","日支","時支"