In [710]:
from selenium import webdriver
import time
from selenium.webdriver.support.ui import Select
driver = webdriver.Chrome()

from selenium.webdriver.common.by import By

In [711]:
driver.get("https://almuten.net/view/events/711435")

In [920]:
Name="Nicole"
year="1996"
month="9"
day="17"
hr="3"
minute="29"
gender="F"
stratyear="2000"
七宮主星="金"

In [803]:
#hover this element: /html/body/div[1]/ul/li[2]/a
document=driver.find_element_by_xpath("/html/body/div[1]/ul/li[2]/a")
#click document
document.click()
# click <a href="/natal/edit" title="Create a new natal">新增</a>
new=driver.find_element_by_xpath("/html/body/div[1]/ul/li[2]/ul/li[2]/a")

new.click()

C:\Users\Atlas\AppData\Local\Temp\ipykernel_6680\4084745659.py:2: DeprecationWarning:

find_element_by_* commands are deprecated. Please use find_element() instead

C:\Users\Atlas\AppData\Local\Temp\ipykernel_6680\4084745659.py:6: DeprecationWarning:

find_element_by_* commands are deprecated. Please use find_element() instead

In [804]:
name=driver.find_element(By.NAME, "name")
#clear the box first
name.clear()
name.send_keys(Name)

yearbox = driver.find_element(By.NAME, "year")
#clear the box first
yearbox.clear()
yearbox.send_keys(year)

#send year to this element: /html/body/div[2]/div[2]/form/div/table/tbody/tr[3]/td[2]/input
yearbox = driver.find_element(By.NAME, "year")


select = Select(driver.find_element(By.NAME, "month"))
select.select_by_value(month)

select = Select(driver.find_element(By.NAME, "day"))
select.select_by_value(day)

select = Select(driver.find_element(By.NAME, "hour"))
select.select_by_value(hr)

select = Select(driver.find_element(By.NAME, "min"))
select.select_by_value(minute)

locationbox = driver.find_element(By.NAME, "location")
locationbox.clear()
locationbox.send_keys("香港")
#click element by value="搜尋"

searchlocation = driver.find_element(By.XPATH, "//input[@value='搜尋']")
searchlocation.click()

In [805]:
#scroll down to bottom
driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

In [806]:
#click element by name=“submit”
submit = driver.find_element(By.XPATH, "//input[@name='submit']")
submit.click()

In [807]:
#click this element by xpath:/html/body/div[1]/ul/li[4]/ul/li[1]/a
#hover this element: /html/body/div[1]/ul/li[2]/a
tools=driver.find_element_by_xpath("/html/body/div[1]/ul/li[4]/a")
#click document
tools.click()
element = driver.find_element_by_xpath("/html/body/div[1]/ul/li[4]/ul/li[1]/a")
element.click()

C:\Users\Atlas\AppData\Local\Temp\ipykernel_6680\4192314833.py:3: DeprecationWarning:

find_element_by_* commands are deprecated. Please use find_element() instead

C:\Users\Atlas\AppData\Local\Temp\ipykernel_6680\4192314833.py:6: DeprecationWarning:

find_element_by_* commands are deprecated. Please use find_element() instead

In [808]:
#uncheck the box /html/body/div[2]/div[2]/form/center/table/tbody/tr[3]/td[3]/input
box=driver.find_element_by_xpath("/html/body/div[2]/div[2]/form/center/table/tbody/tr[3]/td[3]/input")
box.click()
box=driver.find_element_by_xpath("/html/body/div[2]/div[2]/form/center/table/tbody/tr[5]/td[3]/input")
box.click()
box=driver.find_element_by_xpath("/html/body/div[2]/div[2]/form/center/table/tbody/tr[6]/td[2]/input")
box.click()

C:\Users\Atlas\AppData\Local\Temp\ipykernel_6680\1828384717.py:2: DeprecationWarning:

find_element_by_* commands are deprecated. Please use find_element() instead

C:\Users\Atlas\AppData\Local\Temp\ipykernel_6680\1828384717.py:4: DeprecationWarning:

find_element_by_* commands are deprecated. Please use find_element() instead

C:\Users\Atlas\AppData\Local\Temp\ipykernel_6680\1828384717.py:6: DeprecationWarning:

find_element_by_* commands are deprecated. Please use find_element() instead

In [809]:
startbox=driver.find_element_by_xpath("/html/body/div[2]/div[2]/form/center/table/tbody/tr[1]/td[2]/input")
startbox.clear()
startbox.send_keys(stratyear)

periodbox= Select(driver.find_element_by_xpath("/html/body/div[2]/div[2]/form/center/table/tbody/tr[2]/td[2]/select"))
periodbox.select_by_value("20")

C:\Users\Atlas\AppData\Local\Temp\ipykernel_6680\1132722272.py:1: DeprecationWarning:

find_element_by_* commands are deprecated. Please use find_element() instead

C:\Users\Atlas\AppData\Local\Temp\ipykernel_6680\1132722272.py:5: DeprecationWarning:

find_element_by_* commands are deprecated. Please use find_element() instead

In [810]:
#click /html/body/div[2]/div[2]/form/center/table/tbody/tr[7]/td/input
submit = driver.find_element(By.XPATH, "//input[@value='送出']")
submit.click()

In [811]:
#wait for 2 seconds
time.sleep(2)

In [921]:
#HERE

#get the tabel with xpath=/html/body/div[2]/div[2]/center/div/table
table = driver.find_element(By.XPATH, "/html/body/div[2]/div[2]/center/div/table")
#make the table into a pandas dataframe, first row is the header
import pandas as pd
df = pd.read_html(table.get_attribute('outerHTML'))[0]
#df.head()
#df.to_csv('test.csv', index=False)
#df.to_excel('test.xlsx', index=False)

In [922]:
df.head(20)

,日期,歲數,類別,事件,事件.1,事件.2,描述
0,2000-01-08,17.6,太陽弧,‹,=,Y,chart Meeting others; making profitable liais...
1,2000-07-06,18.1,太陽弧,T,=,I,chart Intense self-awareness; tremendous urge...
2,2001-04-21,18.9,太陽弧,<,=,P,chart
3,2001-09-18,19.3,太陽弧,Y,=,<,chart
4,2002-03-31,19.9,太陽弧,Q,=,E,chart Illumination of intelligence; thoughts;...
5,2002-09-20,20.3,太陽弧,O,=,‹,chart Possible break down of relationships; s...
6,2002-10-01,20.4,太陽弧,R,=,Y,chart Happiness in love; success; humanism; b...
7,2003-02-04,20.7,太陽弧,O,=,U,chart Losing focus of ambition; depression; s...
8,2003-02-23,20.8,太陽弧,E,=,Z,chart Social attitude becomes important
9,2003-03-05,20.8,太陽弧,Y,=,X,"chart Success, recognition, good fortune; sen..."
10,2003-09-06,21.3,太陽弧,W,=,Y,chart Feeling happy; being successful; conten...
11,2003-09-17,21.3,太陽弧,Z,=,P,chart The use of personal power and persuasion.
12,2004-01-04,21.6,太陽弧,P,=,T,chart Extreme force; persuasion; control; bru...
13,2004-08-11,22.2,太陽弧,X,=,E,chart Having one's point of view clarified or...
14,2004-09-25,22.4,太陽弧,O,=,I,chart Loss of ego focus is possible if socio-...
15,2005-07-16,23.2,太陽弧,Y,=,Q,chart Being rewarded; success; a great vacation.
16,2005-07-21,23.2,太陽弧,E,=,<,chart
17,2006-01-26,23.7,太陽弧,<,=,E,chart
18,2006-02-01,23.7,太陽弧,Q,=,Y,chart Recognition; success; feeling great.
19,2006-11-22,24.5,太陽弧,I,=,O,chart Exploring individuation through imagina...

In [923]:
#save df to csv file named My太陽弧2016-2035.csv
# df.to_csv('My太陽弧2016-2035.csv', index=False)

In [924]:
# import csv as df
# import pandas as pd
# df = pd.read_csv('My太陽弧2016-2035.csv')

In [925]:
# X=MC
# T=火星
# O=海王星
# ‹=升交點
# P=冥王星
# E=水星
# R=金星
# U=土星
# Q=太陽
# W=月亮
# Z=AC
# I=天王星
# Y=木星

#convert the 事件 into corrasponding planet symbol
df.replace('X','MC',inplace=True)
df.replace('T','火',inplace=True)
df.replace('O','海王',inplace=True)
df.replace('‹','升交點',inplace=True)
df.replace('P','冥王',inplace=True)
df.replace('E','水',inplace=True)
df.replace('R','金',inplace=True)
df.replace('U','土',inplace=True)
df.replace('Q','日',inplace=True)
df.replace('W','月',inplace=True)
df.replace('Z','AC',inplace=True)
df.replace('I','天王',inplace=True)
df.replace('Y','木',inplace=True)
df.replace('<','福點',inplace=True)

In [926]:
#count 事件
df['事件'].value_counts()

水      9
木      8
冥王     7
升交點    5
海王     5
天王     5
福點     4
土      4
金      4
火      4
日      4
月      3
AC     3
MC     3
Name: 事件, dtype: int64

In [927]:
df

,日期,歲數,類別,事件,事件.1,事件.2,描述
0,2000-01-08,17.6,太陽弧,升交點,=,木,chart Meeting others; making profitable liais...
1,2000-07-06,18.1,太陽弧,火,=,天王,chart Intense self-awareness; tremendous urge...
2,2001-04-21,18.9,太陽弧,福點,=,冥王,chart
3,2001-09-18,19.3,太陽弧,木,=,福點,chart
4,2002-03-31,19.9,太陽弧,日,=,水,chart Illumination of intelligence; thoughts;...
...,...,...,...,...,...,...,...
63,2018-11-26,36.5,太陽弧,天王,=,MC,chart An extraordinary time of life; probable...
64,2019-01-31,36.7,太陽弧,土,=,福點,chart
65,2019-03-21,36.8,太陽弧,日,=,火,"chart Energy applied directly, naturally, vig..."
66,2019-06-18,37.1,太陽弧,升交點,=,福點,chart
67,2019-10-15,37.4,太陽弧,金,=,AC,chart Niceness; being appreciated.

In [928]:
#create new col named 特別角度 with bool value = false
df['特別角度']= False
df

,日期,歲數,類別,事件,事件.1,事件.2,描述,特別角度
0,2000-01-08,17.6,太陽弧,升交點,=,木,chart Meeting others; making profitable liais...,False
1,2000-07-06,18.1,太陽弧,火,=,天王,chart Intense self-awareness; tremendous urge...,False
2,2001-04-21,18.9,太陽弧,福點,=,冥王,chart,False
3,2001-09-18,19.3,太陽弧,木,=,福點,chart,False
4,2002-03-31,19.9,太陽弧,日,=,水,chart Illumination of intelligence; thoughts;...,False
...,...,...,...,...,...,...,...,...
63,2018-11-26,36.5,太陽弧,天王,=,MC,chart An extraordinary time of life; probable...,False
64,2019-01-31,36.7,太陽弧,土,=,福點,chart,False
65,2019-03-21,36.8,太陽弧,日,=,火,"chart Energy applied directly, naturally, vig...",False
66,2019-06-18,37.1,太陽弧,升交點,=,福點,chart,False
67,2019-10-15,37.4,太陽弧,金,=,AC,chart Niceness; being appreciated.,False

In [929]:
df['事件'][0]

'升交點'

In [930]:
#combine 事件	事件.1	事件.2 into one col named 事件合併
df['事件合併']=df['事件'].astype(str)+df['事件.1'].astype(str)+df['事件.2'].astype(str)
df

,日期,歲數,類別,事件,事件.1,事件.2,描述,特別角度,事件合併
0,2000-01-08,17.6,太陽弧,升交點,=,木,chart Meeting others; making profitable liais...,False,升交點=木
1,2000-07-06,18.1,太陽弧,火,=,天王,chart Intense self-awareness; tremendous urge...,False,火=天王
2,2001-04-21,18.9,太陽弧,福點,=,冥王,chart,False,福點=冥王
3,2001-09-18,19.3,太陽弧,木,=,福點,chart,False,木=福點
4,2002-03-31,19.9,太陽弧,日,=,水,chart Illumination of intelligence; thoughts;...,False,日=水
...,...,...,...,...,...,...,...,...,...
63,2018-11-26,36.5,太陽弧,天王,=,MC,chart An extraordinary time of life; probable...,False,天王=MC
64,2019-01-31,36.7,太陽弧,土,=,福點,chart,False,土=福點
65,2019-03-21,36.8,太陽弧,日,=,火,"chart Energy applied directly, naturally, vig...",False,日=火
66,2019-06-18,37.1,太陽弧,升交點,=,福點,chart,False,升交點=福點
67,2019-10-15,37.4,太陽弧,金,=,AC,chart Niceness; being appreciated.,False,金=AC

In [931]:
#strip the space in 事件合併
df['事件合併']=df['事件合併'].str.strip()
df

,日期,歲數,類別,事件,事件.1,事件.2,描述,特別角度,事件合併
0,2000-01-08,17.6,太陽弧,升交點,=,木,chart Meeting others; making profitable liais...,False,升交點=木
1,2000-07-06,18.1,太陽弧,火,=,天王,chart Intense self-awareness; tremendous urge...,False,火=天王
2,2001-04-21,18.9,太陽弧,福點,=,冥王,chart,False,福點=冥王
3,2001-09-18,19.3,太陽弧,木,=,福點,chart,False,木=福點
4,2002-03-31,19.9,太陽弧,日,=,水,chart Illumination of intelligence; thoughts;...,False,日=水
...,...,...,...,...,...,...,...,...,...
63,2018-11-26,36.5,太陽弧,天王,=,MC,chart An extraordinary time of life; probable...,False,天王=MC
64,2019-01-31,36.7,太陽弧,土,=,福點,chart,False,土=福點
65,2019-03-21,36.8,太陽弧,日,=,火,"chart Energy applied directly, naturally, vig...",False,日=火
66,2019-06-18,37.1,太陽弧,升交點,=,福點,chart,False,升交點=福點
67,2019-10-15,37.4,太陽弧,金,=,AC,chart Niceness; being appreciated.,False,金=AC

In [941]:
Thelist=[
'日=MC', 'MC=日', '月=MC', 'MC=月', '金=MC', 'MC=金', '木=MC', 'MC=木', 
# '火=MC', 'MC=火', 
f'{七宮主星}=MC', f'MC={七宮主星}',
# '土=MC', 'MC=土',
'日=AC', 'AC=日', '月=AC', 'AC=月', '金=AC', 'AC=金', '火=AC', 'AC=火', 
# '木=AC', 'AC=木', 
f'{七宮主星}=AC', f'AC={七宮主星}',
# '土=AC', 'AC=土',
# '金=火', '火=金', '金=木', '木=金', '土=日', '土=月', '土=火', '土=金', '土=木', '日=土', '月=土', '火=土', '金=土', '木=土',
'日=月',
'日=金',
'日=木',
'日=火',
f'日={七宮主星}',
'月=日',
'月=金',
'月=木',
'月=火',
f'月={七宮主星}',
'金=日',
'金=月',
'金=木',
'金=火',
f'金={七宮主星}',
'木=日',
'木=月',
'木=金',
'木=火',
f'木={七宮主星}',
'火=日',
'火=月',
'火=金',
'火=木',
f'火={七宮主星}',

f'{七宮主星}=火',
f'{七宮主星}=金',
f'{七宮主星}=木',
f'{七宮主星}=日',
f'{七宮主星}=月',
]
# if 事件合併 in Thelist, then 特別角度 = True
for i in range(len(df)):
    if df['事件合併'][i] in Thelist:
        df['特別角度'][i]=True
    else:
        df['特別角度'][i]=False
df

C:\Users\Atlas\AppData\Local\Temp\ipykernel_6680\1118228009.py:48: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

c:\Users\Atlas\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Atlas\AppData\Local\Temp\ipykernel_6680\1118228009.py:46: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,日期,歲數,類別,事件,事件.1,事件.2,描述,特別角度,事件合併,year
0,2000-01-08,17.6,太陽弧,升交點,=,木,chart Meeting others; making profitable liais...,False,升交點=木,2000
1,2000-07-06,18.1,太陽弧,火,=,天王,chart Intense self-awareness; tremendous urge...,False,火=天王,2000
2,2001-04-21,18.9,太陽弧,福點,=,冥王,chart,False,福點=冥王,2001
3,2001-09-18,19.3,太陽弧,木,=,福點,chart,False,木=福點,2001
4,2002-03-31,19.9,太陽弧,日,=,水,chart Illumination of intelligence; thoughts;...,False,日=水,2002
...,...,...,...,...,...,...,...,...,...,...
63,2018-11-26,36.5,太陽弧,天王,=,MC,chart An extraordinary time of life; probable...,False,天王=MC,2018
64,2019-01-31,36.7,太陽弧,土,=,福點,chart,False,土=福點,2019
65,2019-03-21,36.8,太陽弧,日,=,火,"chart Energy applied directly, naturally, vig...",True,日=火,2019
66,2019-06-18,37.1,太陽弧,升交點,=,福點,chart,False,升交點=福點,2019
67,2019-10-15,37.4,太陽弧,金,=,AC,chart Niceness; being appreciated.,True,金=AC,2019

In [942]:
# print Thelist
print(Thelist)

['日=MC', 'MC=日', '月=MC', 'MC=月', '金=MC', 'MC=金', '木=MC', 'MC=木', '金=MC', 'MC=金', '日=AC', 'AC=日', '月=AC', 'AC=月', '金=AC', 'AC=金', '火=AC', 'AC=火', '金=AC', 'AC=金', '日=月', '日=金', '日=木', '日=火', '日=金', '月=日', '月=金', '月=木', '月=火', '月=金', '金=日', '金=月', '金=木', '金=火', '金=金', '木=日', '木=月', '木=金', '木=火', '木=金', '火=日', '火=月', '火=金', '火=木', '火=金', '金=火', '金=金', '金=木', '金=日', '金=月']

In [943]:
#count 特別角度 = True
df['特別角度'].value_counts()

False    55
True     13
Name: 特別角度, dtype: int64

In [944]:
# convert 特別角度 to int
df['特別角度'] = df['特別角度'].astype(int)
df

,日期,歲數,類別,事件,事件.1,事件.2,描述,特別角度,事件合併,year
0,2000-01-08,17.6,太陽弧,升交點,=,木,chart Meeting others; making profitable liais...,0,升交點=木,2000
1,2000-07-06,18.1,太陽弧,火,=,天王,chart Intense self-awareness; tremendous urge...,0,火=天王,2000
2,2001-04-21,18.9,太陽弧,福點,=,冥王,chart,0,福點=冥王,2001
3,2001-09-18,19.3,太陽弧,木,=,福點,chart,0,木=福點,2001
4,2002-03-31,19.9,太陽弧,日,=,水,chart Illumination of intelligence; thoughts;...,0,日=水,2002
...,...,...,...,...,...,...,...,...,...,...
63,2018-11-26,36.5,太陽弧,天王,=,MC,chart An extraordinary time of life; probable...,0,天王=MC,2018
64,2019-01-31,36.7,太陽弧,土,=,福點,chart,0,土=福點,2019
65,2019-03-21,36.8,太陽弧,日,=,火,"chart Energy applied directly, naturally, vig...",1,日=火,2019
66,2019-06-18,37.1,太陽弧,升交點,=,福點,chart,0,升交點=福點,2019
67,2019-10-15,37.4,太陽弧,金,=,AC,chart Niceness; being appreciated.,1,金=AC,2019

In [945]:
#make new col named year using 日期
df['year'] = pd.DatetimeIndex(df['日期']).year
df

,日期,歲數,類別,事件,事件.1,事件.2,描述,特別角度,事件合併,year
0,2000-01-08,17.6,太陽弧,升交點,=,木,chart Meeting others; making profitable liais...,0,升交點=木,2000
1,2000-07-06,18.1,太陽弧,火,=,天王,chart Intense self-awareness; tremendous urge...,0,火=天王,2000
2,2001-04-21,18.9,太陽弧,福點,=,冥王,chart,0,福點=冥王,2001
3,2001-09-18,19.3,太陽弧,木,=,福點,chart,0,木=福點,2001
4,2002-03-31,19.9,太陽弧,日,=,水,chart Illumination of intelligence; thoughts;...,0,日=水,2002
...,...,...,...,...,...,...,...,...,...,...
63,2018-11-26,36.5,太陽弧,天王,=,MC,chart An extraordinary time of life; probable...,0,天王=MC,2018
64,2019-01-31,36.7,太陽弧,土,=,福點,chart,0,土=福點,2019
65,2019-03-21,36.8,太陽弧,日,=,火,"chart Energy applied directly, naturally, vig...",1,日=火,2019
66,2019-06-18,37.1,太陽弧,升交點,=,福點,chart,0,升交點=福點,2019
67,2019-10-15,37.4,太陽弧,金,=,AC,chart Niceness; being appreciated.,1,金=AC,2019

In [946]:
df[df['特別角度']==1]['year'].value_counts().sort_index()

2002    1
2003    2
2005    1
2006    1
2007    1
2008    2
2015    1
2016    2
2019    2
Name: year, dtype: int64

In [947]:
#value count 特別角度 by year，get the count of 特別角度 = True by year,sort by year
df[df['特別角度']==1]['year'].value_counts().sort_index()

# plot graph of 特別角度 = True by year using plotly
import plotly.express as px
fig = px.bar(df[df['特別角度']==1]['year'].value_counts().sort_index(), title='結婚機會 by year')

# show all years in the graph
fig.update_xaxes(tick0=0, dtick=1)
fig.show()

In [950]:
# get rows where year = 2035
df[df['year']==2010]

            日期    歲數   類別  事件 事件.1 事件.2     描述  特別角度   事件合併  year
31  2010-04-29  28.0  太陽弧  冥王    =   福點  chart     0  冥王=福點  2010

In [949]:
# 1992-02-13	30.5	太陽弧	T	=	P	chart Extreme force; persuasion; control; brutality; excessive effort.
# 1992-05-19	30.8	太陽弧	‹	=	Q	chart New contacts come into the life.
# 1992-06-07	30.8	太陽弧	Q	=	<	chart
# 1992-06-07	30.8	太陽弧	W	=	Z	chart Focus on personal needs and relationships to fulfill them.
# 1992-09-03	31.1	太陽弧	U	=	I	chart Tension between the avant-garde and the conventional; the new and the old; feeling controls; need to fight for gains.