In [1]:
import gc
import numpy as np
import os
import re
import sys
import pandas as pd
import tensorflow_data_validation as tfdv

#VERSION = "20221025"
DATA_DIR = r"Z:\13.Data Science\Projects\2022_GI_Xsell\Data"
PROJECT_DIR = "../"
RAW_DATA_DIR = os.path.join(DATA_DIR, "raw")
PROCESSED_DATA_DIR = os.path.join(DATA_DIR, "processed")
META_DATA_DIR = os.path.join(DATA_DIR, "meta_and_reference_data")
VER_1025_DIR = os.path.join(RAW_DATA_DIR, "20221025")
VER_1118_DIR = os.path.join(RAW_DATA_DIR, "20221118")
VER_1122_DIR = os.path.join(RAW_DATA_DIR, "20221122")
VER_1212_DIR = os.path.join(RAW_DATA_DIR, "20221212")
GI_DATA_DIR = os.path.join(RAW_DATA_DIR, "GI")
PA_DATA_DIR = os.path.join(GI_DATA_DIR, "Travel", "202210")
sys.path.insert(0, DATA_DIR)
sys.path.insert(0, PROJECT_DIR)

from datetime import datetime
from dateutil.relativedelta import relativedelta

# from src.utils.common import PLAN_TYPE_LST, WGP_LST, INFORCE_STATUS_LST
# from src.utils.helper_function import find_plan_type, one_hot

In [2]:
pd.set_option('display.width', None)
pd.set_option('max_colwidth', None)
# pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
BASESTAT_FILE = os.path.join(PA_DATA_DIR, "basestat.parquet")
CLAMBASE_FILE = os.path.join(PA_DATA_DIR, "clambase_df.parquet")
PREMBASE_FILE = os.path.join(PA_DATA_DIR, "prembase.parquet")
CLIENT_DATA_MAPPING_FILE = os.path.join(PROCESSED_DATA_DIR, "processed_client_data.parquet")

In [4]:
prembase_df = pd.read_parquet(PREMBASE_FILE)
clambase_df = pd.read_parquet(CLAMBASE_FILE)
basestat_df = pd.read_parquet(BASESTAT_FILE)

In [9]:
clambase_df

,CLAIM,CNTTYPE,RSKNO,DATOCC,DATREP,CLSTAT,MEVENT,SERVBR,contrnb,ldf,clmldf,zdmind_clm,clmdsc,RSCD,rscd_des,chgbal_n,paymnt_n,chgbal_g,paymnt_g,incur_g,incur_n,ultincur_n,ay,am,nb_clm,ult_clm,nb_rscd,large,lrg_nb_clm,AF_nb_clm,AF_ultclm,AF_incur_g,AF_incur_n,AF_ultincur,AL_nb_clm,AL_ultclm,AL_incur_g,AL_incur_n,AL_ultincur,AQ_nb_clm,AQ_ultclm,AQ_incur_g,AQ_incur_n,AQ_ultincur,AW_nb_clm,AW_ultclm,AW_incur_g,AW_incur_n,AW_ultincur,BD_nb_clm,BD_ultclm,BD_incur_g,BD_incur_n,BD_ultincur,BP_nb_clm,BP_ultclm,BP_incur_g,BP_incur_n,BP_ultincur,BU_nb_clm,BU_ultclm,BU_incur_g,BU_incur_n,BU_ultincur,CA_nb_clm,CA_ultclm,CA_incur_g,CA_incur_n,CA_ultincur,CB_nb_clm,CB_ultclm,CB_incur_g,CB_incur_n,CB_ultincur,CD_nb_clm,CD_ultclm,CD_incur_g,CD_incur_n,CD_ultincur,CE_nb_clm,CE_ultclm,CE_incur_g,CE_incur_n,CE_ultincur,CI_nb_clm,CI_ultclm,CI_incur_g,CI_incur_n,CI_ultincur,CK_nb_clm,CK_ultclm,CK_incur_g,CK_incur_n,CK_ultincur,CM_nb_clm,CM_ultclm,CM_incur_g,CM_incur_n,CM_ultincur,CO_nb_clm,CO_ultclm,CO_incur_g,CO_incur_n,CO_ultincur,CS_nb_clm,CS_ultclm,CS_incur_g,CS_incur_n,CS_ultincur,CU_nb_clm,CU_ultclm,CU_incur_g,CU_incur_n,CU_ultincur,DE_nb_clm,DE_ultclm,DE_incur_g,DE_incur_n,DE_ultincur,DI_nb_clm,DI_ultclm,DI_incur_g,DI_incur_n,DI_ultincur,DN_nb_clm,DN_ultclm,DN_incur_g,DN_incur_n,DN_ultincur,DP_nb_clm,DP_ultclm,DP_incur_g,DP_incur_n,DP_ultincur,DY_nb_clm,DY_ultclm,DY_incur_g,DY_incur_n,DY_ultincur,EA_nb_clm,EA_ultclm,EA_incur_g,EA_incur_n,EA_ultincur,EF_nb_clm,EF_ultclm,EF_incur_g,EF_incur_n,EF_ultincur,EV_nb_clm,EV_ultclm,EV_incur_g,EV_incur_n,EV_ultincur,FE_nb_clm,FE_ultclm,FE_incur_g,FE_incur_n,FE_ultincur,FG_nb_clm,FG_ultclm,FG_incur_g,FG_incur_n,FG_ultincur,GH_nb_clm,GH_ultclm,GH_incur_g,GH_incur_n,GH_ultincur,GQ_nb_clm,GQ_ultclm,GQ_incur_g,GQ_incur_n,GQ_ultincur,HC_nb_clm,HC_ultclm,HC_incur_g,HC_incur_n,HC_ultincur,HE_nb_clm,HE_ultclm,HE_incur_g,HE_incur_n,HE_ultincur,HS_nb_clm,HS_ultclm,HS_incur_g,HS_incur_n,HS_ultincur,IC_nb_clm,IC_ultclm,IC_incur_g,IC_incur_n,IC_ultincur,IF_nb_clm,IF_ultclm,IF_incur_g,IF_incur_n,IF_ultincur,IN_nb_clm,IN_ultclm,IN_incur_g,IN_incur_n,IN_ultincur,IP_nb_clm,IP_ultclm,IP_incur_g,IP_incur_n,IP_ultincur,LK_nb_clm,LK_ultclm,LK_incur_g,LK_incur_n,LK_ultincur,ME_nb_clm,ME_ultclm,ME_incur_g,ME_incur_n,ME_ultincur,MO_nb_clm,MO_ultclm,MO_incur_g,MO_incur_n,MO_ultincur,MS_nb_clm,MS_ultclm,MS_incur_g,MS_incur_n,MS_ultincur,OD_nb_clm,OD_ultclm,OD_incur_g,OD_incur_n,OD_ultincur,OL_nb_clm,OL_ultclm,OL_incur_g,OL_incur_n,OL_ultincur,OP_nb_clm,OP_ultclm,OP_incur_g,OP_incur_n,OP_ultincur,OT_nb_clm,OT_ultclm,OT_incur_g,OT_incur_n,OT_ultincur,PA_nb_clm,PA_ultclm,PA_incur_g,PA_incur_n,PA_ultincur,PB_nb_clm,PB_ultclm,PB_incur_g,PB_incur_n,PB_ultincur,PE_nb_clm,PE_ultclm,PE_incur_g,PE_incur_n,PE_ultincur,PL_nb_clm,PL_ultclm,PL_incur_g,PL_incur_n,PL_ultincur,PO_nb_clm,PO_ultclm,PO_incur_g,PO_incur_n,PO_ultincur,PQ_nb_clm,PQ_ultclm,PQ_incur_g,PQ_incur_n,PQ_ultincur,PW_nb_clm,PW_ultclm,PW_incur_g,PW_incur_n,PW_ultincur,RC_nb_clm,RC_ultclm,RC_incur_g,RC_incur_n,RC_ultincur,RE_nb_clm,RE_ultclm,RE_incur_g,RE_incur_n,RE_ultincur,RH_nb_clm,RH_ultclm,RH_incur_g,RH_incur_n,RH_ultincur,SA_nb_clm,SA_ultclm,SA_incur_g,SA_incur_n,SA_ultincur,SI_nb_clm,SI_ultclm,SI_incur_g,SI_incur_n,SI_ultincur,SK_nb_clm,SK_ultclm,SK_incur_g,SK_incur_n,SK_ultincur,TB_nb_clm,TB_ultclm,TB_incur_g,TB_incur_n,TB_ultincur,TC_nb_clm,TC_ultclm,TC_incur_g,TC_incur_n,TC_ultincur,TD_nb_clm,TD_ultclm,TD_incur_g,TD_incur_n,TD_ultincur,TH_nb_clm,TH_ultclm,TH_incur_g,TH_incur_n,TH_ultincur,TI_nb_clm,TI_ultclm,TI_incur_g,TI_incur_n,TI_ultincur,TP_nb_clm,TP_ultclm,TP_incur_g,TP_incur_n,TP_ultincur,UI_nb_clm,UI_ultclm,UI_incur_g,UI_incur_n,UI_ultincur,WB_nb_clm,WB_ultclm,WB_incur_g,WB_incur_n,WB_ultincur,lrg_incur_g,lrg_incur_n,lrg_ultincur,ClosedRSCD,ClosedClm,PLASIC,COUNTRY,DTEEFF,CCDATE,ZDMIND
0,Y0383836,STX,2.0,20160228.0,20160314.0,2,NA,20,00300316,0.952674,1.0,N,Damage to baggage ella,PB,PERSONAL EFFECTS,0.0,650.0,0.0,650.0,650.0,650.0,619.23810,2016.0,201602.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,650.0,650.0,619.23810,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,None,None,20151119.0,20151119.0,N
1,Y0458943,STX,2.0,20170423.0,20170508.0,2,NA,20,00300316,0.985146,1.0,N,Damage to baggage JET-080517,PB,PERSONAL EFFECTS,0.0,600.0,0.0,600.0,600.0,600.0,591.08760,2017.0,201704.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,600.0,600.0,591.08760,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,None,None,20161119.0,20161119.0,N
2,9T01ZMNA,STX,2.0,20190606.0,20190618.0,2,NA,20,00300316,0.996253,1.0,N,Damage to baggage,PB,PERSONAL EFFECTS,0.0,650.0,0.0,650.0,650.0,650.0,647.56445,2019.0,201906.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,650.0,650.0,647.56445,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,HK,HK,20181119.0,20181119.0,N
3,0T035GYA,STX,2.0,20200212.0,20200316.0,2,NA,20,00300316,1.172743,1.0,N,Damage to baggage,PB,PERSONAL EFFECTS,0.0,730.0,0.0,730.0,730.0,730.0,856.10239,2020.0,202002.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,730.0,730.0,856.10239,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,During travel,HK,20191119.0,20191119.0,N
4,Y0459414,STX,2.0,20170428.0,20170510.0,2,NA,20,00300858,0.985146,1.0,N,Travel Delay JET-100517,TD,TRAVEL DELAY,0.0,250.0,0.0,250.0,250.0,250.0,246.28650,2017.0,201704.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,250.0,250.0,246.2865,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,None,None,20161121.0,20161121.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227197,2T05KFIA,STJ,1.0,20221015.0,20221017.0,1,NA,10,Z1654225,0.688157,1.0,N,Cancellation of trip,CA,CANCELLATION OF TRIP,4000.0,0.0,4000.0,0.0,4000.0,4000.0,2752.62800,2022.0,202210.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,4000.0,4000.0,2752.628,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Hong Kong,HK,20221015.0,20221015.0,N
227198,2T05L72A,STJ,1.0,20221021.0,20221023.0,1,COVID19,10,Z1655000,0.688157,1.0,N,Medical expenses(dx: COVID-19); Trip Curtailment,CU,CURTAILMENT,5000.0,0.0,5000.0,0.0,5000.0,5000.0,3440.78500,2022.0,202210.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,5000.0,5000.0,3440.785,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,.,MAL,20221017.0,20221016.0,N
227199,2T05L72A,STJ,1.0,20221021.0,20221023.0,1,COVID19,10,Z1655000,0.688157,1.0,N,Medical expenses(dx: COVID-19); Trip Curtailment,ME,MEDICAL EXPENSES,10000.0,0.0,10000.0,0.0,10000.0,10000.0,6881.57000,2022.0,202210.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,10000.0,10000.0,6881.57,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,.,MAL,20221017.0,20221016.0,N
227200,2T05LCWA,STJ,1.0,20221022.0,20221024.0,1,COVID19,10,Z1655392,0.688157,1.0,N,Cancellation of trip,CA,CANCELLATION OF TRIP,5000.0,0.0,5000.0,0.0,5000.0,5000.0,3440.78500,2022.0,202210.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,5000.0,5000.0,3440.785,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,HK,HK,20221022.0,20221022.0,N

In [10]:
# create a new column to indicate the claim type by getting the first word of each clmdsc
clambase_df["claim_type"] = clambase_df["clmdsc"].str.split(" ").str[0]

In [22]:
# value count rscd_des
clambase_df["rscd_des"].value_counts()

# get unique rscd_des and put them into a list
rscd_des_lst = clambase_df["rscd_des"].unique().tolist()

In [23]:
rscd_des_lst

['PERSONAL EFFECTS',
 'TRAVEL DELAY',
 'Investigation Fee',
 'MONEY',
 'MEDICAL EXPENSES',
 'CANCELLATION OF TRIP',
 'BAGGAGE DELAY',
 'CURTAILMENT',
 None,
 'PA Death',
 'Emergency Assistance Fee',
 'REPATRIATION EXPENSES',
 '?PERSONAL EFFECTS',
 'EMERGENCY EVACUATION EXPENSES',
 'In-Hospital Daily Cash Benefit',
 'THIRD PARTIES PROPERTY DAMAGE',
 'Medical Expenses',
 'Miscellaneous Fee',
 'Hole in One',
 'CARD LOAN',
 'Adjusters/Survey Fee',
 'OWN LAGAL COST',
 'Third Party Bodily Injury',
 'HOSPITALISATION & SURGICAL CLM',
 '?ALL RISKS -PRIVATE WORLDWIDE',
 'MEDICAL CLAIM',
 '?PERSONAL ACCIDENT CLAIM',
 '?BURGLARY- PRIVATE CLAIM',
 '?Sum Insured',
 'Funeral Expenses',
 'THIRD PARTIES LEGAL COST',
 'PA Total Disability',
 'HOLE IN ONE',
 'Repatriation Expenses',
 'Recovery',
 'CONTENTS',
 'PA Disability - Partial',
 'Hospital Expenses',
 '?PUBLIC LIABILITY CLAIM',
 'PERSONAL BAGGAGE CLAIM',
 '?PERSONAL LIABILITY FOR HELPER',
 '?Clinical Expenses',
 'Sum Insured',
 'Own Legal Cost',
 "?BONE-SETTER'S FEE",
 'THIRD PARTY PROPERTY DAMAGE']

In [28]:
# remove the None value from the list
# rscd_des_lst.remove(None)

# make all string to upper case
rscd_des_lst = [rscd_des.upper() for rscd_des in rscd_des_lst]
# get only medical hospital clinical related rscd_des from the list
medical_rscd_des_lst = [rscd_des for rscd_des in rscd_des_lst if "MEDICAL" in rscd_des or "HOSPITAL" in rscd_des or "CLINICAL" in rscd_des]

In [29]:
medical_rscd_des_lst

['MEDICAL EXPENSES',
 'IN-HOSPITAL DAILY CASH BENEFIT',
 'MEDICAL EXPENSES',
 'HOSPITALISATION & SURGICAL CLM',
 'MEDICAL CLAIM',
 'HOSPITAL EXPENSES',
 '?CLINICAL EXPENSES']

In [30]:
# make all string to upper case in the col rscd_des
clambase_df["rscd_des"] = clambase_df["rscd_des"].str.upper()

In [31]:
# get all rows where rscd_des is in the medical_rscd_des_lst
medical_rscd_des_df = clambase_df[clambase_df["rscd_des"].isin(medical_rscd_des_lst)]
medical_rscd_des_df

,CLAIM,CNTTYPE,RSKNO,DATOCC,DATREP,CLSTAT,MEVENT,SERVBR,contrnb,ldf,clmldf,zdmind_clm,clmdsc,RSCD,rscd_des,chgbal_n,paymnt_n,chgbal_g,paymnt_g,incur_g,incur_n,ultincur_n,ay,am,nb_clm,ult_clm,nb_rscd,large,lrg_nb_clm,AF_nb_clm,AF_ultclm,AF_incur_g,AF_incur_n,AF_ultincur,AL_nb_clm,AL_ultclm,AL_incur_g,AL_incur_n,AL_ultincur,AQ_nb_clm,AQ_ultclm,AQ_incur_g,AQ_incur_n,AQ_ultincur,AW_nb_clm,AW_ultclm,AW_incur_g,AW_incur_n,AW_ultincur,BD_nb_clm,BD_ultclm,BD_incur_g,BD_incur_n,BD_ultincur,BP_nb_clm,BP_ultclm,BP_incur_g,BP_incur_n,BP_ultincur,BU_nb_clm,BU_ultclm,BU_incur_g,BU_incur_n,BU_ultincur,CA_nb_clm,CA_ultclm,CA_incur_g,CA_incur_n,CA_ultincur,CB_nb_clm,CB_ultclm,CB_incur_g,CB_incur_n,CB_ultincur,CD_nb_clm,CD_ultclm,CD_incur_g,CD_incur_n,CD_ultincur,CE_nb_clm,CE_ultclm,CE_incur_g,CE_incur_n,CE_ultincur,CI_nb_clm,CI_ultclm,CI_incur_g,CI_incur_n,CI_ultincur,CK_nb_clm,CK_ultclm,CK_incur_g,CK_incur_n,CK_ultincur,CM_nb_clm,CM_ultclm,CM_incur_g,CM_incur_n,CM_ultincur,CO_nb_clm,CO_ultclm,CO_incur_g,CO_incur_n,CO_ultincur,CS_nb_clm,CS_ultclm,CS_incur_g,CS_incur_n,CS_ultincur,CU_nb_clm,CU_ultclm,CU_incur_g,CU_incur_n,CU_ultincur,DE_nb_clm,DE_ultclm,DE_incur_g,DE_incur_n,DE_ultincur,DI_nb_clm,DI_ultclm,DI_incur_g,DI_incur_n,DI_ultincur,DN_nb_clm,DN_ultclm,DN_incur_g,DN_incur_n,DN_ultincur,DP_nb_clm,DP_ultclm,DP_incur_g,DP_incur_n,DP_ultincur,DY_nb_clm,DY_ultclm,DY_incur_g,DY_incur_n,DY_ultincur,EA_nb_clm,EA_ultclm,EA_incur_g,EA_incur_n,EA_ultincur,EF_nb_clm,EF_ultclm,EF_incur_g,EF_incur_n,EF_ultincur,EV_nb_clm,EV_ultclm,EV_incur_g,EV_incur_n,EV_ultincur,FE_nb_clm,FE_ultclm,FE_incur_g,FE_incur_n,FE_ultincur,FG_nb_clm,FG_ultclm,FG_incur_g,FG_incur_n,FG_ultincur,GH_nb_clm,GH_ultclm,GH_incur_g,GH_incur_n,GH_ultincur,GQ_nb_clm,GQ_ultclm,GQ_incur_g,GQ_incur_n,GQ_ultincur,HC_nb_clm,HC_ultclm,HC_incur_g,HC_incur_n,HC_ultincur,HE_nb_clm,HE_ultclm,HE_incur_g,HE_incur_n,HE_ultincur,HS_nb_clm,HS_ultclm,HS_incur_g,HS_incur_n,HS_ultincur,IC_nb_clm,IC_ultclm,IC_incur_g,IC_incur_n,IC_ultincur,IF_nb_clm,IF_ultclm,IF_incur_g,IF_incur_n,IF_ultincur,IN_nb_clm,IN_ultclm,IN_incur_g,IN_incur_n,IN_ultincur,IP_nb_clm,IP_ultclm,IP_incur_g,IP_incur_n,IP_ultincur,LK_nb_clm,LK_ultclm,LK_incur_g,LK_incur_n,LK_ultincur,ME_nb_clm,ME_ultclm,ME_incur_g,ME_incur_n,ME_ultincur,MO_nb_clm,MO_ultclm,MO_incur_g,MO_incur_n,MO_ultincur,MS_nb_clm,MS_ultclm,MS_incur_g,MS_incur_n,MS_ultincur,OD_nb_clm,OD_ultclm,OD_incur_g,OD_incur_n,OD_ultincur,OL_nb_clm,OL_ultclm,OL_incur_g,OL_incur_n,OL_ultincur,OP_nb_clm,OP_ultclm,OP_incur_g,OP_incur_n,OP_ultincur,OT_nb_clm,OT_ultclm,OT_incur_g,OT_incur_n,OT_ultincur,PA_nb_clm,PA_ultclm,PA_incur_g,PA_incur_n,PA_ultincur,PB_nb_clm,PB_ultclm,PB_incur_g,PB_incur_n,PB_ultincur,PE_nb_clm,PE_ultclm,PE_incur_g,PE_incur_n,PE_ultincur,PL_nb_clm,PL_ultclm,PL_incur_g,PL_incur_n,PL_ultincur,PO_nb_clm,PO_ultclm,PO_incur_g,PO_incur_n,PO_ultincur,PQ_nb_clm,PQ_ultclm,PQ_incur_g,PQ_incur_n,PQ_ultincur,PW_nb_clm,PW_ultclm,PW_incur_g,PW_incur_n,PW_ultincur,RC_nb_clm,RC_ultclm,RC_incur_g,RC_incur_n,RC_ultincur,RE_nb_clm,RE_ultclm,RE_incur_g,RE_incur_n,RE_ultincur,RH_nb_clm,RH_ultclm,RH_incur_g,RH_incur_n,RH_ultincur,SA_nb_clm,SA_ultclm,SA_incur_g,SA_incur_n,SA_ultincur,SI_nb_clm,SI_ultclm,SI_incur_g,SI_incur_n,SI_ultincur,SK_nb_clm,SK_ultclm,SK_incur_g,SK_incur_n,SK_ultincur,TB_nb_clm,TB_ultclm,TB_incur_g,TB_incur_n,TB_ultincur,TC_nb_clm,TC_ultclm,TC_incur_g,TC_incur_n,TC_ultincur,TD_nb_clm,TD_ultclm,TD_incur_g,TD_incur_n,TD_ultincur,TH_nb_clm,TH_ultclm,TH_incur_g,TH_incur_n,TH_ultincur,TI_nb_clm,TI_ultclm,TI_incur_g,TI_incur_n,TI_ultincur,TP_nb_clm,TP_ultclm,TP_incur_g,TP_incur_n,TP_ultincur,UI_nb_clm,UI_ultclm,UI_incur_g,UI_incur_n,UI_ultincur,WB_nb_clm,WB_ultclm,WB_incur_g,WB_incur_n,WB_ultincur,lrg_incur_g,lrg_incur_n,lrg_ultincur,ClosedRSCD,ClosedClm,PLASIC,COUNTRY,DTEEFF,CCDATE,ZDMIND,claim_type,claim_type_c
8,14398296,STM,2.0,20141023.0,20141118.0,2,NA,20,00301996,1.001559,1.0,Y,Medical expenses (Dx Sprain) Mr. Battistella Nichloas Peter at 141120,ME,MEDICAL EXPENSES,0.000000e+00,0.00,0.000000e+00,0.00,0.00,0.00,0.000000,2014.0,201410.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.00,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,None,None,NaN,NaN,NaN,Medical,M
13,9T02CV7A,STX,2.0,20190729.0,20190903.0,2,NA,20,00304137,0.996253,1.0,N,Medical expenses(DX.CUT OFF NAIL OF LEFT THUMB),ME,MEDICAL EXPENSES,0.000000e+00,4112.07,0.000000e+00,4112.07,4112.07,4112.07,4096.662074,2019.0,201907.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,4112.07,4112.07,4096.662074,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,UNITED KINGDOM,UK,20181216.0,20181216.0,N,Medical,M
15,9T01IFCA,STX,2.0,20190114.0,20190214.0,2,NA,20,00305513,0.996253,1.0,N,Medical expenses for spouce (DX: left foot injury ),ME,MEDICAL EXPENSES,4.547474e-13,8769.90,4.547474e-13,8769.90,8769.90,8769.90,8737.039185,2019.0,201901.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,8769.90,8769.90,8737.039185,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,China,HK,20181128.0,20181128.0,N,Medical,M
22,14434361,STX,2.0,20141223.0,20150112.0,2,NA,20,00307066,1.001559,1.0,Y,Medical expenses Jane gwis 140514,ME,MEDICAL EXPENSES,0.000000e+00,0.00,0.000000e+00,0.00,0.00,0.00,0.000000,2014.0,201412.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.00,0.00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,None,None,NaN,NaN,NaN,Medical,M
28,Y0450363,STX,2.0,20170222.0,20170311.0,2,NA,20,00308598,0.985146,1.0,N,Medical Expenses (Dx. phiryngitis) Constance Kwan,ME,MEDICAL EXPENSES,0.000000e+00,1156.75,0.000000e+00,1156.75,1156.75,1156.75,1139.567636,2017.0,201702.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1156.75,1156.75,1139.567636,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,None,None,20161208.0,20161208.0,N,Medical,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227187,2T05JRBA,STS,1.0,20220602.0,20220915.0,2,NA,10,Z1652485,0.688157,1.0,N,2113959-1095/A01/0003880/051 MEDICAL EXPENSES AND CURTAILMENT FOR MS. LIU LI,ME,MEDICAL EXPENSES,0.000000e+00,4815.84,0.000000e+00,4815.84,4815.84,4815.84,3314.054007,2022.0,202206.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,4815.84,4815.84,3314.054007,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,UN,HK,20220601.0,20220601.0,N,2113959-1095/A01/0003880/051,2
227189,2T05JJEA,STC,1.0,20220131.0,20220915.0,2,NA,10,Z1652520,0.688157,1.0,N,2111953-1095/AB9/0029499/000-MEDICAL EXPENSED FOR STUART VALENTINE JOHN,ME,MEDICAL EXPENSES,-4.547474e-13,1745.32,-1.705303e-13,1745.32,1745.32,1745.32,1201.054175,2022.0,202201.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1745.32,1745.32,1201.054175,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,UN,HK,20220101.0,20220101.0,N,2111953-1095/AB9/0029499/000-MEDICAL,2
227190,2T05JKFA,STC,1.0,20220506.0,20220915.0,2,NA,10,Z1652522,0.688157,1.0,N,2115086-1095/AB9/0029528/003-MEDICAL EXPENSES FOR MA KWOK KAY,ME,MEDICAL EXPENSES,7.389644e-13,149.66,9.663381e-13,149.66,149.66,149.66,102.989577,2022.0,202205.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,149.66,149.66,102.989577,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,UN,HK,20220501.0,20220501.0,N,2115086-1095/AB9/0029528/003-MEDICAL,2

In [71]:
# get only important columns
useful_clambase_df = medical_rscd_des_df[["DATOCC","DTEEFF","DATREP","rscd_des","contrnb"]]

In [72]:
# drop duplicate rows by contrnb and DATREP
useful_clambase_df = useful_clambase_df.drop_duplicates(subset=["contrnb","DATREP"])

In [73]:
prembase_df

,contrnb,CCDATE,age,RSKNO,TRANNO,DTEEFF,gwp,commis,disc,BATCACTYR,BATCACTMN,CRATE,TRANDATE,trans_code,CNTTYPE,OCCDATE,CRDATE,REPNUM,COWNNUM,AGNTNUM,CNTBRANCH,autorenew,line,ZDMIND,ACSART,bulk,bulk_name,nbrn,tranat,nwp,commis_n,ri_inward,JACKET,product,bulk_name1,CLTTYPE,CLTSEX,CLTDOB,MARRYD,NATLTY,RSKTYP,ldteter,risk_des,INSURED,TOTSIL,ZPLNCD,ZPLANCDE,trlarea,znolive,zcmccard_banca,plan1,lastcrdate,cancdate,cancelled,dteeff_term,duration,lastznolive,plan2,plan3,ChinaCard,EnhancedPA,duration_grp,NBRN1,producer,rmisagent,rmiscode,channel,lifeagent,product2,gap_trandate_ccdate,gap_trandate_ccdate_gp,znolive_gp,age_gp,loyalty,loyalty_cat,insage_smu,inssex_smu,insage_smu_gp,disc_gp
0,00300028,20151213.0,50.0,1.0,2.0,20151213.0,423.9,127.17,0.0,2015.0,12.0,1.0,20151205.0,T413,STX,20111213.0,20161212.0,None,N5017122,E03158,20,0.0,27 - Travel Insurance,N,AXA,N,N,HB,RNWL,417.75345,127.17,N,N,MultiTrip TravelSurance (Annual),N,P,M,19651212.0,M,None,ATH,99999999.0,PA,NaN,1000000.0,C,C2,2,1.0,N,Annual,20161212.0,NaN,0.0,99999999.0,366.0,1.0,Area 2,Self & Children,N,NA,Annual,RNWL,HSBC - Dummy,608(SURANCE)-ILD,9998,Banca - HSBC,0.0,TravelSurance,8.0,3. 6 to 10 days,1. 1 person,4. Age 41 - 50,4.0,4,NaN,NaN,NaN,0. No Discount
1,00300028,20151213.0,50.0,2.0,2.0,20151213.0,2402.1,720.63,0.0,2015.0,12.0,1.0,20151205.0,T413,STX,20111213.0,20161212.0,None,N5017122,E03158,20,0.0,27 - Travel Insurance,N,AXA,N,N,HB,RNWL,2367.26955,720.63,N,N,MultiTrip TravelSurance (Annual),N,P,M,19651212.0,M,None,ATM,99999999.0,Miscellaneous,NaN,1000000.0,C,C2,2,NaN,N,Annual,20161212.0,NaN,0.0,99999999.0,0.0,NaN,Area 2,Self & Children,N,NA,Annual,RNWL,HSBC - Dummy,608(SURANCE)-ILD,9998,Banca - HSBC,0.0,TravelSurance,8.0,3. 6 to 10 days,1. 1 person,4. Age 41 - 50,4.0,4,NaN,NaN,NaN,0. No Discount
2,00300028,20161213.0,51.0,1.0,4.0,20161213.0,423.9,127.17,0.0,2016.0,12.0,1.0,20161203.0,T413,STX,20111213.0,20171212.0,None,N5017122,E03158,20,0.0,27 - Travel Insurance,N,AXA,N,N,HB,RNWL,418.60125,127.17,N,N,MultiTrip TravelSurance (Annual),N,P,M,19651212.0,M,None,ATH,99999999.0,PA,NaN,1000000.0,C,C2,2,1.0,N,Annual,20171212.0,NaN,0.0,99999999.0,365.0,1.0,Area 2,Self & Children,N,NA,Annual,RNWL,HSBC - Dummy,608(SURANCE)-ILD,9998,Banca - HSBC,0.0,TravelSurance,10.0,3. 6 to 10 days,1. 1 person,5. Age 51 - 60,5.0,5+,NaN,NaN,NaN,0. No Discount
3,00300028,20161213.0,51.0,2.0,4.0,20161213.0,2402.1,720.63,0.0,2016.0,12.0,1.0,20161203.0,T413,STX,20111213.0,20171212.0,None,N5017122,E03158,20,0.0,27 - Travel Insurance,N,AXA,N,N,HB,RNWL,2372.07375,720.63,N,N,MultiTrip TravelSurance (Annual),N,P,M,19651212.0,M,None,ATM,99999999.0,Miscellaneous,NaN,1000000.0,C,C2,2,NaN,N,Annual,20171212.0,NaN,0.0,99999999.0,0.0,NaN,Area 2,Self & Children,N,NA,Annual,RNWL,HSBC - Dummy,608(SURANCE)-ILD,9998,Banca - HSBC,0.0,TravelSurance,10.0,3. 6 to 10 days,1. 1 person,5. Age 51 - 60,5.0,5+,NaN,NaN,NaN,0. No Discount
4,00300028,20171213.0,52.0,1.0,6.0,20171213.0,423.9,127.17,0.0,2017.0,12.0,1.0,20171207.0,T413,STX,20111213.0,20181212.0,None,N5017122,E03158,20,0.0,27 - Travel Insurance,N,AXA,N,N,HB,RNWL,419.53383,127.17,N,N,MultiTrip TravelSurance (Annual),N,P,M,19651212.0,M,None,ATH,99999999.0,PA,NaN,1000000.0,C,C2,2,1.0,N,Annual,20181212.0,NaN,0.0,99999999.0,365.0,1.0,Area 2,Self & Children,N,NA,Annual,RNWL,HSBC - Dummy,608(SURANCE)-ILD,9998,Banca - HSBC,0.0,TravelSurance,6.0,3. 6 to 10 days,1. 1 person,5. Age 51 - 60,6.0,5+,NaN,NaN,NaN,0. No Discount
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4844652,Z1942661,20221026.0,9999.0,1.0,1.0,20221026.0,410.0,123.00,0.0,2022.0,10.0,1.0,20221025.0,T405,STJ,20221026.0,20221103.0,None,0784814,05038,10,0.0,27 - Travel Insurance,N,AXA,N,N,NB,NWBS,405.12100,123.00,N,STB0122A,SmartTraveller Plus (Single),N,C,NaN,NaN,NaN,None,ATP,99999999.0,PA,S0,2000000.0,None,Q4,9,1.0,NaN,Single,20221103.0,NaN,0.0,99999999.0,9.0,1.0,Prestige,Insured Only,N,Y,5. 8-10 Days,NWBS,MARSH-JARDINE LLOYD THOMPSON L,MARSH-JARDINE LLOYD THOMPSON L,MJLL,Agents & Broker,0.0,SmartTraveller Plus,1.0,2. 1 to 5 days,1. 1 person,9. unknown,-0.0,Single,NaN,NaN,NaN,0. No Discount
4844653,Z4459258,20210526.0,21.0,1.0,1.0,20210526.0,205.0,71.75,0.0,2021.0,6.0,1.0,20210603.0,T405,STJ,20210526.0,20210526.0,None,1646667,05021,10,0.0,27 - Travel Insurance,N,AXA,N,N,NB,NWBS,203.99550,71.75,N,STB1219A,SmartTraveller Plus (Single),N,P,M,19991111.0,NaN,None,ATP,99999999.0,PA,S0,2000000.0,None,Q1,9,1.0,NaN,Single,20210526.0,20210526.0,1.0,99999999.0,0.0,1.0,Prestige,Insured Only,N,Y,1. 0 Days,NWBS,Kai Fung Insurance Brokers Ltd,KAI FUNG INS BRO LTD-B2B2C,KFIB,Agents & Broker,0.0,SmartTraveller Plus,-8.0,1. 0 days or les,1. 1 person,2. Age 17 - 30,-0.0,Single,NaN,NaN,NaN,0. No Discount
4844654,Z4459258,20210526.0,21.0,1.0,2.0,20210526.0,-205.0,-71.75,0.0,2021.0,9.0,1.0,20210903.0,T454,STJ,20210526.0,20210526.0,None,1646667,05021,10,0.0,27 - Travel Insurance,N,AXA,N,N,NB,CANC,-203.99550,-71.75,N,STB1219A,SmartTraveller Plus (Single),N,P,M,19991111.0,NaN,None,ATP,99999999.0,PA,S0,2000000.0,None,Q1,9,1.0,NaN,Single,20210526.0,20210526.0,1.0,NaN,NaN,1.0,Prestige,Insured Only,N,Y,1. 0 Days,NWBS,Kai Fung Insurance Brokers Ltd,KAI FUNG INS BRO LTD-B2B2C,KFIB,Agents & Broker,0.0,SmartTraveller Plus,-8.0,1. 0 days or les,1. 1 person,2. Age 17 - 30,-0.0,Single,NaN,NaN,NaN,0. No Discount
4844655,ZS753243,20160319.0,30.0,1.0,1.0,20160319.0,304.0,0.00,0.0,2016.0,3.0,1.0,20160321.0,T405,STC,20160319.0,20160326.0,None,0920580,04203,10,0.0,27 - Travel Insurance,N,AXA,N,N,NB,NWBS,300.20000,0.00,N,STS0116,SmartTraveller (Single),N,P,M,19850630.0,NaN,HK,ATP,99999999.0,PA,IO,1000000.0,None,V8,9,1.0,NaN,Single,20160326.0,20160319.0,1.0,99999999.0,0.0,1.0,VIP,Insured Only,N,Y,1. 0 Days,NWBS,Travel SWAP,TRAVEL SWAP,GT03,AXA Online Direct,0.0,SmartTraveller,-2.0,1. 0 days or les,1. 1 person,2. Age 17 - 30,-0.0,Single,NaN,NaN,NaN,0. No Discount
4844656,ZS753243,20160319.0,30.0,1.0,2.0,20160319.0,-304.0,0.00,0.0,2016.0,4.0,1.0,20160329.0,T454,STC,20160319.0,20160326.0,None,0920580,04203,10,0.0,27 - Travel Insurance,N,AXA,N,N,NB,CANC,-300.20000,0.00,N,STS0116,SmartTraveller (Single),N,P,M,19850630.0,NaN,HK,ATP,99999999.0,PA,IO,1000000.0,None,V8,9,1.0,NaN,Single,20160326.0,20160319.0,1.0,NaN,NaN,1.0,VIP,Insured Only,N,Y,1. 0 Days,NWBS,Travel SWAP,TRAVEL SWAP,GT03,AXA Online Direct,0.0,SmartTraveller,-2.0,1. 0 days or les,1. 1 person,2. Age 17 - 30,-0.0,Single,NaN,NaN,NaN,0. No Discount

In [74]:
# get only important columns from prembase_df
useful_prembase_df = prembase_df[["COWNNUM","contrnb","CLTSEX","MARRYD","age_gp","CLTDOB"]]

In [75]:
# drop duplicate rows of prembase_df by all columns
useful_prembase_df = useful_prembase_df.drop_duplicates()

In [76]:
useful_prembase_df

          COWNNUM   contrnb CLTSEX MARRYD          age_gp      CLTDOB
0        N5017122  00300028      M      M  4. Age 41 - 50  19651212.0
2        N5017122  00300028      M      M  5. Age 51 - 60  19651212.0
14       N5022188  00300316      M      M  2. Age 17 - 30  19881027.0
22       N5022188  00300316      M      M  3. Age 31 - 40  19881027.0
36       N5030025  00300858      M      M  5. Age 51 - 60  19630815.0
...           ...       ...    ...    ...             ...         ...
4844650   1046004  Z1942637    NaN    NaN  6. Age 61 - 70  19601025.0
4844651   0361142  Z1942650      M    NaN  4. Age 41 - 50  19790324.0
4844652   0784814  Z1942661    NaN    NaN      9. unknown         NaN
4844653   1646667  Z4459258      M    NaN  2. Age 17 - 30  19991111.0
4844655   0920580  ZS753243      M    NaN  2. Age 17 - 30  19850630.0

[2442119 rows x 6 columns]

In [77]:
useful_clambase_df.shape

(37673, 5)

In [78]:
# merge useful_clambase_drop_not_in_usefulprembase with useful_prembase_w_client_df on contrnb only

p_c = pd.merge(useful_prembase_df, useful_clambase_df, on=['contrnb'], how='right')
p_c.shape

(40659, 10)

In [79]:
CLIENT_DATA_MAPPING_FILE = os.path.join(PROCESSED_DATA_DIR, "processed_client_data.parquet")
# read in processed_client_data_df
client_data_df = pd.read_parquet(CLIENT_DATA_MAPPING_FILE)

In [80]:
client_data_df

,CLNTNUM,VALIDFLAG,CLTTYPE,SECUITYNO,CLTSEX,OCCPCODE,CLTDOB,START_DATE,MARRYD,NATLTY,modified_SECUITYNO
0,0000001,1,C,unknown,None,None,99999999.0,19950314.0,None,None,unknown
1,0000003,1,C,unknown,None,None,99999999.0,19950314.0,None,None,unknown
2,0000002,1,C,348147,None,None,99999999.0,19950314.0,None,None,348147
3,0000004,1,C,unknown,None,None,99999999.0,19950314.0,None,None,unknown
4,0000005,1,C,unknown,None,None,99999999.0,19950314.0,None,None,unknown
...,...,...,...,...,...,...,...,...,...,...,...
6139945,6080439,1,P,K565428(9),M,None,99999999.0,20220625.0,None,None,K565428
6139946,6080440,1,P,M264473(3),F,None,99999999.0,20220625.0,None,None,M264473
6139947,1709379,1,P,Y492127(3),M,NURS,19950420.0,20220625.0,S,XXX,Y492127
6139948,1709380,1,P,Y381215(2),F,NURS,19950109.0,20220625.0,S,XXX,Y381215
6139949,6080441,1,P,E868236(8),M,None,19620610.0,20220625.0,None,None,E868236

In [81]:
#get only important columns from client_data_df
useful_client_data_df = client_data_df[["CLNTNUM","CLTSEX","MARRYD","CLTDOB"]]

In [82]:
# drop duplicate rows of client_data_df by all columns
useful_client_data_df = useful_client_data_df.drop_duplicates()

In [83]:
#merge useful_client_data_df with p_c on COWNNUM and CLNTNUM on the right
p_c_c = pd.merge(p_c, useful_client_data_df, left_on='COWNNUM', right_on='CLNTNUM', how='left')

In [84]:
p_c_c

,COWNNUM,contrnb,CLTSEX_x,MARRYD_x,age_gp,CLTDOB_x,DATOCC,DTEEFF,DATREP,rscd_des,CLNTNUM,CLTSEX_y,MARRYD_y,CLTDOB_y
0,N1018368,00301996,NaN,NaN,9. unknown,NaN,20141023.0,NaN,20141118.0,MEDICAL EXPENSES,N1018368,None,None,99999999.0
1,N5056861,00304137,M,NaN,7. Age 71 - 80,19410926.0,20190729.0,20181216.0,20190903.0,MEDICAL EXPENSES,N5056861,M,None,19410926.0
2,N5074433,00305513,F,M,5. Age 51 - 60,19570612.0,20190114.0,20181128.0,20190214.0,MEDICAL EXPENSES,N5074433,F,M,19570612.0
3,N5074433,00305513,F,M,6. Age 61 - 70,19570612.0,20190114.0,20181128.0,20190214.0,MEDICAL EXPENSES,N5074433,F,M,19570612.0
4,N5083171,00307066,F,S,6. Age 61 - 70,19531225.0,20141223.0,NaN,20150112.0,MEDICAL EXPENSES,N5083171,F,S,19531225.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40654,1735438,Z1652485,NaN,NaN,9. unknown,NaN,20220602.0,20220601.0,20220915.0,MEDICAL EXPENSES,NaN,NaN,NaN,NaN
40655,1735428,Z1652520,NaN,NaN,9. unknown,99999999.0,20220131.0,20220101.0,20220915.0,MEDICAL EXPENSES,NaN,NaN,NaN,NaN
40656,1658474,Z1652522,NaN,NaN,9. unknown,NaN,20220506.0,20220501.0,20220915.0,MEDICAL EXPENSES,1658474,None,None,99999999.0
40657,1735429,Z1652523,NaN,NaN,9. unknown,NaN,20220422.0,20220401.0,20220915.0,MEDICAL EXPENSES,NaN,NaN,NaN,NaN
40658,1743425,Z1655000,F,NaN,2. Age 17 - 30,19940427.0,20221021.0,20221017.0,20221023.0,MEDICAL EXPENSES,NaN,NaN,NaN,NaN

In [85]:
# merge CLTDOB_x and CLTDOB_y to CLTDOB, get the cell with non NaN value
p_c_c["CLTDOB"] = p_c_c["CLTDOB_x"].combine_first(p_c_c["CLTDOB_y"])

In [86]:
# combine CLTSEX_x and CLTSEX_y to CLTSEX, get the cell with non NaN value
p_c_c["CLTSEX"] = p_c_c["CLTSEX_x"].combine_first(p_c_c["CLTSEX_y"])

In [87]:
# combine MARRYD_x and MARRYD_y to MARRYD, get the cell with non NaN value
p_c_c["MARRYD"] = p_c_c["MARRYD_x"].combine_first(p_c_c["MARRYD_y"])

In [88]:
# drop CLTDOB_x, CLTDOB_y, CLTSEX_x, CLTSEX_y, MARRYD_x, MARRYD_y
p_c_c = p_c_c.drop(columns=["CLTDOB_x","CLTDOB_y","CLTSEX_x","CLTSEX_y","MARRYD_x","MARRYD_y"])

In [89]:
p_c_c

,COWNNUM,contrnb,age_gp,DATOCC,DTEEFF,DATREP,rscd_des,CLNTNUM,CLTDOB,CLTSEX,MARRYD
0,N1018368,00301996,9. unknown,20141023.0,NaN,20141118.0,MEDICAL EXPENSES,N1018368,99999999.0,NaN,NaN
1,N5056861,00304137,7. Age 71 - 80,20190729.0,20181216.0,20190903.0,MEDICAL EXPENSES,N5056861,19410926.0,M,NaN
2,N5074433,00305513,5. Age 51 - 60,20190114.0,20181128.0,20190214.0,MEDICAL EXPENSES,N5074433,19570612.0,F,M
3,N5074433,00305513,6. Age 61 - 70,20190114.0,20181128.0,20190214.0,MEDICAL EXPENSES,N5074433,19570612.0,F,M
4,N5083171,00307066,6. Age 61 - 70,20141223.0,NaN,20150112.0,MEDICAL EXPENSES,N5083171,19531225.0,F,S
...,...,...,...,...,...,...,...,...,...,...,...
40654,1735438,Z1652485,9. unknown,20220602.0,20220601.0,20220915.0,MEDICAL EXPENSES,NaN,NaN,NaN,NaN
40655,1735428,Z1652520,9. unknown,20220131.0,20220101.0,20220915.0,MEDICAL EXPENSES,NaN,99999999.0,NaN,NaN
40656,1658474,Z1652522,9. unknown,20220506.0,20220501.0,20220915.0,MEDICAL EXPENSES,1658474,99999999.0,NaN,NaN
40657,1735429,Z1652523,9. unknown,20220422.0,20220401.0,20220915.0,MEDICAL EXPENSES,NaN,NaN,NaN,NaN
40658,1743425,Z1655000,2. Age 17 - 30,20221021.0,20221017.0,20221023.0,MEDICAL EXPENSES,NaN,19940427.0,F,NaN

In [90]:
#drop if CLTDOB is NaN
p_c_c = p_c_c.dropna(subset=["CLTDOB"])

In [91]:
p_c_c

,COWNNUM,contrnb,age_gp,DATOCC,DTEEFF,DATREP,rscd_des,CLNTNUM,CLTDOB,CLTSEX,MARRYD
0,N1018368,00301996,9. unknown,20141023.0,NaN,20141118.0,MEDICAL EXPENSES,N1018368,99999999.0,NaN,NaN
1,N5056861,00304137,7. Age 71 - 80,20190729.0,20181216.0,20190903.0,MEDICAL EXPENSES,N5056861,19410926.0,M,NaN
2,N5074433,00305513,5. Age 51 - 60,20190114.0,20181128.0,20190214.0,MEDICAL EXPENSES,N5074433,19570612.0,F,M
3,N5074433,00305513,6. Age 61 - 70,20190114.0,20181128.0,20190214.0,MEDICAL EXPENSES,N5074433,19570612.0,F,M
4,N5083171,00307066,6. Age 61 - 70,20141223.0,NaN,20150112.0,MEDICAL EXPENSES,N5083171,19531225.0,F,S
...,...,...,...,...,...,...,...,...,...,...,...
40652,1740457,Z1645422,3. Age 31 - 40,20221015.0,20221013.0,20221021.0,MEDICAL EXPENSES,NaN,19900104.0,F,NaN
40653,1731640,Z1649136,2. Age 17 - 30,20221010.0,20221001.0,20221014.0,MEDICAL EXPENSES,NaN,20040804.0,M,S
40655,1735428,Z1652520,9. unknown,20220131.0,20220101.0,20220915.0,MEDICAL EXPENSES,NaN,99999999.0,NaN,NaN
40656,1658474,Z1652522,9. unknown,20220506.0,20220501.0,20220915.0,MEDICAL EXPENSES,1658474,99999999.0,NaN,NaN
40658,1743425,Z1655000,2. Age 17 - 30,20221021.0,20221017.0,20221023.0,MEDICAL EXPENSES,NaN,19940427.0,F,NaN

In [92]:
# drop if CLTDOB is 99999999.0
p_c_c = p_c_c[p_c_c["CLTDOB"] != 99999999.0]

In [93]:
p_c_c

,COWNNUM,contrnb,age_gp,DATOCC,DTEEFF,DATREP,rscd_des,CLNTNUM,CLTDOB,CLTSEX,MARRYD
1,N5056861,00304137,7. Age 71 - 80,20190729.0,20181216.0,20190903.0,MEDICAL EXPENSES,N5056861,19410926.0,M,NaN
2,N5074433,00305513,5. Age 51 - 60,20190114.0,20181128.0,20190214.0,MEDICAL EXPENSES,N5074433,19570612.0,F,M
3,N5074433,00305513,6. Age 61 - 70,20190114.0,20181128.0,20190214.0,MEDICAL EXPENSES,N5074433,19570612.0,F,M
4,N5083171,00307066,6. Age 61 - 70,20141223.0,NaN,20150112.0,MEDICAL EXPENSES,N5083171,19531225.0,F,S
5,N5096852,00308598,3. Age 31 - 40,20170222.0,20161208.0,20170311.0,MEDICAL EXPENSES,N5096852,19750513.0,F,NaN
...,...,...,...,...,...,...,...,...,...,...,...
40650,1738954,Z1644684,3. Age 31 - 40,20221011.0,20221006.0,20221021.0,MEDICAL EXPENSES,NaN,19900203.0,F,NaN
40651,1740227,Z1645201,5. Age 51 - 60,20221008.0,20221008.0,20221024.0,MEDICAL EXPENSES,NaN,19710816.0,F,NaN
40652,1740457,Z1645422,3. Age 31 - 40,20221015.0,20221013.0,20221021.0,MEDICAL EXPENSES,NaN,19900104.0,F,NaN
40653,1731640,Z1649136,2. Age 17 - 30,20221010.0,20221001.0,20221014.0,MEDICAL EXPENSES,NaN,20040804.0,M,S
40658,1743425,Z1655000,2. Age 17 - 30,20221021.0,20221017.0,20221023.0,MEDICAL EXPENSES,NaN,19940427.0,F,NaN

In [94]:
# drop is CLTSEX is NaN
p_c_c = p_c_c.dropna(subset=["CLTSEX"])

In [95]:
p_c_c

,COWNNUM,contrnb,age_gp,DATOCC,DTEEFF,DATREP,rscd_des,CLNTNUM,CLTDOB,CLTSEX,MARRYD
1,N5056861,00304137,7. Age 71 - 80,20190729.0,20181216.0,20190903.0,MEDICAL EXPENSES,N5056861,19410926.0,M,NaN
2,N5074433,00305513,5. Age 51 - 60,20190114.0,20181128.0,20190214.0,MEDICAL EXPENSES,N5074433,19570612.0,F,M
3,N5074433,00305513,6. Age 61 - 70,20190114.0,20181128.0,20190214.0,MEDICAL EXPENSES,N5074433,19570612.0,F,M
4,N5083171,00307066,6. Age 61 - 70,20141223.0,NaN,20150112.0,MEDICAL EXPENSES,N5083171,19531225.0,F,S
5,N5096852,00308598,3. Age 31 - 40,20170222.0,20161208.0,20170311.0,MEDICAL EXPENSES,N5096852,19750513.0,F,NaN
...,...,...,...,...,...,...,...,...,...,...,...
40650,1738954,Z1644684,3. Age 31 - 40,20221011.0,20221006.0,20221021.0,MEDICAL EXPENSES,NaN,19900203.0,F,NaN
40651,1740227,Z1645201,5. Age 51 - 60,20221008.0,20221008.0,20221024.0,MEDICAL EXPENSES,NaN,19710816.0,F,NaN
40652,1740457,Z1645422,3. Age 31 - 40,20221015.0,20221013.0,20221021.0,MEDICAL EXPENSES,NaN,19900104.0,F,NaN
40653,1731640,Z1649136,2. Age 17 - 30,20221010.0,20221001.0,20221014.0,MEDICAL EXPENSES,NaN,20040804.0,M,S
40658,1743425,Z1655000,2. Age 17 - 30,20221021.0,20221017.0,20221023.0,MEDICAL EXPENSES,NaN,19940427.0,F,NaN

In [96]:
#conver DATOCC DTEEFF DATREP to datetime
p_c_c["DATOCC"] = pd.to_datetime(p_c_c["DATOCC"], format="%Y%m%d")
p_c_c["DTEEFF"] = pd.to_datetime(p_c_c["DTEEFF"], format="%Y%m%d")
p_c_c["DATREP"] = pd.to_datetime(p_c_c["DATREP"], format="%Y%m%d")

C:\Users\NICOLE~1.LEU\AppData\Local\Temp/ipykernel_12500/506587486.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_c_c["DATOCC"] = pd.to_datetime(p_c_c["DATOCC"], format="%Y%m%d")
C:\Users\NICOLE~1.LEU\AppData\Local\Temp/ipykernel_12500/506587486.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_c_c["DTEEFF"] = pd.to_datetime(p_c_c["DTEEFF"], format="%Y%m%d")
C:\Users\NICOLE~1.LEU\AppData\Local\Temp/ipykernel_12500/506587486.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_c_c["DATREP"] = pd.to_datetime(p_c_c["DATREP"], format="%Y%m%d")

In [97]:
# create a new col called DATOCC_year and get the year of DATOCC
p_c_c["DATOCC_year"] = p_c_c["DATOCC"].dt.year
# create a new col called DATOCC_month and get the month of DATOCC
p_c_c["DATOCC_month"] = p_c_c["DATOCC"].dt.month

C:\Users\NICOLE~1.LEU\AppData\Local\Temp/ipykernel_12500/3859077134.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_c_c["DATOCC_year"] = p_c_c["DATOCC"].dt.year
C:\Users\NICOLE~1.LEU\AppData\Local\Temp/ipykernel_12500/3859077134.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_c_c["DATOCC_month"] = p_c_c["DATOCC"].dt.month

In [98]:
# conver CLTDOB to datetime
p_c_c["CLTDOB"] = pd.to_datetime(p_c_c["CLTDOB"], format="%Y%m%d")

C:\Users\NICOLE~1.LEU\AppData\Local\Temp/ipykernel_12500/1996949336.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  p_c_c["CLTDOB"] = pd.to_datetime(p_c_c["CLTDOB"], format="%Y%m%d")

In [99]:
p_c_c

,COWNNUM,contrnb,age_gp,DATOCC,DTEEFF,DATREP,rscd_des,CLNTNUM,CLTDOB,CLTSEX,MARRYD,DATOCC_year,DATOCC_month
1,N5056861,00304137,7. Age 71 - 80,2019-07-29,2018-12-16,2019-09-03,MEDICAL EXPENSES,N5056861,1941-09-26,M,NaN,2019,7
2,N5074433,00305513,5. Age 51 - 60,2019-01-14,2018-11-28,2019-02-14,MEDICAL EXPENSES,N5074433,1957-06-12,F,M,2019,1
3,N5074433,00305513,6. Age 61 - 70,2019-01-14,2018-11-28,2019-02-14,MEDICAL EXPENSES,N5074433,1957-06-12,F,M,2019,1
4,N5083171,00307066,6. Age 61 - 70,2014-12-23,NaT,2015-01-12,MEDICAL EXPENSES,N5083171,1953-12-25,F,S,2014,12
5,N5096852,00308598,3. Age 31 - 40,2017-02-22,2016-12-08,2017-03-11,MEDICAL EXPENSES,N5096852,1975-05-13,F,NaN,2017,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40650,1738954,Z1644684,3. Age 31 - 40,2022-10-11,2022-10-06,2022-10-21,MEDICAL EXPENSES,NaN,1990-02-03,F,NaN,2022,10
40651,1740227,Z1645201,5. Age 51 - 60,2022-10-08,2022-10-08,2022-10-24,MEDICAL EXPENSES,NaN,1971-08-16,F,NaN,2022,10
40652,1740457,Z1645422,3. Age 31 - 40,2022-10-15,2022-10-13,2022-10-21,MEDICAL EXPENSES,NaN,1990-01-04,F,NaN,2022,10
40653,1731640,Z1649136,2. Age 17 - 30,2022-10-10,2022-10-01,2022-10-14,MEDICAL EXPENSES,NaN,2004-08-04,M,S,2022,10
40658,1743425,Z1655000,2. Age 17 - 30,2022-10-21,2022-10-17,2022-10-23,MEDICAL EXPENSES,NaN,1994-04-27,F,NaN,2022,10

In [100]:
# get only age DATOCC DATOCC_year DATOCC_month rscd_des CLTDOB CLTSEX MARRYD and output to parquet
p_c_c_out = p_c_c[["DATOCC","DATOCC_year","DATOCC_month","rscd_des","CLTDOB","CLTSEX","MARRYD"]]

In [101]:
# output to parquet 
p_c_c_out.to_parquet(os.path.join(PROCESSED_DATA_DIR, "clt_med_dob.parquet"), index=False)